### ISSUE TITLE
Simplify display/binding of  'Last Loaded' dates.

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1019]
An interesting idea (from ATM)

+ Make LoadSupport.LastLoadCompleted observable
+ Make RelativeTimestamp support a model 'prop', to allow efficient binding without extra rendering of parent object.

One issue to work out is how to model load failures vs. successes

**Comment by amcclain** [comment]
I'm gonna close this old ticket - we have the more specific #1368 for the binding, and I don't know that we have a clear direction or want to touch the load support integration. With the model context and the change in #1368 seems to me we should be in good shape.
