### ISSUE TITLE
Change 'commitOnChange' to default to true

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1020]

**Comment by lbwexler** [comment]
I would like to wait for Hoist 21 to do this.  Think we should probably still do it, but most appropriate to wait for a a major version.  We can avoid sacrificing any goats to the gods of semver this way.

We recently made a bug fix to remove the delay that HoistInput was imposing on  blur-based commit-- this should stop the application bugs we were seeing when a button click would get "old values. 

One concern I did notice when researching this was some discussion about the value of a false value for this property on `Select` where the user may have an intermediate value that we never want to commit.  Just want to be very careful here to think about Select differently from  TextInput, if appropriate.  The calculus may be different between the two.

**Comment by febbraiod** [comment]
Re: Select

Went over with Anselm and it looks to us that we will not have to worry about an intermediate value being committed. Select input already defaults its commitOnChange to true via its HoistInput.

Also, it looks like this property is not a propType on Select and therefore will not be overidden by Form's fieldDefaults nor formField props themselves:

```const commitOnChange = this.getDefaultedProp('commitOnChange');
        if (propTypes.commitOnChange && !isUndefined(commitOnChange)) {
            overrides.commitOnChange = commitOnChange;
        }```

Select input's value is committed via an onSelectChange handler as distinct from its onInputChange handler which is associated with the text input portion of the control, which might have been the concern regarding intermediate values. The only time this portion of the control's value is committed is if the entire value of the input is deleted:

``` @action
    onInputChange = (value, {action}) => {
        if (this.manageInputValue) {
            if (action == 'input-change') {
                this.inputValue = value;
                this._inputChangedSinceSelect = true;
                _if (!value) this.noteValueChange(null);_
            } else if (action == 'input-blur') {
                this.inputValue = null;
                this._inputChangedSinceSelect = false;
            }
        }
    };```

**Comment by lbwexler** [comment]
Don -- Can we please do this for Hoist v29, or otherwise close this one.

**Comment by febbraiod** [comment]
Wow, sorry I miss your comment here Lee. This one really got a way from us!  Is this something we still want? (Comment here seems to indicate we could do without it.) I have some time to look at this if we do.

**Comment by lbwexler** [comment]
At this point, I actually think the ship has sailed on this.  The disruption to existing apps would outweigh the gain.   (I was never 100% sure about this one,  so I may not be the most objective here)

@amcclain -- if you agree we can close this one

**Comment by amcclain** [comment]
Agreed (here in Sept 2020)
