### ISSUE TITLE
GridExportService should be more flexible about date formats

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1097]
This JS service prepares the columns for export to conform to what the server expects. This includes setting the column 'type' ('date' or 'datetime') and formatting the date to a string specific to the server's needs.

Currently it will only do this if the Column.exportFormat == ExportFormat.DATE_FMT for 'date' column type, or Column.exportFormat == ExportFormat.DATETIME_FMT for 'datetime'. Essentially we are providing a exportFormat property but then limiting that string to only one possible value.

We could start by allowing the column def to specify a exportColType property and using that to make these determinations before falling back to the Column.exportFormat.

**Comment by amcclain** [comment]
@febbraiod can you take another look at this ticket - just the ticket / idea - and let us know if it still seems worth taking on / remains actionable?

**Comment by febbraiod** [comment]
Looking

**Comment by febbraiod** [comment]
I would say it remains actionable in the sense that the problem still exists; date/datetime exporting is very rigid about formatting. If I want to export a datetime in 24hr time, for example, there does not appear to be any way to do this unless I preformat into a string and lose the date type in the excel sheet.

The question of whether on not it is worth taking on is up in the air. The original reason for this ticket was for use in a client app for which, in the end, it was decided the default format was acceptable. Also, IIRC the last I discussed this ticket with Lee (possibly in 2019) I didn't get the impression there was a lot of appetite for this change.

**Comment by amcclain** [comment]
@petradish - assigning this to you as you have been looking @ export formats recently for client work.

No need for immediate action, unless this would be a good candidate to fold into that work.
