### ISSUE TITLE
GridStateModel - allow developer to customize where state is persisted

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1173]
Currently GridStateModel, if configured for a grid, will always initialize that grid's state from localStorage and persist changes to the same.

However it also contains useful logic around extracting the consolidated state from GridModel and, even more so, safely loading saved state into GridModel.

These methods would be useful to any custom approaches to saving state - e.g. a system that allowed for multiple named views and saved their state to a preference or other storage mechanism.

We should make GridStateModel more flexible and remove the expectation that it is always the class that's actually doing the persistence and direct initialization.  

I could still be able to perform that function - and even perform it by default for backwards compatibility - but it can also be configured with that disabled and, in that mode, provide a well-structured public API on top of grid model for safely getting, observing, and setting state.

The simplest way to do this might be to make the `gridId` config optional. If provided, that would trigger the state saving/loading parts of the code.  If not, it could be used to call newly public methods such as `getState()`, `setState()`, and `resetState()` (to go back to defaults).

**Comment by haynesjm42** [comment]
A couple thoughts here..

- I think it would make sense for GridStateModel to match some of the FormModel interface/behavior wrt to how it handles init(), reset(), isDirty, etc. I think most implementations would be looking for that kind of functionality.
- Regarding the persistence layer (and this would be a big change in general, probably for the future if at all) what if we just provided the GridStateModel some kind of CrudStore (interface could be extracted from RestStore)? We could add a family of Stores for handling CRUD operations with support for persisting to a variety of locations (REST endpoint, local storage, preference, etc.). Obviously a big change but something I've thought of before and could be useful in other contexts (such as inline grid editing)

**Comment by amcclain** [comment]
+ Great point re. consistency with `FormModel` - will review with an eye towards that now.
+ I've had the same thought - without working through any details - for a while now re. the notion of a store or perhaps "adaptor" concept being useful to back a few of our systems in Hoist. I think it's something we should keep our minds on.

**Comment by amcclain** [comment]
Thought about this a bit more and had a client question on it.  I do think we should prioritize support for grid state being saved to a preference so it can follow users around. I don't want to block on a full-featured view system (which you might not always want to use) to support this use case.

We should discuss, but having the current option to persist to local storage _without having to predefine a local pref_ is also useful and I think we'd keep that....

**Comment by amcclain** [comment]
@peterjcoffman here is a ticket from last summer re. making `GridStateModel` more general.

Revisiting this in the context of making it easier for developers to route gridstate storage to a `DashViewModel` so dashboard widgets can store their grid state within the user's overall dashboard configuration.

**Comment by amcclain** [comment]
@lbwexler was talking to @peterjcoffman about this one as we are doing an ad-hoc implementation to get grid state routed to dash views in a client project - would like your thoughts on whether or not this is something we would be ready to take on now as a (hopefully small) Hoist project.

**Comment by amcclain** [comment]
Closing out this ticket - has been handled nicely by our recent `persistWith` work - don't believe there is more to do here.
