### ISSUE TITLE
Mobile Select shows AutoFill Contact button in Safari

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#1190]
Despite the mobile select not supporting text input, an AutoFill Contact button appears on the form toolbar in mobile safari. It's currently unclear what causes this.

Unclear how urgent this problem is, given that (a) it only affects Safari, which is not in use by our clients and (b) tapping the AutoFill Contact prompt has no ill-effect.

**Comment by amcclain** [comment]
Closing as low-priority / not a Hoist component issue (directly).
