### ISSUE TITLE
Add focus() method to FormModel fields

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#1203]
Currently, to focus a field in a form programmatically, one must put a reference on the field component, and access that reference through the model.
It would be a great convenience if one could just call focus() on the field object in the hoistFormModel.

Possible solutions are:

- Automatically putting a reference on every field in a hoistForm and making it available to the hoistFormModel field models, and then using the reference to get to the underlying DOM input element to focus it.
- looking up the field input DOM element by unique id attribute, and calling focus on it.  (if the unique id attribute is consistent across renders).

**Comment by lbwexler** [comment]
👍

**Comment by lbwexler** [comment]
Some evidence that this is just a core problem in the entire web and react universe.

https://github.com/facebook/react/issues/16009

Not sure what that means about whether or not we want to try to build some support for this or not.....
