### ISSUE TITLE
Support more customization of AppMenu items

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1222]
Currently the `extraItems` that can be provided to the AppBar via `appMenuButtonOptions` are always assumed to be a plain json object which are the props for a Blueprint MenuItem component. It should support being provided elements for more flexibility in the setup of the menu (like we do in other places), and it would be nice if it supported a shorthand for adding a separator like we have in context menus.

In general it seems there is a lot of room for improvement in how we are handling menus for desktop, and I think we could share of lot of things between desktop and mobile. The naming of classes and components in particular is very confusing. I would propose:

* Action class
    * Would serve as a base class for RecordAction, but would not be Record specific
    * Would replace MenuItemModel in mobile, ContextMenuItem in desktop
* ActionList class
    * Container for Actions, knows how to parse from json objects and string tokens for built-in items
    * Would serve as a base class for StoreContextMenu in desktop (maybe StoreContextMenu becomes RecordActionList?)
    * MenuModel in mobile would contain an ActionMenu?
    * Should allow extenders to specify the Action class to use for the actions (StoreContextMenu would use RecordAction) similar to what we do with Store and `defaultFieldClass`
* Components would take a spec or instance of an action or list of actions
    * Components will usually be specific to the ui toolkit for each platform, so it's important to do as much of the action parsing/processing in a platform-independent way as we can so we limit the Action family of components to presentation details
    * ActionButton and ActionBar similar to RecordActionButton/Bar
        * This could result in replacing some of our special Button components with an action spec - `actionButton({action: refreshAction})`
    * ActionMenu - replaces ContextMenu
    * ActionMenuItem and RecordActionMenuItem probably make sense
    * Equivalent components for mobile
    * etc.
* We should only use the Menu term for components, and stop using it for model/data classes

**Comment by amcclain** [comment]
Closing this as I think #2400 is a better umbrella ticket for rethinking menus at this point.
