### ISSUE TITLE
Show count of items on each side of LeftRightChooser

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1231]
Have a couple of LeftRightChooser components in a client application which contain a lot of items (around 1k), and the users have requested that we show a count of the number of items on each side of the chooser.

I see 2 options for how this could be shown:
1. Have a footer on each side which just uses a StoreCountLabel to show the count.
2. Show the count in the column header for the grid on each side in parentheses.

I like option 2 the best as it does not take up any additional vertical space in the control. This would however involve adding dynamic column header support to our Column class, and refreshing the header via `agApi.refreshHeader()` when needed (in this case when the Store data has changed for that side). Perhaps we could figure something out using an autorun?

**Comment by amcclain** [comment]
Agree working the count into the header here seems like the clear best option as far as this control is concerned. 

Ideally it would be something we could get done without needing to involve changes to our core grid stuff, but a) I realize it probably does require that and b) being able to dynamically adjust a column header sounds like a reasonable capability in general...

**Comment by lbwexler** [comment]
We have dynamic column headers as of hoist v. 28.1 -- time to revisit this!  
Think this might be a good one for Peter to work on with John Haynes

**Comment by peterjcoffman** [comment]
PR is here:

https://github.com/xh/hoist-react/compare/leftRightCounts?expand=1
