### ISSUE TITLE
Distinct styling for tree grid parent row

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1250]
Would like to explore (optional) distinct styling for tree-grid parent rows.  Something in between the full-on dark background shading of the full-width row groups and what we have now, where parents and children are only identified by their indent level.

One option we have used in the past successfully is a lighter background shading + ledger-style top border on group rows.

Would need to consider how this styling applies to nested (multi-level) groups. Should it appear on top-level groups only? Be the same for all groups? Have some gradation based on color or intensity between the levels?

**Comment by nadkarniarjun** [comment]
Some grids I've used in the past allow for bigger fonts / bolded text for
grouped rows. Makes the row standout more, while allowing for an
alternating background color.

For example, something like this:

[image: image.png]

**Comment by lbwexler** [comment]
This was just requested by a client.  Don is working on the project, so I will give him this ticket.
