### ISSUE TITLE
Grid should avoid extra re-render if identical agOptions prop passed

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1257]
We've been updating apps to push agOptions objects out to a shared singleton reference on the component (or similar) to avoid extra grid re-renders triggered by the creation of a new object on each parent render.  

Can we automate this within Grid, short-circuiting the render if agOptions was the only prop that changed and is structurally identical?

**Comment by haynesjm42** [comment]
I believe we already made this change as part of some other grid changes a while back.

https://github.com/exhi/hoist-react/blob/develop/cmp/grid/Grid.js#L144

We are only building the `agOptions` in the constructor of Grid now so we should not be seeing extra re-renders of agGrid if the `agOptions` prop changes in the parent render.

**Comment by amcclain** [comment]
Thanks for pointing this out, John.  And we're sure that this ends up avoiding re-renders - at least of the inner rendered ag-grid?

I'm really not paranoid about this, but I must have missed the memo on this optimization as I've still been recommending to other devs that we extract out any ag-options into a const on the parent component that's outputting a grid child. Will stop doing that and could unwind any cases we come across where that's already done.  

(@lbwexler wanted to ensure this matched your expectation as well.)

**Comment by lbwexler** [comment]
Hi -- my bad -- yes, john and I did this work with an eye toward stabilizing the rendering of agGrid.  It should mean that only the trivial re-render of the <Grid> itself, not the <AgGrid>.

I guess I wanted to test it further before announcing that we should revert all the static agOptions, and then just kind of forgot about it.  Maybe just a lack of confidence in the fix at a time when Alps performance in particular was really under the gun.....

Let's use this ticket to ensure we feel confident in our approach (perhaps by forcing some re-renders in various ways, and seeing that the re-render chain is broken) and then start cleaning up client code as we see it.

**Comment by amcclain** [comment]
I was just playing with our main positions grid in the Portfolio app, on the `treeMapV2` branch:

https://github.com/exhi/toolbox/blob/4062e2e2b5f160cb108f7a1b93d9a4528a5c9812/client-app/src/examples/portfolio/GridPanel.js#L30

If I pass any agOptions to the grid, e.g. `item: grid({model: model.gridModel, agOptions: {foobar: true}})` and then expand a node, I see that node collapse on the next update tick.  Running the React tools profiler shows the grid rendering multiple times.

**Comment by amcclain** [comment]
@haynesjm42 - we would like to resolve this one way or another in the near future, so we're not living with any de-optimization for our grids.  Can you make some time to confirm any issue here in the coming days?

**Comment by haynesjm42** [comment]
Yes will do

**Comment by lbwexler** [comment]
Hi -- I spent a bunch of time looking at this and am pleased to finally close this!

I can confirm that (when specifying an agOptions and other props) we *do not* re-render the underlying agGrid, when the parent is rendered.  We *will* re-render our minimal wrapper,  but the wrapper itself freezes the  props in state so the render does not cascade.  This is critically to avoid losing state like expansion state and exactly what we want to do.

Seperately, we might discuss whether the remaining grid props like `agOptions` and `onReady` should just be moved to the GridModel -- seems like we could just complete this task once and for all!

**Comment by amcclain** [comment]
Excellent - I will finally stop breaking out `agOptions` into consts and resume passing them inline without fear.

**Comment by haynesjm42** [comment]
This is great - thanks Lee!

**Comment by amcclain** [comment]
https://github.com/xh/hoist-react/blob/00b62ee70f820734f9e0118006687fd0963c9fe2/mobile/cmp/navigator/impl/swipe/Swiper.js#L141
