### ISSUE TITLE
Streamline configuring of GridModel context menu actions

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1266]
GridModel currently contains a `contextMenuFn` config which is expected to return a StoreContextMenu. This pre-dates the RecordAction class which should be able to handle all of the dynamic use-cases that would require an app to actually use the `contextMenuFn` callback in a non-trivial way. 

I propose that we remove `contextMenuFn` (breaking change!) in favor of adding a `contextMenuActions` config which GridModel would use to construct its StoreContextMenu (which could/should be renamed). This should cleanup app code around grid context menus and make things consistent with other components/models which use the RecordAction class.

**Comment by lbwexler** [comment]
Fixed in a duplicate ticket
