### ISSUE TITLE
FormField minimal prop poorly named

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1273]
This prop controls the display of validation error messages.  We just reviewed a client form that had its layout shifting due to the non-minimal validation errors. Suggested to the developer that we turn on minimal validation to avoid. 

He was pleased that the option existed and we took it, but understandably pointed out that the prop name did not provide him with much clue as to what it does.

**Comment by amcclain** [comment]
This prop controls the display of validation error messages.  We just reviewed a client form that had its layout shifting due to the non-minimal validation errors. Suggested to the developer that we turn on minimal validation to avoid. 

He was pleased that the option existed and we took it, but understandably pointed out that the prop name did not provide him with much clue as to what it does.

**Comment by lbwexler** [comment]
I would argue that we should leave it at this point. Its a documentation/example code/toolbox  issue at this point.  @amcclain please feel free to close if you agree.

**Comment by amcclain** [comment]
Agreed!
