### ISSUE TITLE
Enable keyboard nav/selection in ag-Grid context menu

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1285]
Client request to allow up-down arrow navigation within the Grid context menu. 

Would need to determine if supported in any way by ag-grid itself. We are currently using their provided context menu. We have also discussed replacing that with the Blueprint menu for general consistency with other components. Could research options for keyboard handling there as well (if any).

Note that `shift + f10` is a built-in Windows shortcut for right-click. For this to be useful, I think we would need to ensure that focus lands on the menu when shown in this way, and the user can immediately go up/down the list with the keys, see focus change, and action an item with `spacebar` or `enter`.

**Comment by lbwexler** [comment]
Colin -- can you look at this?  

If its not practically feasible, would like to close this.

**Comment by cnrudd** [comment]
Taking a look.

**Comment by cnrudd** [comment]
It was pretty trivial to add keyboard nav with Enter = Click to the first level menu.  Getting it onto child menus would be more difficult or require some re-think of approach.   
We could enable only if there are no child menus, which would take care of most use cases I think, or we could not go forward at all.  Worth reviewing.

**Comment by cnrudd** [comment]
After discussion with Lee, we agreed to try find a new npm lib for context menus that already supports child menus and keyboard navigation, and see if we can use that in all hoist components and in AG-Grid.

**Comment by cnrudd** [comment]
The only npm lib I've found that is written for React and supports child menus and keyboard nav is:
https://vkbansal.github.io/react-contextmenu/#/
https://github.com/vkbansal/react-contextmenu

but it has a few issues:

1. needs maintainers
2. left arrow does not trigger walk back up to parent menu
3. Escape key closes top level menus but does not close anything if a sub menu is open.

**Comment by cnrudd** [comment]
Have also entered this feature request with Blueprint: https://github.com/palantir/blueprint/issues/3881

**Comment by cnrudd** [comment]
PR for adding keyboard navigation to AG-Grid context menu:
https://github.com/xh/hoist-react/pull/1470

After looking around quite a bit, I don't see any ready to go context menus in react lib land that have good support for keyboard navigation.

I'm also not sure how easy it would be to replace AG-Grid's own context menu with one of our choosing.

So, I have put together this mixin (in PR above) that adds key-nav to AG-Grid's context menu.

This doesn't get us key-nav for non-grid context menus, but it seems like most requests for this feature are in the context of grids so this takes care of most needs, I think.

For non grid context menus, I think Blueprint has a very good implementation, and we could ask them or contribute to their code key nav support.  If we don't want to do that, we would have to make our own from scratch.

**Comment by lbwexler** [comment]
We have added this neatly analogously to how we handle row navigation with the keyboard.  We should keep our eyes peeled for it in release notes in case ag-Grid ever builds it in to the core
