### ISSUE TITLE
PanelModel should delay loadAsync() calls when collapsed

### ISSUE THREAD

**Issue by inewell** [xh/hoist-react#1310]

**Comment by amcclain** [comment]
Seems like this could be a `PanelRefreshContextModel` similar to https://github.com/exhi/hoist-react/blob/develop/cmp/tab/impl/TabRefreshContextModel.js

**Comment by lbwexler** [comment]
Seems like we just want to add support for refreshMode to PanelModel?   Hoping this will fall right into place!

**Comment by TomTirapani** [comment]
Added support for RefreshMode to PanelModel. Also DRYed up our duplicate RefreshContextModels across the various APIs that use RefreshMode.

See PRs:
https://github.com/xh/hoist-react/pull/1787
https://github.com/xh/toolbox/pull/382
