### ISSUE TITLE
Chart should re-using existing visualization, avoid extra renders

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1314]
In our TreeMap component, we have reworked to minimize re-renders, having the overall component render() the container (or placeholder/error messages) and then having dedicated more targeted reactions to either create/render the Highcharts viz or reload the existing viz with new series data.

This brought some meaningful performance benefits to TreeMap that should apply to Chart as well.

**Comment by peterjcoffman** [comment]
I found something interesting. My current solution for this issue also solves this one:
https://github.com/xh/hoist-react/pull/1455

**Comment by peterjcoffman** [comment]
WIP PR is here:

https://github.com/xh/hoist-react/pull/1505

This seems to get a decent performance improvement when reloading data, maybe a factor of two.

It also changes some behavior, which may not be desirable. As I mentioned, it will cause charts to keep their zoom level when refreshed. It also seems to prevent charts from displaying an animation when refreshing data, like the one at toolbox.xh.io/app/charts/line

**Comment by lbwexler** [comment]
Great Job on this Peter  👍
