### ISSUE TITLE
Improve coloring for SplitTreeMap/TreeMap

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1316]
Some issues to consider:

+ The default coloring scale should be settable by the applications according to domain knowledge of the data.  This will allow colors to be compared meaningfully from data set to data set

+ In any case, split tree map should never use different color ranges for its two sub maps!  The map is conceptually one thing.  The brightest profit should be of an equivalent relative heat as the brightest loss!

+ <s>Consider using gray for nodes that should not have color (e.g. no risk info available).  This will look better than white in both dark and light modes and is more clearly 'disabled' </s>

+ <s> Need a clearer boundary between the two maps, or at least the option for an app to set the width.  In certain degenerate cases it can be difficult to grok the whole notion of the split tree map without that.</s>

**Comment by lbwexler** [comment]
@TomTirapani  -- is there anything in this ticket that we still need to address?

**Comment by TomTirapani** [comment]
I don't think so. I think all of the above has since been addressed

**Comment by lbwexler** [comment]
I actually think the first two are still important issues.  We spread any heat data we get between 0 and 1, _for each individual map_.  I may be misunderstanding this, but I don't think this allows the application to determine a consistent scale for multiple maps.

**Comment by TomTirapani** [comment]
Okay, I'll take another look.

Just to make sure I understand the requirements, for:
1) We want apps to be able to pass min/max values which determine the scale, otherwise we determine the range from the data.
2) The range used for each map is derived from the min / max of both maps. e.g. A wide range of negative values and a narrow range of positive values would render the positive values with a narrower color range.

Is this correct?

**Comment by lbwexler** [comment]
Sorry for the delay.  I think the key is that the app should typically pass the split treemap a single absolute `maxHeat` value that represents the heat value that will have the maximum brightness (positive or negative) within the entire HeatMap.  This allows the coloring to be co-ordinated and consistent, across multiple maps, and multiple loads.  

Right now we use the largest value in the dataset, which makes the coloring always nice and bright in each submap, but does not allow the user to attach any consistent meaning to that brightness.

**Comment by lbwexler** [comment]
FIXED!  Thanks Tom!
