### ISSUE TITLE
Review Hoist Inputs for inline grid editor compatibility

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1319]
Some inputs are more friendly to this than others. In particular dateInput is very tricky with respected to handling keydown events that one might want the input to receive but not the grid or vice versa.  For example, the dateInput's underlying textInput may contain a parseable but as of yet uncommitted value. If you then hit the tab key, the blur that would do the commit does not happen before ag-grid has destroyed the component. However, if you suppress the ag event that causes this and attempt to navigate cells via the grid api you end up with focus problems on your input.

Long story short: inputs that allow commitOnChange are fairly easy to adapt to inline editing, while others are not. Speaking to John Haynes about this, and we suspect the select input in particular may also be tricky.

I have a workaround for my dateInput use case, but we think Hoist can be improved along these lines as the demand for these inline editors appears only be increasing across apps.  Workaround is as follows ('getValue' is ag-grid's hook into retrieving the value of the cell before destroying the editor):

![Screen Shot 2019-08-20 at 2 04 31 PM](https://user-images.githubusercontent.com/15745614/63372105-77bba980-c353-11e9-9f00-285d6fac2379.png)

**Comment by lbwexler** [comment]
Was speaking to Don about this.  Was wondering if we should build our own basic editors into hoist?  Seems like there is a lot of boilerplate to get right here that we could take away from applications?

At the very least they would form a template for applications that wanted to develop more complex editors.

**Comment by amcclain** [comment]
Closing in favor of tracking the entire effort under #883 for now.
