### ISSUE TITLE
ChartModel should expose the underlying highcharts component...

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1326]
...or possibly a set of helpful highcharts API methods.

Original motivation was: I wanted to be able to call methods like setExtremes on charts in a client app in order to respond to a user clicking a range select button. 

Spoke to Lee shortly thereafter regarding the reactive model and how it would be more appropriate to change the state of the highchartsConfig in order to get the chart to render as desired if possible (rather than poking the _hChart).

However, even if that is possible, I need to query the _hChart (getExtremes) to find out if the user has manually zoomed via a drag action so that we can set the new visible range based on that.

At the end of the day, we should at very least be able to use the highcharts api to query the chart for useful info, if not to drive the chart itself. (I think)

**Comment by amcclain** [comment]
@peterjcoffman @febbraiod - did the recent chart work handle this ticket? 

Let's leave aside the idea of switching to some other wrapper and continue to build out the component we already have.  Other than that, can the current Chart/ChartModel classes satisfy the need Don had that caused him to open the ticket?

**Comment by febbraiod** [comment]
Just glancing the current chart code and I think this is still an open ticket. Not sure what kinds of decisions were made regarding exposing this instance. Might open the door to people poking the chart and having it get out of sync with the config we're observing. In any case, if we are going to expose it, I would expect to see a hChart property on ChartModel, which I do not.

**Comment by peterjcoffman** [comment]
We do not currently expose the chart. It is managed internally by the LocalModel of Chart.js.

I don't think it matters much whether or not the actual chart gets out of sync with our config. The only thing we do is remake the chart entirely when the config changes. If it gets out of sync, the only thing that might happen is doing an unnecessary re-render once in a while.

**Comment by febbraiod** [comment]
Right, but my concern is that one pattern is that you grab the Highcharts config, probably clone it, and then change some part of it and re-set it to cause a render with the new config. If we also allow direct manipulation of the chart instance, it might be a development/debugging nightmare when a person can't seem to figure out why the config doesn't match what they are seeing on the screen.

I very well may be overstating the case, but worth considering.

**Comment by peterjcoffman** [comment]
PR:
https://github.com/xh/hoist-react/pull/1583
