### ISSUE TITLE
Classes applied via GridModel.rowClassFn / Column.cellClassFn are additive only

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1331]
As per the [the ag-Grid docs](https://www.ag-grid.com/javascript-grid-row-styles/#refresh-of-styles) row CSS classes applied via `getRowClass()` will only accumulate - updates to the data will not remove previously applied classes.  This is the method we rely on for our `GridModel.rowClassFn`, so our contract is not working as expected.

Same applies for [cellClassFn](https://www.ag-grid.com/javascript-grid-cell-styles/#refresh-of-styles)

**Comment by haynesjm42** [comment]
Taking this over as will need the add/remove control for #2353
