### ISSUE TITLE
Expose inputRef prop on Blueprint input components

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1334]
BP supports an `inputRef` prop that it will pass through to the underlying DOM input - this could be useful to attach to / get a handle on.

**Comment by lbwexler** [comment]
Nice to just get this done and close.  Should be trivial

+ So we are talking about TextInput/TextArea/NumberInput/DateInput. 
+ If Select or JsonInput or mobile controls can implement, they should do so.
+ Don't forget to call out the enhancement in changelog!

**Comment by peterjcoffman** [comment]
We already use an inputRef in dateInput. It passes an inputRef to its child textInput, which is a Hoist textInput.

```                   
 item: textInput({
                        value: this.formatDate(this.renderValue),
                        className: this.getClassName(!enableTextInput && !props.disabled ? 'xh-date-input--picker-only' : null),
                        onCommit: this.onInputCommit,
                        rightElement,

                        disabled: props.disabled || !enableTextInput,
                        leftIcon: props.leftIcon,
                        tabIndex: props.tabIndex,
                        placeholder: props.placeholder,
                        textAlign: props.textAlign,
                        selectOnFocus: props.selectOnFocus,
                        inputRef: this.inputRef,
                        ...layoutProps
                    })
```

**Comment by peterjcoffman** [comment]
Does that actually do anything?

**Comment by lbwexler** [comment]
Discussed with Peter -- that's not currently a supported prop in textInput.  He will fix as part of this ticket.

**Comment by peterjcoffman** [comment]
I'm not sure how to handle DateInput. It passes its own inputRef prop to its child textInput. Should I allow the user to override that?

**Comment by peterjcoffman** [comment]
Same goes for select and jsonInput. Both of them could take an inputRef, but both of them also create their own ref that I think I'd have to replace.

**Comment by peterjcoffman** [comment]
WIP pull request is here:

https://github.com/xh/hoist-react/pull/1479

I do not know of the correct way to handle having multiple refs to the same element. So Lee proposed we just merge the easy changes and leave dateInput, jsonInput, and select until later.

**Comment by lbwexler** [comment]
Its not we even would want to promise supporting this on dateInput/jsonInput and or select.

Closing this -- think we got a nice API enhancement, and also fixed an unrelated bug with DateInput!
