### ISSUE TITLE
Select.enableMulti doesn't work with zero values

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#1341]
Select throws with `Cannot read property 'value' of null` on the following line if you try to use a `0` value with `enableMulti: true`:

https://github.com/exhi/hoist-react/blob/develop/desktop/cmp/input/Select.js#L328

Most likely due to a downstream falsey check

**Comment by amcclain** [comment]
Looking at this a bit now - one thing I just realized is that `_.isEmpty(0) == true` - which surprised me and might be related.  

I see we are using isEmpty in a few places related to option and value processing.  I guess I should have known that zero was treated as empty, but I think I was associating isEmpty with null, undefined, [], and '' - had not considered 0. 

Anyway - not positive this is it, but wanted to note here in case this was news to anyone else.

**Comment by amcclain** [comment]
Hmmmm... was not able to reproduce in Toolbox.  I tool the multi-select example in InputsPanel where we provide an array of states and tried:

* replacing `options: usStates` with `options: [99, 0,' whatever']` and selecting 0
* replacing it with `enableCreate: true` (i.e. no options) and entering 0 as an on-demand value
* replacing the value of one of the states in the source data with 0

**Comment by amcclain** [comment]
Any which way - as per above I think there are a number of isEmpty() calls that need to be replaced by something like isNil || is empty array.  Will require some careful looking....

**Comment by TomTirapani** [comment]
I was specifically seeing it when calling `formModel.init({field: [0, 0.5, 1]})`.

It didn't go too deep into the investigation, but figured it was due to the zero as it resolved when I used string values.

**Comment by lbwexler** [comment]
Would be great to close out a ticket that is a clear bug, and sounds like a gotcha that we understand fairly well.  Tom -- do you have some time to take a look?

**Comment by TomTirapani** [comment]
Taking a look at this shortly...

**Comment by TomTirapani** [comment]
On closer inspection, it seems the root cause seems `createIfNotFound` being false due to incorrect `isEmpty()` checks.

Fun fact: `isEmpty()` returns true for *any* numerical value, not just zeros. Replacing the `isEmpty()` checks in `toInternal()` with `isNil()` seems to be more like what we are looking for and resolves the issue.

The last `isEmpty()` check can remain, but only applies in multi mode.

PR: https://github.com/xh/hoist-react/pull/1364

**Comment by lbwexler** [comment]
Thanks for this tom.

For this record, I reported that isEmpty() is dangerous and confusing for just that reason on slack about a year ago.  Somehow everybody convinced me that we would never use it on primitives and I should stop worrying....  :-)
