### ISSUE TITLE
NumberInput will exhibit loopy behavior when tab and click at same time

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1358]
Reported by a client.

This looks like the same issue that we encountered here:

https://github.com/exhi/hoist-react/commit/73e36e97cb7246ce68af66164bdb7eefa7b5b40e#diff-d997ba58bd3457276aca8f13fcf898e8

Can we fix this, and also audit all of our HoistInputs and make sure we are not vulnerable to this elsewhere?

**Comment by cnrudd** [comment]
taking a look now.

**Comment by cnrudd** [comment]
Not able to reproduce yet on any number field in toolbox.

**Comment by lbwexler** [comment]
Also having a little trouble reproducing on client app.

**Comment by lbwexler** [comment]
Cannot reproduce.  Was extremely subtle and rare as shown by client, and on a pre v28 version of hoist..  We can re-open if needed.
