### ISSUE TITLE
RefreshButton and Mask:  Deprecate 'model' in favor of a more appropriate prop name

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1359]
Could introduce new names 'target' for RefreshButton and 'pendingTask' for Mask. 

We would probably just deprecate "model".  Think we want to generally reserve the prop name 'model' for the specific case where we consider the model to be the "model" of the component, not a model it needs to reference....

Not critical.

**Comment by amcclain** [comment]
Agree - I like `target` for RefreshButton for sure.  

Another option for the mask could be `bind` - that seems very natural to me considered on its own, but maybe too confusing to have it be bound to a model vs. the string field name we are used to from the inputs. 

Also perfectly OK with `pendingTask`. We expect direct usages of mask to be relatively rare (vs. panel built-in).

**Comment by lbwexler** [comment]
MenuButton could also take a target which would be the MenuModel

**Comment by amcclain** [comment]
Closing as not a priority / not worth the API drift.
