### ISSUE TITLE
Cannot register ag-grid framework components

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1370]
There is an agOption called 'frameworkComponents' with which you can register components with the grid. Inline editor components for example. After upgrading to Hoist 28 SNAPSHOT, the grid is not finding these components when needed.

**Comment by lbwexler** [comment]
Don is looking into whether there might be a more general problem here.  No longer clear that this is related to frameworkComponents.   

Would be great to see if we could reproduce this in toolbox.  Might be the first step to having a much needed inline-editor example.

**Comment by febbraiod** [comment]
There was a small suspicion that agOptions in general were not being set/respected in app where we saw this issue. However, other options in that block are working. Focus should go back to frameworkComponents and inline editors.

Will try to repro in toolbox as Lee suggests

**Comment by febbraiod** [comment]
Closing. This is not a bug in Hoist 28, but rather an in-app bug caused by a hard to catch typo made by a dev with tired eyes and an injured finger doing the Hoist 28 upgrade.
