### ISSUE TITLE
Need Record Method to more easily do client-side update.

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1376]
As far as I can tell, you actually have to write the following code to update a record appropriately on the client:

rec.store.updateData(update:[{id: rec.id, ...rec.raw, fooField: 'newValue'}]);

yikes!

This relates to 
https://github.com/xh/hoist-react/issues/1321

**Comment by haynesjm42** [comment]
A few questions on what we are really looking for here:

1. Records are immutable, so it probably would be misleading to have a method on Record itself which would not actually update that instance of the Record, the Record instance you just updated will no longer be in the Store after that update call returns. Probably looking for something like `updateRecordData` on Store?
2. Store data updates do not currently support being provided with partial Record data (unless I an misreading the code), which seems like what we would want here for the use-case of updating just a single field in the Record. Any reason why we don't support partial data updates via Store.updateData?

Seems like a common use-case for this would be inline grid editing, where you would want to write something like this in an ag-grid valueSetter callback `store.updateRecordData(record.id, {mktVal: 1000000})` which would just be a convenience method for building the full StoreUpdate for the call to Store.updateData

**Comment by lbwexler** [comment]
agree with much of the above.  Sorry for muddying the waters.   Think the main point now is what is the right name for the store method.  could also be updateFields().

Also, record argument could be the record, or its id, if we wanted to be really friendly.

**Comment by lbwexler** [comment]
Subsumed in the following:

Store enhancements for partial loading and client-side editing support #1495
