### ISSUE TITLE
Tree column should pass any renderer through to the innerRenderer

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1390]
Currently the only way to use a custom renderer on a tree column is to use `agOptions` to set the `cellRendererParams` for the `agGroupCellRenderer` and then set the `innerRenderer` or `innerRendererFramework` property, using the ag-Grid interface for renderers instead of the Hoist Column renderer interface. 

Don't see any reason why we can't/shouldn't pass the renderer through to that `innerRenderer` for tree columns, would clean up the Toolbox SampleTreeGridModel impl (and some client apps)

**Comment by amcclain** [comment]
This would be useful for an app @febbraiod is working on as well.  There we had a particular use case of grouping by a LocalDate field in a tree grid. We wanted to show the groups with a format different from the YYYYMMDD default, but there was no easy way to do so.

Would be happy to review any proposals if you have a chance to work on it, or give a shout anytime if that does not look likely and will see if we can make some progress.

**Comment by haynesjm42** [comment]
Already have a PR up, but looks like I forgot to link back to this ticket

**Comment by lbwexler** [comment]
@febbraiod  -- can you confirm that this change works for your use case?

**Comment by febbraiod** [comment]
Lets hold off. Want to talk to John.

**Comment by febbraiod** [comment]
OK there were a couple hurtles to getting this to work for me, none of which actually pertained to John's code. Apologies John!

One issue that might be worth discussing is that, at least with cubeLabel columns, the value passed to the renderer appears to always be a string. In my use case we intended to check isLocalDate(v), but that was never the case even when passing the cube a LocalDate as a value on a field. Not sure where along the line this conversion to string is happening yet.

I am, however, able to achieve my desired result with this renderer in a sort of not-so-clean way by attaching the LocalDate value to an additional field and then comparing in the renderer:

renderer: (v, {record}) => return v == record.localDateField.toString() ? myDesiredValue : v)

**Comment by lbwexler** [comment]
Merged and Closing.  Thanks for Verifying Don.  We'll consider the issue mention as we adjust the Cube api going forward.
