### ISSUE TITLE
Date Input should either use moment in strict mode or offer an option to do so

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1396]
Client use case where a forgivingly parsed input could lead to unintentional real world consequence. 2019-10 should NOT yield Oct 1, 2019, but rather null so as to invalidate the input.

Additionally consider not forcing an out-of-bounds value to an in-bounds one. IE if the input receives a date below the minDate that doesn't not mean forcing it to the minDate is an acceptable value.

**Comment by amcclain** [comment]
A few decisions to make here and then we can tackle this ticket / split it up:

1. Current dateInput will coerce value to fit within min/maxDate range by setting it to one of those extremes if out of bounds.  Do we ever want this behavior?  If no, should it force the value to null? Should it leave it alone?
2. Current dateInput uses moment in `parseDate` in its default "loose" mode which will make a best effort to parse text input.  This should likely be controllable via a prop - need to confirm and decide on a default.
3. Should both behaviors be controlled via some kind of proposed "strictMode" prop or are they distinct?  A non-issue if #1 above is not something we expose to customize.

**Comment by lbwexler** [comment]
1) I vote for forcing it to null.  I strongly vote *against* changing it to min/max date, which seems arbitrary to me.  We have already been tripped up by just that behavior, and it seems like it risks corrupting business data in ways that we would never want.
2) Like the idea of a strictMode prop that jus trampolines to the same on moment.  Guess we will want to default to false for backward compatibility and usability
