### ISSUE TITLE
Support for Cube data updates

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1399]
Need Cube to be able to handle updates for a client application. Currently it only supports full data loads. 

As part of this we should probably also add support for Cube Views, or something similar where a store can be automatically updated after the Cube receives updated data.

**Comment by lbwexler** [comment]
Thinking about this some more.  I think we should aim to simplify things from the hoist-sencha version, namely

When a bundle of records in the cube changes, determine if the record are contained *at all* in the View.  If they are, have the view recompute itself completely, firing an event to indicate that records.

Given the actual client usages, it's not clear that the cube requires or benefits from  the tremendous complexity of recomputing only the affected aggregates for each change.

**Comment by lbwexler** [comment]
This is underway now
