### ISSUE TITLE
Model context incorrectly set on certain types of Panels

### ISSUE THREAD

**Issue by mpeckerman** [xh/hoist-react#1421]
1. Navigate to Toolbox -> 
2. Select Grids tab ->
3. Select  Standard (Tree, Tree w/CheckBox, Grouped Columns) subtab ->
4. Select a "Display Option" ->
ERROR: Exception.js:119 
Uncaught Exception: Required function 'setShowCellFocus()' not found on bound model at Function.createInternal

**Comment by mpeckerman** [comment]
Uncaught Exception error generated when tested: 
Toolbox -> Forms -> FormModel -> Display Options: Inline Labels / Minimal Validation Display / Commit On Change

**Comment by lbwexler** [comment]
I will fix this today
