### ISSUE TITLE
ModelSpec createFn should be passed component props

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1422]
@febbraiod ran into a use-case where he wanted to pass a different service to his model constructor based on a prop passed to the component, but there was currently no way to accomplish this (that we could find) using the `creates` spec.

We didn't see any reason why we shouldn't be passing the props to the create function, seems like a fairly common use-case where you'd want to pass those props through to your model ctor. Is there a different pattern that should be used in this case? (`useLocalModel` not applicable because it is desired to put this component's model on the model context)

**Comment by lbwexler** [comment]
Will take a look tomorrow.  Sounds like a good idea.

**Comment by febbraiod** [comment]
Thanks guys
