### ISSUE TITLE
Tree grid does not retain expand state upon re-mount

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#1434]
Steps to replicate
1. Create tree grid and expand all rows.
2. Close or hide grid.
3. Open or rerender grid with the same gridModel.
4. Note that the expansion state of the tree is always collapsed after render. The grid does retain other state such as the sort and column state.

**Comment by pauldelano** [comment]
This can be seen in the hideTreeGrid branch of Toolbox. Navigate to Grids/Tree and use the Hide switch to hide and show the grid.

**Comment by lbwexler** [comment]
reworked this ticket to remove the confusing use of "render" when "mount" is actually meant. 

This is not a surprise, and the example branch not needed --  GridModel makes no attempt to store node expansion state!

**Comment by amcclain** [comment]
Closing this as covered by #1844
