### ISSUE TITLE
RelativeTimestamp improvements

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1441]
Two proposed improvements for RelativeTimestamp - the component and its public backing function:

1. Accept a param/prop for `referenceTimestamp` - default `Date.now()` but could be given another static timestamp to compute and display the relative diff between two explicit dates.
2. Use `moment.from()` utility function to generate relative string. This can replace bespoke internal logic and is presumably a better / more robust implementation. @pauldelano also observed that the current impl and moment use different rounding rules, outputting different results for certain diffs.

**Comment by pauldelano** [comment]
On #1 - Do we need 2 props for the now timestamp? One for a static value and other with a bind variable?

**Comment by lbwexler** [comment]
I am not sure about the value of making the change to use lodash, unless we have known bugs/issues. Using lodash would be a breaking change, as it would not the various options that we provide on (e.g. `suffix/prefix/epsilon/short` etc.)

**Comment by lbwexler** [comment]
Also, note that we describe the current "timestamp" property as the "reference time" in the documentation, so will very easy to get confused as to which is which when we allow specifying two times.  We should just be sure to clean up the documentation and be consistent and clear with whatever we do.

**Comment by peterjcoffman** [comment]
If two times are specified, it will not be necessary to periodically refresh the display. So we can turn off the timer in that situation.

**Comment by peterjcoffman** [comment]
I'm not sure how to handle the API change on getRelativeTimestamp. I don't see a good way to add a second timestamp parameter, other than putting it in the options parameter (where I don't think it logically belongs).

**Comment by lbwexler** [comment]
I think it does logically belong as an option.  Its not required, and
frequently won't be set, and secondary to the main timestamp argument.

-Lee

**Comment by amcclain** [comment]
> I am not sure about the value of making the change to use lodash, unless we have known bugs/issues. Using lodash would be a breaking change, as it would not the various options that we provide on (e.g. `suffix/prefix/epsilon/short` etc.)

I don't feel strongly about swapping to moment (note [this is the method I was looking at](https://momentjs.com/docs/#/displaying/from/), but I think the only option we would be unable to easily support would be the `short` flag. The `from()` util takes a second argument that removes the default "in/ago" text around the time units, which would allow us to surround them again with our suffix configs. Likewise the `nowEpsilon` could continue to be evaluated early and `nowString` returned if within that limit.  The minor code cleanup within this file was appealing, but the consistency with moment as our reference date formatting library was even more so.

Re. the second timestamp concept - what about using `relativeTo` as the name and supporting:
* Special string `'now'` for current behavior
* Date
* Epoch ms timestamp

I agree re. exposing this config in options - maintains the function's current API and properly reflects its status as an advanced/infrequent parameter.  Thanks!

**Comment by lbwexler** [comment]
Ah yes -- I had looked at the moment method -- just a sloppy comment.  
But alas did not look closely enough at the method -- if we think that `short` is the only piece that would be lost, that might change the calculus, although definitely are using `short` in client apps IIRC.

**Comment by peterjcoffman** [comment]
I have compared the behavior of Moment, our current version, and our current version with 'short' enabled.


  | moment | current (long) | current (short) | desired
-- | -- | -- | -- | --
0 seconds | a few seconds | <1 minute | <1 min | ???
10 seconds | a few seconds | <1 minute | <1 min | ???
20 seconds | a few seconds | <1 minute | <1 min | <1 minute
30 seconds | a few seconds | <1 minute | <1 min | <1 minute
40 seconds | a few seconds | <1 minute | <1 min | <1 minute
50 seconds | a minute | <1 minute | <1 min | <1 minute
1 minutes | a minute | 1 minute | 1 min |  
10 minutes | 10 minutes | 10 minutes | 9 mins |  
20 minutes | 20 minutes | 20 minutes | 20 mins |  
30 minutes | 30 minutes | 30 minutes | 30 mins |  
40 minutes | 40 minutes | 40 minutes | 40 mins |  
50 minutes | an hour | 50 minutes | 50 mins |  
1 hours | an hour | about an hour | ~1 hour |  
5 hours | 5 hours | about 5 hours | ~5 hours |  
10 hours | 10 hours | about 10 hours | ~10 hours |  
15 hours | 15 hours | about 15 hours | ~14 hours |  
20 hours | 20 hours | about 20 hours | ~20 hours |  
1 days | a day | a day | a day |  
2 days | 2 days | 2 days | 2 days |  
5 days | 5 days | 5 days | 5 days |  
10 days | 10 days | 10 days | 10 days |  
20 days | 20 days | 20 days | 19 days |  
1 months | a month | about a month | a month |  
2 months | 2 months | 2 months | 2 months |  
4 months | 4 months | 4 months | 4 months |  
6 months | 6 months | 6 months | 6 months |  
8 months | 8 months | 8 months | 8 months |  
10 months | 10 months | 10 months | 10 months |  
1 years | a year | about a year | a year |  
2 years | 2 years | 2 years | 2 years |  
5 years | 5 years | 5 years | 5 years |  
10 years | 10 years | 10 years | 10 years |  
25 years | 25 years | 25 years | 25 years |  
100 years | 100 years | 100 years | 100 years |

**Comment by lbwexler** [comment]
Thanks for this Peter -- Extremely Helpful.

1) It occurs to me that if we wanted to continue to support 'short' we could merely implement it by post-processing whatever string moment produces to abbreviate 'minutes' -> 'mins' and 'seconds' -> 'secs'.  

2) Think we could overwrite the moment string for 10 < x < 50 secs to "<1 minute" (or "<1 min" for short).

That's it!

**Comment by peterjcoffman** [comment]
@lbwexler 

I did those two things.
