### ISSUE TITLE
Grids -> Excel Alerts "with content" on opening an exported file (Mac)

### ISSUE THREAD

**Issue by mpeckerman** [xh/hoist-react#1446]
1. Navigate to Toolbox -> Grids -> Standard
2. Click 'Export' icon
3. Open file
4. Excel Alert(s) on opening"Hoist-sample-export' file

![Screen Shot 2019-11-12 at 1 58 20 PM (2)](https://user-images.githubusercontent.com/40367298/68702702-43711700-0557-11ea-89dd-bbe28d40ea95.png)
![Screen Shot 2019-11-12 at 1 45 38 PM (2)](https://user-images.githubusercontent.com/40367298/68702713-48ce6180-0557-11ea-8714-98a989919fae.png)
![Screen Shot 2019-11-12 at 1 45 08 PM (2)](https://user-images.githubusercontent.com/40367298/68702735-4d931580-0557-11ea-9ff2-80c6cc32690a.png)

**Comment by mpeckerman** [comment]
![Screen Shot 2019-11-12 at 1 42 01 PM (2)](https://user-images.githubusercontent.com/40367298/68703550-e8d8ba80-0558-11ea-86ac-7870ea083605.png)

**Comment by mpeckerman** [comment]
Re-Opened: Closed in error

**Comment by lbwexler** [comment]
Hi Peter- First step here is to work with Malvina to reproduce

**Comment by peterjcoffman** [comment]
Seems fixed by this:

 https://github.com/xh/hoist-react/compare/dynamicHeaderExport?expand=1
