### ISSUE TITLE
Support for valueGetter on Column

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1453]
ag-Grid columns support a `valueGetter` config - a function that will extract a value if providing a simple string field is not sufficient.

I have a use-case where this functionality would be useful to extract some data from nested collections in a somewhat dynamic manner, where flattening out this data on the record is not especially elegant. Our `Column.agOptions` provides an escape hatch I can use, but this doesn't work with grid export, which is a critical feature. 

I have also observed the use of `agOptions` in the wild on Hoist columns to set valueGetters, presumably for similar reasons.

We should consider supporting valueGetter as a first-class config on Column and ensuring we carry that support through the rest of the integration. We could normalize to always define a valueGetter, even if it's simply `return record[field]` to reduce complexity.  (This might be exactly what ag-Grid does anyway, and we're already in the business of setting a custom valueGetter for tree column.)

**Comment by haynesjm42** [comment]
Fixed by #1509
