### ISSUE TITLE
Grid.dataReaction keys off of private store._filtered

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1454]
I would like to avoid accessing private `_Foo` members from outside the class, as we want that underscore to be a strong signal that the property is not part of the class's public API. Believe this is worth maintaining even across Hoist classes, such as Grid's use of `Store._filtered` as an input to its (super-important) data reaction:

https://github.com/xh/hoist-react/blob/8d465c13cc43ca2ee01f241beffa599fa06bc40f/cmp/grid/Grid.js#L357

(Could imagine exceptions for very closely related classes such as those in the same impl package, but I think these are distinct enough.)

**Comment by lbwexler** [comment]
Yes, agree with the ticket, and this is something we thought about.  The motivation here is that we are trying to avoid publicizing the internal RecordSet class as a public API,  yet we want to continue to use it (and especially its internal map representation) in our own Grid for performance reasons.

Not sure this is the worst API crime in the world -- perhaps we can go ahead and expose RecordSet *after* the Hoist V29 immutable record changes we are looking to do.

**Comment by lbwexler** [comment]
Subsumed in the following:

Store enhancements for partial loading and client-side editing support #1495
