### ISSUE TITLE
Store should have a public method to trigger a refilter

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1467]
Currently if we want a store to be refiltered we would either need to 'setFilter' or 'noteDataUpdated'. There is also a 'rebuildFiltered' method but it is marked as private.

The the problem is one of semantics but probably worth the change. In a client app we have a filter function that does not need to change but a property on a model that is used to do the filter is user settable. We don't want to 'setFilter' over and over with the very same function. We don't really want to call noteDataUpdated because, it hasn't. And we don't want to call a private function.

**Comment by haynesjm42** [comment]
Seems like we should be able to automatically update the filtered record set via a mobx autorun, that would probably handle the majority of use-cases here with custom filtering controls (though we should also just make `rebuildFiltered` public - don't see any reason for it to be private)

**Comment by lbwexler** [comment]
John -- lets go ahead and take care of this one in this release.  I think publicizing the method makes sense.  Perhaps a rename is in order -- `applyFilter()`'? `refreshFilter()` `runFilter()` ?

Running the filter in an autorun in an interesting idea as well.  Just thinking about the best mechanics for doing that.....

**Comment by haynesjm42** [comment]
Fixed by #1509
