### ISSUE TITLE
GridModel.js warning when selecting "DockContainer" 

### ISSUE THREAD

**Issue by mpeckerman** [xh/hoist-react#1483]
1. Navigate to Toolbox -> Containers
2. Click "DockContainer" subtab
3. Warning
Called GridModel.js:267 selectFirst before the grid was ready!

**Comment by peterjcoffman** [comment]
This occurs because the agGrid is only initialized when it is rendered, but we load data into it (and call selectFirst) before it is rendered.

**Comment by peterjcoffman** [comment]
And I caused it!

https://github.com/xh/toolbox/issues/240

**Comment by peterjcoffman** [comment]
I added a check so that the SampleGridModel will only try to select the first row if the grid is ready, i.e. rendered.
