### ISSUE TITLE
Grid export options not well documented

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1491]
It doesn't look like we have a `@typedef` doc for the grid export options, they only appear to be documented in the GridExportService class constructor, not very easy to find if you don't know where to look.

**Comment by lbwexler** [comment]
Peter -- Can you take a look at this?

**Comment by peterjcoffman** [comment]
@haynesjm42 
It looks like the options live on GridExportService.exportAsync, not the constructor. Is that correct?

**Comment by haynesjm42** [comment]
Yes that is correct, they are on `exportAsync` - not sure what I was looking at when I wrote the ticket :)

**Comment by peterjcoffman** [comment]
PR: https://github.com/xh/hoist-react/compare/gridExportDocs?expand=1
