### ISSUE TITLE
Router state should be an observable ref instead of observable object

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1494]
Our `currentState` in the RouterModel is currently marked as `@observable` instead of `@observable.ref`, which can cause some strange issues/errors when putting arrays in state params due to how mobx sets up the proxies for deeply observable objects. I can't see any reason why we would want the router state to be an observable object, it is not something that an app would ever modify directly - we might consider locking it down even more with an internal prop and getter.

Also worth considering whether we should be cloning the state when we update it from router5.

**Comment by lbwexler** [comment]
Great catch, John -- I went ahead and fixed this.

Regarding cloning -- that seems like it could be a little riskier, in case any applications were using object equality here.   Think its should be pretty obvious that apps that are crazy enough to modify a property with the name `routerState` are doing so at their own risk.
