### ISSUE TITLE
Cleanup button-related CSS vars

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1506]
We have several minor bits of messiness currently re. button CSS vars I would like to clean-up:

* Use `--xh-button` prefix consistently, not `--xh-btn`.
* Use `-bg` and `-text-color` consistently, as we do with other themed components.
* Add distinct color vars for active (pressed) button text/bg colors
* Review usages of these vars, especially in mobile, to ensure we're applying the renamed values correctly.
* Alpha sort / consolidate sections in `vars.scss` appropriately to make these easier to locate (there are multiple comment block headers for buttons)

**Comment by peterjcoffman** [comment]
WIP PR is here:

https://github.com/xh/hoist-react/pull/1568
