### ISSUE TITLE
Column tooltip config no longer working

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1507]
I believe we might have had a regression re. `Column.tooltip`

**Comment by haynesjm42** [comment]
Thanks for catching, I had left a change in to set the `tooltipField` on the ag-Grid column def while experimenting with the tooltips, but that takes precedence over the `tooltip` config, so was causing ag-Grid to ignore the `tooltipValueGetter` we were setting

**Comment by amcclain** [comment]
Great thanks for the quick fix - and happy new year! 🎉
