### ISSUE TITLE
Allow gridModel.emptyText to be set dynamically

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1508]
It can be useful to customize / update the empty text message displayed by Grid beyond the initial configuration of the GridModel. Currently `GridModel.emptyText` is provided in the ctor only and is treated as immutable.

**Comment by lbwexler** [comment]
IIRC the problem here is that the underlying agGrid does not provide a way to change the emptyText dynamically without remounting a new version of the Grid

**Comment by lbwexler** [comment]
Peter -- perhaps you could just verify that this is the case -- assuming it is, I don't think we have any great options

**Comment by amcclain** [comment]
Not to stress out about this feature overly much, but it takes a [custom overlay component](https://www.ag-grid.com/javascript-grid-overlay-component/) to render the emptyText. 

Could we always provide the grid with a custom component that gets its inner text from the model, and would internally re-render as needed?

**Comment by peterjcoffman** [comment]
I was looking into the custom overlay components, and there seems to be some inconsistency in the ag-grid docs.

[This page says the component is called `noRowsOverlayRenderer`.](https://www.ag-grid.com/javascript-grid-components/)

[This page says it's `noRowsOverlayComponent`.](https://www.ag-grid.com/javascript-grid-overlay-component/)

I believe the correct name is `noRowsOverlayComponent`.

**Comment by peterjcoffman** [comment]
PR is here:
https://github.com/xh/hoist-react/pull/1519

**Comment by lbwexler** [comment]
👍
