### ISSUE TITLE
Golden Layout integration

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1515]
We have identified [GoldenLayout](https://golden-layout.com/) as very promising layout system for building dynamic, user customized dashboards and similar multi-pane layouts. 

We would like to bring this in as a dependency to hoist-react and explore options for a new Hoist component to provide a managed/curated API on top of its core functionality, very similar to how we do for all other reasonably complex library components.

As a very general initial sequencing - entirely open to discussion/debate - I would suggest the following steps in relative priority order:

1. Select a name for a Hoist component and model to encapsulate the functionality we need and add a very basic initial integration to test.
2. Basic theming to ensure the component styles meld well with our existing look/feel and theme approach. Does not need to be elaborate but some customization off the default will likely help make it clear that this will be a well-integrated Hoist comp.
3. Tackle the persistence API exposed by the library and discuss how we want to serialize/manage this state in the context of the general use-case and more specific dashboard use-cases.  This is a big topic and will clearly need a number of sub-steps.
4. Research/explore options for pop-out windows managed by this library. We might or might not want to handle this here.

**Comment by lbwexler** [comment]
Closing this as we just merged tom's fantastic work here.

 https://github.com/xh/hoist-react/pull/1540

We will continue to tweak this Alpha api and can open new tickets as needed.
