### ISSUE TITLE
Grid component row/cell clicked callbacks

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1517]
The Grid component currently has some props for adding callbacks for various row and cell clicked events. These only serve as pass-through props for the actual ag-grid component, so they could just be set via `agOptions`. I was thrown off initially by the fact that the app callback is just passed the ag-grid params for these, as it is inconsistent with most other grid/column callbacks.

I would expect at a minimum that we parse the ag-grid callback params like we do for the Column callbacks, and pass more useful params to the callback. We usually try to avoid bubbling the raw ag-grid callback params up to applications when they are using props or configs on our components and classes.

What might be even more useful for handling row/record click events is supporting some new configs on GridModel and making use of RecordActions. This would allow apps or higher-level components to use the same actions they have declared for other contexts for these click handlers. RestGrid would be cleaned up by being able to use the `editAction` for the double-click handler, instead of duplicating code to open the form for edit. The only weird aspect of this would be that RecordAction has many props for how it is displayed, and these click handlers would have no representation in the UI. We would probably want to still process the `displayFn` and no trigger the action if the action would be disabled or hidden for the context, etc. Also if we want to try this we could/should support just providing a function and building a basic RecordAction config from it.

**Comment by amcclain** [comment]
👍  for a short-term project to move the callbacks to GridModel and normalize their params in line with our other function calls.

Could revisit any further integrations with RecordAction, etc. in follow-on tickets.
