### ISSUE TITLE
Handle overflow in toolbars

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1524]
Our toolbars currently just hide any overflow, so toolbar items become completely inaccessible. 

Scrollbars don't really make sense in a toolbar, so I think we should instead move the invisible items into a drop-down menu. BlueprintJs provides this component, which seems like it would provide the exact kind of functionality we would want here: https://blueprintjs.com/docs/#core/components/overflow-list

**Comment by amcclain** [comment]
👍 agreed this has been a long-outstanding gap. ExtJS had a similar approach where overflow items would trigger a little V menu button.

**Comment by lbwexler** [comment]
That overflow list looks pretty awesome -- can we just use that?

**Comment by TomTirapani** [comment]
Finally got round to wrapping up the branch I started on this last week:
https://github.com/xh/hoist-react/pull/1719
https://github.com/xh/toolbox/pull/369
