### ISSUE TITLE
Select input should support option groups

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1525]
React Select is designed to allow for options to be [displayed in groups](https://react-select.com/home), however we are a bit strict about how we present options to our input and it appears we disallow this feature.

Shape for groupOptions in example on home page is [here](https://github.com/JedWatson/react-select/blob/8fa6c0f01416b923d2c7a6f31ee687b6248fcd71/docs/data.js#L109)

**Comment by febbraiod** [comment]
Note: This is a feature that is currently used in the Sencha implementation of a client app that we are updated to the new toolkit. So this is a real world desire for this driving the ticket.

**Comment by peterjcoffman** [comment]
PR is here:
https://github.com/xh/hoist-react/pull/1529

**Comment by lbwexler** [comment]
👍
