### ISSUE TITLE
Remove GridModel.experimental.useTransactions

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1541]
We still have three "experimental" flags supported and defaulted in GridModel related to strategies for updating data.  Only one of these - `useTransactions` - is defaulted to true, meaning you would need to flip the experimental flag to false to get a custom behavior and _not_ use transactions..

https://github.com/xh/hoist-react/blob/6191027b5ed57e08056b18ea2ad2285d85eb32c0/cmp/grid/GridModel.js#L232

I propose we remove at least this flag and always use transactions. (Are we aware of any apps that are setting this to false to disable transactions?). This gives us at least an incremental cleanup.

While we are here, we could also check in on the current state of `useDeltaSort` with the latest ag-grid. This was a major (for very large datasets) performance improvement they had undocumented and apparently incubating in their codebase.

**Comment by lbwexler** [comment]
So it looks like there may be a use-case in a client app where ag-Grid is able to maintain a natural sort order when we turn this off.   Colin can shed some light on this.  

But the value of having external sorting preserved also might become more important now that we 
have the need to presort data externally before presenting the grid.

Finally, if we can be guaranteed that the performance was up to snuff, the best case would be if we could remove our own transaction generating code, and simplify things on 

For all these reasons, let's keep the flexibility to easily toggle this for now.  I added some documentation
