### ISSUE TITLE
TextArea not respecting "fill" prop

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1543]
TextArea has a `fill` prop that is documented as causing the input to soak up the full width of its container:

https://github.com/xh/hoist-react/blob/3f4d560d865d006514e1a51449ee7335cb4b89f2/desktop/cmp/input/TextArea.js#L33

But then we default width to 300px, which overrides fill and appears to make it pointless:

https://github.com/xh/hoist-react/blob/3f4d560d865d006514e1a51449ee7335cb4b89f2/desktop/cmp/input/TextArea.js#L78

The developer must also specify `width: null` to get the input to flex width-wise.

I find `fill` to be kind of a weird prop - it came over from Blueprint I think - so I am not sure if we should continue to support it.  But if we do we should ensure that `fill:true -> width:null` or equivalent.

**Comment by lbwexler** [comment]
@TomTirapani Just found this one. 

Can we close this one or do we need to address it?  Notice that on NumberInput, TextArea, and Select, we have a hard-coded default width.  Will this override a flex setting?    Should we be basing the default on whether their is also a flex setting?

**Comment by TomTirapani** [comment]
Following merging https://github.com/xh/hoist-react/pull/3296 TextArea behaves the same as our other inputs, so I think we can close this one out.

I opened a new ticket addressing the width / flex behaviour across inputs generally, which I think we want to be consistent about one way or the other: https://github.com/xh/hoist-react/issues/3300
