### ISSUE TITLE
Tree grid rows not aligned for sibling rows with/without children

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1546]
A tree grid with "mixed" sibling rows - where some have children / are expandable and others do / are not - ends up with misaligned rows.

Verify / consider how to add a natural example in Toolbox to track this.

Review these classes - I think they are outdated, believe the current classes are `ag-group-expanded` / `ag-group-contracted` - but must verify:

https://github.com/xh/hoist-react/blob/7b125368134a836dea53e97a3e86a7c988465f49/cmp/ag-grid/AgGrid.scss#L217

**Comment by peterjcoffman** [comment]
The new classes are `ag-group-expanded` and `ag-group-contracted`.

**Comment by peterjcoffman** [comment]
I changed to the correct class names and also set the expand and contract icons to be a constant width.

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/48924151/72807758-1495b200-3c26-11ea-9491-8551286aae2d.png">

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/48924151/72807774-1eb7b080-3c26-11ea-998e-93e265f205c6.png">

https://github.com/xh/hoist-react/pull/1567

**Comment by peterjcoffman** [comment]
Here is what it looked like before:

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/48924151/72808100-cfbe4b00-3c26-11ea-9569-b71e3a9c703b.png">

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/48924151/72808116-d947b300-3c26-11ea-88fb-710e32275e06.png">
