### ISSUE TITLE
Tree grid indenting should be controllable via CSS var

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1547]
We use a SASS variable and this little routine to generate indents for multiple tree levels. We don't have any good story currently around setting/overriding this variable, however, so an app ends up without a way to customize the indent level used:

https://github.com/xh/hoist-react/blob/7b125368134a836dea53e97a3e86a7c988465f49/cmp/grid/Grid.scss#L98

I think this should be a CSS var.  We won't be able to do this little SASS loop. but we should be able to add in a reasonable number of levels (10 would be plenty I think - not 50) and use a CSS var calc to multiple a base var by the indent level.  That should allow an app to set a var like any other to control the indent.

**Comment by peterjcoffman** [comment]
This was fixed fixed in https://github.com/xh/hoist-react/pull/1567/files
