### ISSUE TITLE
Tree grids should support a tree column not bound to a particular field

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1548]
Some datasets don't have a natural primary / label field to use as a tree column, but still have parent/children relationships and are naturally shown in a tree grid.

You might attempt to specify a column to show the arrows (and only the arrows) such as:

 `{field: 'noSuchField', headerName: '', isTreeColumn: true, width: 40}` 

But ag-Grid weirdly will not render the expand/collapse arrows. I experimented with then adding a `noSuchField` property to my data (set to empty string) and it _did_ work, but this was a weird workaround.

**Comment by peterjcoffman** [comment]
I believe this is caused by our `valueGetter` returning null if there is no field defined or if the field defined does not exist in the record.

I am not sure why that would cause this problem, but I do know that returning an empty string rather than `null` seems to fix it.
