### ISSUE TITLE
Add Auto-Size Columns to default Grid context menu

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1550]
Not sure when you _wouldn't_ want an auto-size option, seems like it makes sense as a default context menu item.

We can/should setup a RecordAction for it with an icon to be consistent with our other items, the default ag-grid `autoSizeAll` built-in option has no icon.

See https://www.ag-grid.com/javascript-grid-resizing/#auto-size-columns for the ag-Grid column api method we need to call.

**Comment by amcclain** [comment]
Thanks - I think we should expose this API on our GridModel as well - just was looking at this yesterday - in case the developer wishes to call in another context (no pun intended).

**Comment by haynesjm42** [comment]
Another nice auto-size-related feature would be a `keepAutosized` config on GridModel and/or Column where we could do our best to always do an auto-size when appropriate (data changes, group/tree row expansion, adding columns, toggling compact mode, etc) - only complexity is that auto-size only works on rendered rows, so large grids with cell values of varying widths wouldn't be a good candidate

**Comment by amcclain** [comment]
Definitely some caveats (explained pretty clearly by the ag-Grid docs, once you find the relevant section).

In the use case I had, we also got caught with column virtualization causing cols scrolled off to the right not to be auto-sized + the docked summary didn't seem to be taken into account.

Nothing too terrible - but potentially reasons to be wary of making auto-size _too_ much of a feature - just don't want to over-promise.

**Comment by peterjcoffman** [comment]
PR: https://github.com/xh/hoist-react/pull/1620
