### ISSUE TITLE
Expand/collapse grid nodes on dbl click (desktop) and single tap (mobile) by default

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1552]
This is a very natural way to expand/collapse tree grid rows. We are not wiring up anything by default - I believe because we didn't want to eagerly "claim" the double-click action for expand/collapse when an app might wish to use it for something else (e.g. opening a detail modal).

It would be an enhancement however if we could enable this behavior with a simple config vs. needing to wire up a custom handler.

Note we are setting this property within `Column` that appears related, but is not commented (and is somewhat weirdly at the Column, meaning cell, level).  We should understand what this is doing and how it might relate:

https://github.com/xh/hoist-react/blob/e8d32b5bd1713c7386efe7ea325be5f7eff5fc8c/cmp/grid/columns/Column.js#L300

**Comment by amcclain** [comment]
Note the implementation for this might be as simple as:

```
onRowDoubleClicked({node, api}) {
    if (!node?.allChildrenCount) return;
    api.setRowNodeExpanded(node, !node.expanded);
}
```

I still think it would be worth bundling into a config, but of course am happy to discuss.

**Comment by lbwexler** [comment]
Let's go ahead and call this "expandOnDoubleClick".  

As anselm, mentions  let's favor toggling the native ag property, over adding a new explicit handler.

**Comment by amcclain** [comment]
Great thanks - this will help me clean up a few handlers in my code that I've added to do this consistently across grids. Will keep an eye out for it.

**Comment by petradish** [comment]
> This is a very natural way to expand/collapse tree grid rows. We are not wiring up anything by default - I believe because we didn't want to eagerly "claim" the double-click action for expand/collapse when an app might wish to use it for something else (e.g. opening a detail modal).
> 
> It would be an enhancement however if we could enable this behavior with a simple config vs. needing to wire up a custom handler.
> 
> Note we are setting this property within `Column` that appears related, but is not commented (and is somewhat weirdly at the Column, meaning cell, level). We should understand what this is doing and how it might relate:
> 
> https://github.com/xh/hoist-react/blob/e8d32b5bd1713c7386efe7ea325be5f7eff5fc8c/cmp/grid/columns/Column.js#L300

Hi Anselm, can you give me an example of when you might have a detail modal on a tree column? I think it makes sense to always default to AgGrid's native expandOnDoubleClick for tree columns. (The double click property only applies to that first tree column at the cell level, not the entire row, which is why it lives in column). AgGrid's demo tree grids are also only double-clickable on the first tree column.

**Comment by amcclain** [comment]
HI - sorry for the delayed reply - 

+ I realized I would like this to apply to the entire row, not just the tree column.  I find it confusing to have only the tree col have this behavior, especially as it can in some cases only show a >v glyph and not be a primary label.
+ We can look @ an example in the current client app we're working on, where we have a tree grid but also might wish to wire double-click to open an editor form under certain conditions.

**Comment by lbwexler** [comment]
Assigning this to Tom, because Tom is currently working on built-in tap affordances on mobile, and we should have API consistency (and behavioral consistency) to whatever degree posible.

**Comment by amcclain** [comment]
Will review the notes I had started to write up , but bumping to near-term release so we can review in context of current tree-grid-heavy client projects.

**Comment by lbwexler** [comment]
Moving this out to 43 -- we have a PR, but just ran out of time on this one and don't want to rush it
