### ISSUE TITLE
FormField - allow custom string for required indicator (including empty/null to suppress)

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1557]
If a field is marked as required in the model, `FormField` will always print a little * after the label:

https://github.com/xh/hoist-react/blob/a796c3049f34e675223b89eca55a835aca374b87/desktop/cmp/form/FormField.js#L62

This looks weird in some contexts and should be something developers can customize (e.g. set to something more explicit like `(required)` or suppress entirely.  

I suggest that we support a new prop `requiredIndicator` - defaulted to `'*'` - and add it to the list of props that can be defaulted at the form level.

**Comment by peterjcoffman** [comment]
PR:
https://github.com/xh/toolbox/pull/326

**Comment by lbwexler** [comment]
Hi -- Seems like an unfortunate loss of functionality for a pretty technical reason.

This is around recognizing if that fieldDefaults is meaningfully changed, and republishing to the children.  It's a bit of a theoretical concern.  I wonder if we could some how come up with a way to effectively stringify a react element?

**Comment by TomTirapani** [comment]
https://reactjs.org/docs/react-dom-server.html#renderToStaticMarkup ?

**Comment by TomTirapani** [comment]
https://reactjs.org/docs/react-dom-server.html#renderToMarkup to get a string, and the https://reactjs.org/docs/react-dom.html#hydrate on the other end?

**Comment by amcclain** [comment]
I am a-OK with simply accepting a string. (In fact I think it's probably better to keep it simpler.)

I would suggest that if we're rendering an indicator (either the default or a custom string) we wrap it in a span with a class that the developer could key off of to style (e.g. make light gray, or smaller)

**Comment by lbwexler** [comment]
Think we could rework how the defaults are published, but not worth it for this.  So agree with Anselm.  

Can we have the default documented as just '*'.  The spacing implementation can be kept internal!
