### ISSUE TITLE
Charts should react to theme changes

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#1560]
Our Charts support both a light theme and dark theme... however, when the theme changes, the Chart doesn't react to the change.

Easily reproduced in Toolbox by toggling the theme when viewing a chart

**Comment by lbwexler** [comment]
We may have jsut regressed this.  Peter think we just need to observe the Theme as well and re-render the underlying highchart when it changes.

**Comment by peterjcoffman** [comment]
https://github.com/xh/hoist-react/pull/1563

**Comment by lbwexler** [comment]
Thanks Tom and Peter  👍
