### ISSUE TITLE
DataView should support dynamic itemHeight

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#1566]
We have a need in a client app for DataView to use different itemHeight for different data. If itemHeight is observable, the DataView should react to changes to it.

**Comment by lbwexler** [comment]
@peterjcoffman -- can we get started on this today?  Would like to prioritize this ticket, as its needed for Tom's high priority client App.  :-)

**Comment by peterjcoffman** [comment]
Does this require having height vary between items, or is there one height for every item displayed in the DataView?

**Comment by TomTirapani** [comment]
Hi Peter. We need every item to be displayed at the same height. The height changes based on the type of data requested, but not per-item.

**Comment by peterjcoffman** [comment]
PR is here:

https://github.com/xh/hoist-react/pull/1589

I think it's a bit funky, so I'll talk it over with Lee.
