### ISSUE TITLE
Add support for hiding Select indicator through props

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1575]
The Select control indicator can be easily hidden via css, but would be nice to add a prop for hiding. Use case is when using a Select as an async search field, everything else about how Select works makes this very convenient, but the indicator doesn't really make sense in this case.

```
.xh-select__indicators {
    display: none;
  }
```

**Comment by peterjcoffman** [comment]
This can be done using the react-select `components` property.

https://react-select.com/components

**Comment by lbwexler** [comment]
Peter -- realize
