### ISSUE TITLE
Improve perceived performance of Tab switching/rendering

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1581]
Top-level tabs in our applications tend to become very complex, and the initial render can take a bit of time, during which the application may seem unresponsive for a few seconds. Even after the initial render, for complex tabs, there can be a small period of unresponsiveness while the tab renders. I'm not sure we can do much to improve the render performance, but we could improve the perceived performance by ensuring the user interactions (mouse click on tab switcher) appear to be processed immediately and slightly deferring the actual tab content render. 

We could make this an opt-in feature so an app could use this on either/both the initial render and subsequent renders of the tab. Not sure what we should display in the empty space before we actually render the tab contents, but I think an empty container for a second would feel better than the app appearing to hang for a second.

If we could figure out a good way to make use of some kind of skeleton styling (https://blueprintjs.com/docs/#core/components/skeleton), especially for the initial render, that would look good. This seems to be what Asana does on initial render. Not sure if that is feasible without explicit setup by the application though.

**Comment by lbwexler** [comment]
John -- when we ever not want this on?  If we do it right, it seems like it's a no-op when things are fast, and a clear improvement when things are not.

**Comment by haynesjm42** [comment]
If we can get this to be a no-op for fast-rendering tabs, then definitely just something we can have on all the time. My only concern would be if perceived performance because _worse_ for small tabs which do not have any perceivable render time because we show an empty container for a frame or 2 before rendering the tab contents.

**Comment by lbwexler** [comment]
I discussed this with John and we think we don't really have an issue right now.  Hopefully browser and processor improvements will just make this even less relevant going forward.  Our TabComponent is already complex enough as it is.

Turning off animation helped a lot as well
