### ISSUE TITLE
RelativeTimestamp should add a class when displaying the equalString

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1590]
Would like to be able to style the element differently when the display value is the equal string, compared to an actual relative date string.

**Comment by peterjcoffman** [comment]
John and I discussed this. We believe it would be better to allow the user to specify an element to be displayed rather than just a string. This keeps the RelativeTimestamp simpler and more versatile while giving more power to the user.

**Comment by peterjcoffman** [comment]
PR: https://github.com/xh/hoist-react/tree/timestampElements

**Comment by lbwexler** [comment]
John and I discussed this at great length.  We think that given the uncertainty around this, and the simplicity of this component which has worked well until now, we think it makes more sense to keep it as it.  

The client application in question may have additional requirements, and probably worth building a custom component for that in any case.
