### ISSUE TITLE
NumberInput leftIcon is not displayed

### ISSUE THREAD

**Issue by peterjcoffman** [xh/hoist-react#1594]
I tried setting a leftIcon on several numberInputs and it is not displayed. The problem occurs even if I hard-code a leftIcon in the NumberInput class itself.

**Comment by peterjcoffman** [comment]
This does work if the leftIcon is defined as a string which Blueprint handles internally, such as:
```
leftIcon: 'dollar'
```
But it does not work if we define it using out `Icon` utility, like:
```
leftIcon: Icon.skull()
```

**Comment by lbwexler** [comment]
Hah!   Was retesting this, and realized that it was working fine in our DarkTheme.  !?!  So presumably just somehow hidden in our LightTheme.  Presumably a problem with some context specific styling on our icons in light theme 

Also note, that explicitly changing the className on the icon does not change the color in this context -- that would be nice to support as well, e.g. Icon.skull({className: 'xh-red'})

**Comment by TomTirapani** [comment]
PR here: https://github.com/xh/hoist-react/pull/1785

This turned out to be trickier than expected. It turns out BP uses a different z-index for icons inside of a "control group" input than for inputs, which meant our input icon styling was showing the icon *behind* the input. The reason you could see it in dark theme is because dark theme uses a semi-transparent input background color

**Comment by TomTirapani** [comment]
For the second part about applying the styles, there's no easy solution there. The input icon color styling has a higher level of specificity than the color styles, so its gets overridden.

We *could* use !important in our color styles, but that may well have a number of unintended side-effects - and besides, that would only apply to our provided styles, not any custom ones.

**Comment by lbwexler** [comment]
Closing. Thank You.   Don't think we need to address the second problem of custom icon styling.  Its unfortunate, but much less important.
