### ISSUE TITLE
Update flex columns to use new ag-Grid functionality

### ISSUE THREAD

**Issue by peterjcoffman** [xh/hoist-react#1602]
ag-Grid now supports flex columns. The documentation can be found here:

https://www.ag-grid.com/javascript-grid-resizing/#column-flex

Our flex columns should use the built-in ag-Grid flex functionality.

**Comment by lbwexler** [comment]
I believe that we should look at their new flex implementation and see if we can remove our custom handling around flex columns.

See

hoist-react/cmp/grid/columns/Column.js

Line 369 in a0538de

 ret.width = Number.MAX_SAFE_INTEGER; 
where we currently take our formerly unique flex config on Column and translate it into an extremely large width. This ends up paired with multiple calls to sizeColumnsToFit() to create the effect of flex columns taking up as much room as they can (but not actually taking up the width that's been specified):
hoist-react/cmp/grid/Grid.js

Line 470 in a0538de

 api.sizeColumnsToFit(); 
Would need to look carefully as these two lines of code are definitely not the entire implementation of this feature. Would also want to understand how the new ag-grid impl differs from the scheme we have in place currently.

**Comment by peterjcoffman** [comment]
We call api.sizeColumnsToFit() a bunch of times in `Grid` and in two places on `GridModel`.

I don't think any of them are needed any more. I believe `sizeColumnsToFit` already had no effect on the majority of columns because we set `ret.suppressSizeToFit = true`, and the ag-Grid flex columns seem to update whenever needed.

**Comment by peterjcoffman** [comment]
ag-Grid flex columns accept a number, which is analogous to the CSS flex property. Space is divided between the various flex columns in proportion to the value of their flex prop, i.e. a column with `flex: 2` will be twice as big as a column with `flex: 1`.

Should we still allow users to specify `flex: true` and then convert this to a `1`, or should we make this a breaking change and require people to specify `flex: 1`?

**Comment by peterjcoffman** [comment]
WIP PR is here:

https://github.com/xh/hoist-react/pull/1605

**Comment by lbwexler** [comment]
This PR looks very promising, but lets WAIT for hoist v30.  We need to live with agGrid v22 for a bit first.

**Comment by lbwexler** [comment]
to be clear -- this ticket and PR is being blocked by the following ag-ticket

AG-3852 | react: cellRenderer being remounted when updating

which seems to be causing real performance problems.
