### ISSUE TITLE
Filter on ColumnChooser is broken

### ISSUE THREAD

**Issue by mpeckerman** [xh/hoist-react#1607]
1. Navigate to Toolbox -> Other tab
2. Click LeftRightChooser sub-tab
3. Navigate to Other->LeftRightChooser panel
4. Populate the "Quick filter" field and click "Enter"
No data is being retrieved  

![Screen Shot 2020-01-28 at 3 58 20 PM](https://user-images.githubusercontent.com/40367298/73305006-5060e680-41e7-11ea-8c01-7c8676a5ce64.png)
![Screen Shot 2020-01-28 at 3 58 20 PM](https://user-images.githubusercontent.com/40367298/73305044-6078c600-41e7-11ea-8067-f2043acc6a8c.png)

**Comment by lbwexler** [comment]
thanks for the super quick fix peter!
