### ISSUE TITLE
Column should accept HTML strings and/or React elements for headerName

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1608]
App developers sometimes want to include icons or more richly styled html as the headerName.

Ag-Grid will set the `headerName` as the `innerHtml` in the column headers, so providing HTML strings works fine there, but we are just passing it as the item for a `span` so the string is being rendered as-is.  We should probably be using `dangerouslySetInnerHTML` or use a library like [react-html-parser](https://www.npmjs.com/package/react-html-parser) (using in a client app and it works great) to set the header span contents so we aren't losing functionality which ag-Grid provides.

Also it seems that providing a react element as the `headerName` works fine, we should decide if we want this to be something we support and update our documentation to reflect that (and make sure there are no potential issues)

**Comment by amcclain** [comment]
+1 for react-html-parser in general - I am using that in a client app to display user comments that can contain simple HTML, and it seems to work well.

But since we're already in the business of providing a custom ColumnHeader, it seems to me that we could go ahead and document that as taking an element that we can insert into our items array. I think that would be preferable to getting HTML in the mix.

We could make it clear that jamming any old kind of component in here won't work - you still need to be sensitive to how much space is available, etc.

**Comment by amcclain** [comment]
@haynesjm42 if you can provide a sense of urgency or  tag as client-request if applicable, that would be great.  The change to just update the doc and call it a day would be an "easy" one, so if that's viable and covers what you need, I am up for that.

**Comment by haynesjm42** [comment]
Not urgent at all - client's immediate need was well served by the undocumented feature of using an element for `headerName`. 

Just supporting elements here instead of html strings sounds good to me - only thing we might want to consider in additional to the doc updates is the fact that the `headerName` element would be added as a child in a span - we might want to only do that if the `headerName` is a string. Also needs to double-checking to make sure things like alignment, etc. work with the kinds of elements we would expect users to provide.

**Comment by peterjcoffman** [comment]
I believe @febbraiod is currently using an element for headerName as well.

**Comment by peterjcoffman** [comment]
In `MultiFieldRenderer`, we use headerName on line 89:

    if (label && !isString(label)) label = headerName;

Does this work properly at present? Will it work properly with elements for headerName?

I don't know what a `MultiFieldRenderer` is used for.

**Comment by peterjcoffman** [comment]
Surprisingly, this works just fine with the context menu `Copy with Headers` option. It looks like ag-Grid just ignores non-string headerName for copy.

**Comment by peterjcoffman** [comment]
PR: https://github.com/xh/hoist-react/pull/1627
