### ISSUE TITLE
A form component can be imported from layout package, breaking formFields

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1616]
The form in the layouts package is an HTML form.

**Comment by lbwexler** [comment]
Think we decided simply to console warn if a FormField ever finds itself *outside* of a Form.  Developer can be warned that maybe they misimported the html Form, rather than the Hoist Form they intended to import

**Comment by peterjcoffman** [comment]
@lbwexler Where can I find the Slack discussion?

**Comment by febbraiod** [comment]
Hoist Room: Jan 30, 1038am

**Comment by peterjcoffman** [comment]
@lbwexler 

I think we should throw, not warn. If it's outside a Form then I think `formField` will always throw on render, so we may as well have it throw at the right place.

**Comment by lbwexler** [comment]
Well, we could change that as part of this fix.  It was that throw that was making people so miserable and confused and precipitated this change.

If possible, we have been trying to have errors like these be gentler, to allow a smoother development time experience --we would like to allow you to start to build your form visually and seeing it, without it violently failing....
