### ISSUE TITLE
DataViewModel should support groupBy

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#1617]
Could we add a groupBy property to the DataViewModel so that the DataView grid can render the sorted field according to groups (or at least a single, specified group)?

Use case for Hoist Roadmap, to group by quarterly phases:
![Hoist Roadmap](https://user-images.githubusercontent.com/49966727/73466173-7b664a00-434f-11ea-86b2-88b2ce8fe4b2.jpg)

**Comment by peterjcoffman** [comment]
https://github.com/xh/hoist-react/pull/1618

**Comment by lbwexler** [comment]
👍 Thanks All!
