### ISSUE TITLE
Support menuDividers in appMenuButton.extraItems

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1628]
Currently there is no way to put a menu divider into the set of extra items passed to `appBar.appMenuButtonProps.extraItems` - this only accepts plain objects and passes each to the `menuItem` elemFactory.  

At the least `appMenuButton` should check to see if any extra item is a component vs. plain object and handle accordingly. 

Better still would be to support the string token `'-'` as a shortcut to add dividers, although I don't know if we do this consistently elsewhere.

**Comment by amcclain** [comment]
Tried a quick in-place patch of this for my project, but weirdly difficult to know how to distinguish between a config object and an elemFactory output.....

**Comment by haynesjm42** [comment]
FYI I added #1222 a while back when I wanted to do this in a client app (and then promptly forgot about it ..)

**Comment by amcclain** [comment]
Hi Don - we need to apply the fix you made recently for `extraItems` to all other custom props we support for appMenuButton - you will see a console warning if you open the Hoist Admin console (in local dev mode) re. attempting to set `hideAdminItem` on the DOM button.
