### ISSUE TITLE
Add support for maxRows or similar config on GridModel

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1636]
This is useful to achieve "top n" or "bottom n" grids, where the top/bottom is driven by the sort config of the grid and the amount is driven by the number of rows shown.

We can achieve this by using the ag-Grid pagination support and hiding the pagination panel. This way we leverage the ag-Grid sorting to handle the top/bottom ordering. Filtering is an issue, but is a larger issue with our grid implementation so outside the scope of this ticket.

 https://www.ag-grid.com/javascript-grid-pagination/

Then GridModel can call `agApi.paginationSetPageSize(maxRows)` to change the row count at runtime.

**Comment by peterjcoffman** [comment]
Do you want the ability to change the number of rows displayed at runtime?

**Comment by haynesjm42** [comment]
Yes definitely an important aspect of this, expect it to be used with toolbar controls to change between Top 10, Top 20, etc.

**Comment by peterjcoffman** [comment]
I think we need to consider how this behaves when the user tries to operate on a row that is not currently displayed. Consider what would happen if the user selects the first row and then reverses the sort order. The currently selected row will not be visible since it will be at the very bottom of the Grid, well past the limit we set on the number of displayed rows. However, it will still be considered selected. Any operation the user tries to perform on the current row will then affect this hidden row, with no indication to the user that it is the selected row.

**Comment by lbwexler** [comment]
Peter and I discussed the selection issue in detail.  We need to drop the selection for rows that are off the visible page.  Hopefully we do something similar when a filter is applied and a row is filtered out?

More drastically, we might consider disabling selection entirely with this mode.

**Comment by haynesjm42** [comment]
Filtering using our store filter should be fine because we are applying the filter to the store records, so the record is no longer visible to the selection model and it is updated accordingly. 

Filtering using built-in ag-grid column or quick filter would probably have this same problem. Would be interesting to test that and see what happens in that case, I would expect the behavior to be identical to changing the page size/sort. Ideally ag-grid would update their own selection state to clear the selection of rows which are no longer visible, and we would handle that event and update our selection model accordingly. If filtering handle this correctly but pagination does not, then it sounds like an ag-grid bug that we should report.

**Comment by peterjcoffman** [comment]
@lbwexler @haynesjm42 

We currently do deselect rows that are filtered out. The filtering is done at the level of our store.

I am not sure of the best way to deselect rows that are not displayed. I know that changing maxRows or changing sort order with maxRows enabled can cause a row to become hidden. Would it be best to add a reaction to those two things?

**Comment by lbwexler** [comment]
Shelving this one.  There is not a client demand on this one right now, and it may interact and make it harder to do other more important grid features that we are working on rolling out.
