### ISSUE TITLE
Grid still isn't "ready" when agGridModel.isReady === true

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1638]
I was trying to setup a mobx `when` to select the first row in the grid once the grid became ready, because trying to set selection before the grid is first rendered (ready) results in a warning, like so:

```
when(
    () => gridModel.agGridModel.isReady,
    () => gridModel.selectFirst()
)
```

But it still wasn't working, adding options as the third argument to `when` with a delay `{delay: 1}` fixes it, so it seems that when our `isReady` flag becomes true, the grid still isn't quite ready enough to handle selection (and perhaps other things as well).

Seems like we may need to defer the setting of that flag in `AgGridModel` 1 frame or millisecond to be sure the grid has been rendered and initialized fully.

Also might be nice to add an `isReady` getter on `GridModel` to avoid having to go through the `agGridModel` property. 

Another thing to consider is if there is a better way we can handle this in general? Why do we not maintain the selection state in our `StoreSelectionModel` and then sync the grid once it becomes ready? I don't see any reason why we need to force the application to wait for the grid to be ready since we are managing the state here, not ag-grid.

**Comment by amcclain** [comment]
+1 on this.

I pretty regularly see console warnings related to this, and manually add waits when I want to select the first row programatically.  Would be great to have a more managed / centralized solution.

**Comment by peterjcoffman** [comment]
I've been doing a little digging and have had no luck in finding out why this is a problem.

I have implemented the suggested workaround, but I do not understand why it is necessary.

**Comment by peterjcoffman** [comment]
I believe we are running into a race condition. `Grid.js` contains several reactions that fire as soon as the `agApi` is installed. These reactions have some important functionality, such as loading data, that should be completed before the application or the user interact with the grid.

If the reactions on the grid fire before the application reactions, there is no problem. Methods such as `selectFirst` will work. However, if `selectFirst` fires before the reactions on the grid, then the data is not yet loaded into the grid and there will be no rows to select.

@amcclain What console warnings were you seeing? I don't know of a situation where `selectFirst` would give warnings.

**Comment by febbraiod** [comment]
I have seen this issue recently in a flagship client app. Will add a 'wait' for now, but wanted to put another upvote in

**Comment by lbwexler** [comment]
OK -- we had a bit of a false start here, but think that the simplest thing is to put a delay.  Don -- I can put together a PR with the latest idea.  can you help me reproduce and test it?

**Comment by lbwexler** [comment]
John -- to answer your main question -- we *do* let you go ahead and manipulate the selection model without the grid being rendered.  

The one thing that we *cannot* do, unfortunately, is selectFirst(), as we are relying on ag-Grid to sort the records.  Other methods that rely on the actual underlying ag-Grid state being settled are ensureSelectionVisible and localExport.

I would be very curious to see the context you were looking at when you first filed this bug, John.

**Comment by lbwexler** [comment]
Went over this in detail with John and examined the original case in a client app that led to this ticket.  
It doesn't seem that the grid is ever "lying" about being ready, or exceptions being thrown 

We still have the issue of needing to insert delays on selection operations after loading but that really is a different issue.  Perhaps we need the grid to go into some kind of "unsettled" state until its data reaction fires.  

In any case closing this ticket, which I think would just confuse us when working on that other issue.
