### ISSUE TITLE
Fix FormField overriding the disabled prop of its child input

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#1642]
v29.0.0 seems to have regressed this change from v25.1.0: FormField will no longer override the disabled prop of its child input if true (#1262).

Effectively, input field disabled property is ignored if it is in a FormField.

ATM identified this change as a culprit:
https://github.com/xh/hoist-react/commit/bc5ab92409ca4be4d66defa64d46f449a91cb250#diff-e52ac5da1fa0c43ce42c2675975a79d2L198

**Comment by lbwexler** [comment]
This looks like a merge issue with our too-long outstanding move to functional components.  

I fixed it here.

https://github.com/xh/hoist-react/commit/ba8bae67a
