### ISSUE TITLE
Add disabled property to StoreFilterField

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#1643]
There is no way to disable StoreFilterField, so it would be helpful to add a disabled property.

Pro: All input fields should have the ability to be disabled.

Con: A likely use case is to disable when the data is not loaded. However, this case is better served by masking the enclosing grid/toolbar panel.

**Comment by lbwexler** [comment]
Think its generally like a TextInput, so would favor being able to disable

**Comment by amcclain** [comment]
Any reason not to relay all `...props` to the underlying TextInput?

**Comment by lbwexler** [comment]
Agree, Anselm makes sense!
