### ISSUE TITLE
Expose better exception messages to client in restGrid

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#1650]
Currently client 400 request errors are thrown as server-side 500 exceptions with no clear message on why the request failed. For example, if a client posts a request that violates a constraint on the data model, client is thrown a 500 error and the detailed dialog includes an exception message that says "No message available". It would be useful to expose better server-side exception messages to the client such as "400 error - Unique constraint violation on name".

**Comment by peterjcoffman** [comment]
I'm confused. I thought I fixed that quite a while ago in this PR:

https://github.com/xh/hoist-core/pull/101

But it is indeed not working. I'll take a look.

**Comment by peterjcoffman** [comment]
https://github.com/xh/hoist-core/pull/108

**Comment by lbwexler** [comment]
Thanks for the quick fix guys  -- my apologies for failing to see the connection here!
