### ISSUE TITLE
Chrome CORS "SameSite" warning when using Config differ

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1651]
![Screen Shot 2020-02-12 at 9 06 04 AM](https://user-images.githubusercontent.com/225806/74342108-f6c7f280-4d76-11ea-93ba-8e5fa0605234.png)

**Comment by peterjcoffman** [comment]
This is caused by a recent change in Chrome. All cookies are now required to specify a `SameSite` attribute.

We can still have the same behavior as we have now by setting `SameSite` to `None`. This will still allow the ConfigDIffer to work.

Unfortunately, this may be difficult to fix in Grails. Grails tracks sessions using a JSESSIONID cookie. I have not been able to find an easy way to set `SameSite` on this cookie.

**Comment by amcclain** [comment]
Thanks much for looking at this Peter, and for these additional details.

It appears as though we can do this at our nginx proxy layer via the `proxy_cookie_path` directive. I have it working locally, although we will want to proceed with care as if we somehow break cookies we'll obviously break auth as well in general.

I'm going to experiment a bit more, then should have an update to our xh-nginx base image to put this into place.

**Comment by amcclain** [comment]
This appears to be resolved by https://github.com/xh/xh-nginx/commit/7db17f610d6b52f9bcfc72a94515a6b83ea062af.

Some notes:

* I am a bit concerned that this cookie path adjusting directive could have some unintended consequences for apps with non-standard deployments - e.g. where their nginx config has been adjusted to listen on a particular sub-path (and not `/`). I don't really know that there would be an issue - I just want to proceed with care here.
* Given that, I added this to our pre-existing `xh-hardeners.conf` include, which is opt-in in that apps must add an include line to their nginx config's `location /api/ { ... }` block.
* I also pushed this to a new `xh-nginx/develop` branch and adjusted our autobuilds on hub.docker.com to build off of develop as `xh-nginx:next` so we have a chance to test this before it gets rolled out generally.

@haynesjm42 some of the client apps you have managed are probably the most likely to have a custom nginx setup. If that's the case, when you have a chance could you try updating one of their Dockerfiles to use `xh-nginx:next` as its base image and ensure that it's including xh-hardeners? 

No rush really - I don't _think_ this will break anything for apps that have yet to update (other than the config differ) if/when Chrome rolls out their new policy.

**Comment by amcclain** [comment]
I'll leave this open for a bit to see if we have time to test in some client apps and - if successful - will merge into `xh-nginx/master` and close this ticket out.

**Comment by amcclain** [comment]
Closing as we can revisit if we see any actual issues in practice when we promote `xh-nginx:next` to `latest`, which we're gonna need to do soon due to other changes in the base image for k8s support.
