### ISSUE TITLE
Config differ warns about deletions when attempting to apply "remote only" config

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1652]
From https://toolbox.xh.io/admin/general/config launch the config differ and diff against toolbox-dev. Note there is a `toolboxDevOnlyConfig` string config that only exists on the remote instance.

Click to apply it locally, which will add it to the local server - differ warns that operation includes deletions, which it should not!  (Did not investigate if it's just the warning that's wrong, or if it would actually delete something locally....)

**Comment by peterjcoffman** [comment]
This seems to be yet another problem caused by our change to the Record API.

I think we might want to make a change like [this](https://stackoverflow.com/a/45322399) because we have been bitten by this particular bug so many times.
