### ISSUE TITLE
Column tooltipElement doesn't work without a tooltipValueGetter

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1656]
Seems like an ag-grid bug, but the `tooltipElement` doesn't seem to work at all unless you are also providing a `tooltipValueGetter`. Would be easy for us to workaround by installing a default `tooltipValueGetter` alongside the `valueGetter` - but also should determine if fixed in latest ag-grid and if not, should be reported to them.

**Comment by haynesjm42** [comment]
Another issue with the `tooltipElement` is that providing a `tooltip` in a Column when there is a `tooltipElement` in the `GridModel.colDefaults` will not work, the `tooltipElement` is always added and takes precedence

**Comment by amcclain** [comment]
A reasonable first step might be to warnIf both end up specified - a developer could then resolve by setting the defaulted config to null in the column where they want the different behavior.

Alternatively, we could ensure the column's config is applied by deleting the default after merge - is that what you were thinking?  I suppose it's always a bit weird when you need to set one config to null to get another to work...

Also we just merged the ag-Grid 23 upgrade - would you have a chance to re-test the tooltip stuff in the off chance the situation has been improved?

**Comment by lbwexler** [comment]
Still a problem in ag-Grid 23. :-(

**Comment by lbwexler** [comment]
I have a solution for this and will putting in a PR shortly
