### ISSUE TITLE
Document title should be set based on AppSpec.clientAppName

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1661]
We currently set the document title based on the `appName` in the webpack config via the HtmlWebpackPlugin, but in the case where an application has multiple sub-apps, this is not usually what you want.  The admin app is a good example where it would make more sense for the title to be "MyApp Admin" instead of just "MyApp".

Not sure if there is a way for us to retrieve that from the AppSpec during build time, we may need to set it at runtime, though that is not really ideal since you would see the default `appName` from the webpack config for a second until our init process has started and the AppSpec has been parsed ...

**Comment by amcclain** [comment]
Yes - agree.

Note we already adjust the title on the fly to append non-prod environment name:

https://github.com/xh/hoist-react/blob/96d4cc95c05e854217ee7e983278b550dbcb671c/svc/EnvironmentService.js#L61

I would vote for moving this logic to the overall init sequence - probably here:

https://github.com/xh/hoist-react/blob/96d4cc95c05e854217ee7e983278b550dbcb671c/core/XH.js#L509

and include the change to use `clientAppName`. Note this is the real resolution for https://github.com/xh/toolbox/issues/252.

**Comment by lbwexler** [comment]
Better to not set a name then in the webpack config?  Or set a name of the empty string, trusting the javascript to set the name?
