### ISSUE TITLE
Add "UI Server Unavailable/Starting" modal to bootstrap process

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1665]
John Haynes, Tom and I discussed this in the context of a client app that takes a little while for the server to "warm" up, but this could be generally useful for any "hot" restart, as the grails server always takes a bit to come up:

> What if we had environment service also return a server status which could be either 'READY' ,  or 'STARTING'.  Our bootstrap code in XH  consults this first -- if it gets a failed request, or a request with server 'STARTING' it brings up a special modal (rather than throwing as it does now).  The modal would have some kind of a friendly wait image and eye candy, and would say "Server currently [unavailable|starting], please wait.." and would have a timer that would retry every 5 seconds or so until it got a better response...
>
> in a world where we don't have seamless deploys might be very helpful for allowing us to do intraday restarts and re-releases
>
> timer could eventually stop (to avoid zombie request storms) leaving just a button for the user to try to reload the app....
>
> (I know we have bandied about ideas just like this for a while -- just seems to me maybe the time is ripe now)

**Comment by lbwexler** [comment]
Happy to discuss this Tom, but wanted to make sure the man behind the Owl is on this one.  Need a pleasing, but appropriately serious dialog for this critical modal.

**Comment by amcclain** [comment]
Note this will just catch the case where the user happens to be loading the app during the restart. Not a non-trivial situation, but wouldn't cover the case where a user already working with the app attempts to continue using it while the server's being bounced.

Any sense we should/could extend this further to have environmentService maintain more of a heartbeat? Could bundle up the current version check with an overall connectivity / server state check. I.e. a bundle that either:

- Doesn't return - indicating a low-level client connectivity or server issue - which could trigger a new top-level warning bar if enabled.
- Returns `serverStatus: 'STARTING'` (or whatever we decide), triggering the proposed new model, or maybe better a new top-level bar (for the user who has a grid of data they are scanning and might still want to finish reading that essential data point....)
- Returns a new version, triggering the update bar.

Thoughts?

Note too that we've had https://github.com/xh/hoist-react/issues/887 open for a while - this could be a chance to get that done as well, if we had a general API for showing an alert bar with an optional action button (or any arbitrary content). The new bars + version update banner could use this API for their implementation.

**Comment by lbwexler** [comment]
Houston we have a problem...

**Comment by lbwexler** [comment]
Definitely thought of your case, but was concerned about overreacting to hiccups.  But of course a banner, which came up conservatively, and took actions conservatively is definitely the way to go.

**Comment by TomTirapani** [comment]
Looking at this... it seems all calls to the server will fail until *after* the Bootstrap is complete. So I'm not sure when the server would be 'STARTING' - looks like the server will either be unable or ready

**Comment by TomTirapani** [comment]
Unless we want to require apps to explicitly say when they are ready? In which case we can do some async startup stuff on the server and be 'STARTING' until the app has explicitly said its ready. Downside is this will require changes in all apps.

**Comment by amcclain** [comment]
Thoughts in https://extremelyheavy.slack.com/archives/GE614HJDT/p1582115540002400

**Comment by amcclain** [comment]
Largely handled by new blocking init with dedicated exception to relay to client that server has not yet fully initialized
