### ISSUE TITLE
DashContainer should support "no more views to add"

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1668]
A dev might wish to specify all views as `unique` if the Dashboard is such that it doesn't make sense to have more than one copy of any of its widgets.

In that case, the (+) button would ideally disappear from all panes of the dashboard once an instance of each view has been added. If that's not easily achieved, we should at least show a placeholder entry such as "All available views have been added" in the menu. Currently it's weirdly empty.

**Comment by lbwexler** [comment]
Fixed by:   https://github.com/xh/hoist-react/pull/1690
