### ISSUE TITLE
DashContainerModel won't regenerate GoldenLayout after unmount

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1669]
See discussion in XH Slack @ https://extremelyheavy.slack.com/archives/C4MF830H5/p1582021229022300 + Toolbox branch/commit to demo @ https://github.com/xh/toolbox/commit/663ddbd7ea3d6ae3c8722f8b2487e9c6be908679

**Comment by TomTirapani** [comment]
Fixed here: https://github.com/xh/hoist-react/pull/1670
