### ISSUE TITLE
Update react-beautiful-dnd to 12.x

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1675]
We are currently on 11.0.5, want to go to latest 12.2.x.

We use this in the mobile column chooser. Since it's a major release, we should look carefully at what changed since our current version via their [releases page](https://github.com/atlassian/react-beautiful-dnd/releases). But hopefully no major adjustments are required (if any).

**Comment by petradish** [comment]
Reviewed the release change docs and played with the latest version on the mobile toolbox in local. No adjustments necessary.

**Comment by lbwexler** [comment]
Great -- can we get a PR for this change for v.30
