### ISSUE TITLE
Rendering bug in multi-select Selects inside of Toolbars

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1676]
This is a weird one - I am only seeing it when we have a Select control with enableMulti: true inside of a toolbar and (I think) a custom font active, such as we're using in Toolbox:

![Screen Shot 2020-02-19 at 9 35 48 AM](https://user-images.githubusercontent.com/225806/74844427-6dc33500-52fb-11ea-935c-181972e2c791.png)

I'm not sure where that gap or color is coming from.........

**Comment by TomTirapani** [comment]
I think that is a vertical scrollbar... probably because the font's height is too tall. I can take a look

**Comment by TomTirapani** [comment]
Fixed here: https://github.com/xh/hoist-react/pull/1677
