### ISSUE TITLE
Inconsistent styling between local and deployed version of app

### ISSUE THREAD

**Issue by peterjcoffman** [xh/hoist-react#1689]
I noticed this issue at first on the mobile version of Toolbox. localhost:3000/mobile does not appear the same as toolbox.xh.io/mobile.

Localhost:
![image](https://user-images.githubusercontent.com/48924151/74983021-3a6bcd80-5403-11ea-9c0d-3cebf9d2f1b1.png)
Production:
![image](https://user-images.githubusercontent.com/48924151/74983028-3cce2780-5403-11ea-9e63-834e62f61b2d.png)

It appears that `xh-toolbar` styles are overriding `xh-appbar` styles on localhost.

This is reproducible on multiple machines (at least mine and @petradish's), so it doesn't appear to be a problem with my development environment.

**Comment by lbwexler** [comment]
Fixed in 

https://github.com/xh/hoist-react/commit/7cdbef53111e103c7bca4d81749545583846c9e4
