### ISSUE TITLE
Column should support mobileOverrides

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1693]
Would be great for Column to have a config for `mobileOverrides` which would be an easy easy way to specify alternate defaults when `XH.isMobile` is `true`. The most common usage of this would be hiding certain columns by default and setting a different default width. 

Another option would be to allow Column to accept some like this, to allow overriding on a per-sub-app basis if we are dealing with more than just mobile/desktop platforms
```
{
    width: 80,
    appOverrides: {
        mobile: {
            width: 30,
            hidden: true
        }
        tablet: {
            width: 50
        }
    }
}
```

**Comment by amcclain** [comment]
I like this idea. 

The idea of app does seem like it would provide the benefits of the platform (mobile/desktop) overrides concept, but push it a bit farther, although potentially at the expense of being a bit more difficult to document or work into a typescript definition. 

Supporting both as `platformOverrides: {mobile: {}, desktop: {}}` and `appOverrides: {coreApp: {}, detailApp: {}}` would be yet another all-of-the-above option....

Happy to discuss in the coming week.

**Comment by TomTirapani** [comment]
Please see PR here: https://github.com/xh/hoist-react/pull/1774

Code's not as clean as I would like, but I felt it was easiest to apply the overrides first in the constructor to minimise changes elsewhere. The downside of this is that we lose the destructuring of the constructor arguments.

I went with just supporting `appOverrides` for now. Given that `isMobile` is set in `XH.renderApp()`, I think we have a strong notion of "different apps for different platforms", so felt that app overrides would be sufficient for most cases. Its currently not expected for the same app to support multiple platforms, but if we ever find we have multiple apps that must share the same platform overrides we can revisit.

**Comment by amcclain** [comment]
Closing - see notes in PR
