### ISSUE TITLE
Button Styling Issues

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1699]
It looks like in the v30 Snapshot we have some unintentional changes to default button styling:
 + No longer seeing any hover in light theme on standard buttons.
+ The background color on dark theme is pretty different than what we have.

I am looking at the grid of buttons in Toolbox ->  Other -> Popups, where the problem is apparent.  Have not looked more extensively at other buttons where it might be happening

**Comment by TomTirapani** [comment]
Apologies for letting this one through :(

Thanks for jumping on this John, changes look great!
