### ISSUE TITLE
Select should select all text after opening if enableFilter is true

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1705]
It is currently a little annoying that when opening a Select input which has `enableFilter` turned on (default is on) that the text in the input is not selected automatically, so if you start typing the characters are appended to the end of the current value, which is almost never what you want to happen.

We need to consider whether this behavior would be desired if `enableCreate` is turned on as well. Probably should be consistent, and user could click at the end of the text or hit the right-arrow key if they do want to just append some characters to the end of the current value.

**Comment by peterjcoffman** [comment]
What would this be noted as in the changelog?
