### ISSUE TITLE
Enhance Timer API

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1709]
Some nice-to-haves to consider, from a recent convo with John H

+ Would be nice to have delay = true, yield a delay equal to the interval. We often want that.
+ Programmatic way to start and stop.
+ Might we have a createAndRun() version that creates returns a running timer -- *after an initial blocking run"

**Comment by amcclain** [comment]
Can we add ability to pass an appConfig name string as the interval, as we do on the hoist-core?

https://github.com/xh/hoist-core/blob/f6349db9119d88e6ed150cab6015181783258605/src/main/groovy/io/xh/hoist/util/Timer.groovy#L29

We won't get the server-side ability to dynamically respond to config changes on the client (at least not yet) but still seems like a nice little pickup + more symmetry with the server-side class.

**Comment by lbwexler** [comment]
One thing that is making the appConfig thing a little less convenient (on server and client) is that we often get timeout intervals from within nested json within config.  

I actually think the most elegant way to make the whole thing "dynamic" on client and server might be to allow just defining the interval as a function/closure that can be re-read periodically.  Would be more flexible than what we have, and syntax would be not much more verbose

**Comment by lbwexler** [comment]
Did two out of the four ideas in this ticket -- hopefully a nice pickup and enough to earn closing the ticket!
