### ISSUE TITLE
DimensionChooserModel should provide a public api for getting/setting its history

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1712]
Currently it supports saving/loading the history to a preference only, but we have cases where we would want to be able to save the history in a different data structure (such as when you have multiple instances of the same grid using the dim chooser in a dash container)

This kind of state serialization api is something we likely want for any of our component models which have the convenience support for saving their state to a preference. Grid and Panel are two that come to mind, not sure if we have others. Perhaps we could/should remove the built-in preference saving that we have in models in favor of providing some utility service/methods for wiring up the state serialization to a preference.

**Comment by lbwexler** [comment]
Closing this, after consultation with John -- we think the solution to 

https://github.com/xh/hoist-react/issues/1898

will take care of this use-case.   It seems most likely that we will continue to always just want to put the history in one preference or another, rather than in a dashboard.
