### ISSUE TITLE
Button in ButtonGroupInput needs to show depressed state more clearly

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1716]
A button in ButtonGroupInput is showing its depressed state in an unclear way, especially on toolbars.
The issues is seen in both themes, although manifested differently.

Perhaps slight light-mode regression in v.30, but was never extremely clear in either mode.

**Comment by amcclain** [comment]
Yep, looks like a regression, with the button-active rule not being specific enough in the light theme to have `var(--xh-button-active-bg)` applied.  Should look like:

<img width="315" alt="Screen Shot 2020-02-26 at 4 45 16 AM" src="https://user-images.githubusercontent.com/225806/75332824-0a815780-5853-11ea-95af-ee5a14390a3d.png">

The dark theme is getting the correct style, but even with the active background applied it's always been tricky to read these button inputs - especially when there are only two. 

We've used a border highlight around the pressed/active button before to make it more clear that it's the one that's been selected. That could be an opt-in feature for use cases where we know there are only two options and/or it's especially critical to know which button is active.

Tom if you could please ensure the style gets applied first as an immediate fix and then maybe think on that suggestion if you have time....

**Comment by TomTirapani** [comment]
In mobile, the active state is not displayed at all in either dark theme or light theme.

**Comment by peterjcoffman** [comment]
I can easily fix this on Desktop. The selector just isn't specific enough.

In Mobile, I'm not sure how to handle this. In Mobile, it isn't the active button that's a special color. Instead the _in_active button is a special color, with the active button being the normal button color. There is a variable `--xh-button-active-bg`, but it's just the same as the normal color.

Should I add a new `--xh-button-inactive-bg`?

**Comment by TomTirapani** [comment]
Can't we override the behaviour to have the active button use a special color on mobile? Would like to be consistent with desktop if we can

**Comment by peterjcoffman** [comment]
@TomTirapani We certainly can. That might be the better approach.

**Comment by peterjcoffman** [comment]
Two possible fixes:

https://github.com/xh/hoist-react/pull/1721

https://github.com/xh/hoist-react/pull/1722

They differ in how they handle the mobile case. The first one keeps the current behavior, where inactive buttons are given a special color. The second one makes inactive buttons the default color and gives the active button a special color.
