### ISSUE TITLE
Down Caret in Select is a bit bulky

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1717]
Seems like the down caret  affordance in the Select is a bit wide, taking up precious space in crowded toolbars.  If possible would like to slim it down, giving some more room for content.

**Comment by amcclain** [comment]
Note we do have a `Select.hideDropdownIndicator` prop if you want to zap it completely (as we've done in the past)

**Comment by TomTirapani** [comment]
Took a quick go at this. Managed to reduce the width a bit, but I'm not sure how much more we can without it looking wonky. I think in practice we may be more inclined to just hide the indicator when we deem it problematic.
https://github.com/xh/hoist-react/pull/1740

**Comment by lbwexler** [comment]
I think this is a material improvement and looks better too.  Thanks
