### ISSUE TITLE
Add RefreshMode support to mobile navigator

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#1720]
When refreshing a mobile app, I would expect pages deeper in the stack to wait until they become active again to refresh. Currently, they all refresh at once.

**Comment by peterjcoffman** [comment]
Do mobile pages have a RefreshMode at all? It looks to me like RefreshMode is only used on TabContainerModel and DashContainerModel.

**Comment by TomTirapani** [comment]
No, they don't. I'm saying they should - will update the title to clarify

**Comment by TomTirapani** [comment]
PR here: https://github.com/xh/hoist-react/pull/1732
