### ISSUE TITLE
Bottom Summary Row height is not changed when sizingMode is changed

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#1745]
This can be seen on this toolbox demo page:
https://toolbox.xh.io/app/grids

**Comment by TomTirapani** [comment]
Just took a look at this - looks the the summary row height does reflect the sizing mode?

<img width="804" alt="Screenshot 2020-03-05 at 13 03 06" src="https://user-images.githubusercontent.com/3017757/75984124-bd9c2180-5ee1-11ea-9614-047d3ec62b4b.png">
<img width="795" alt="Screenshot 2020-03-05 at 13 03 19" src="https://user-images.githubusercontent.com/3017757/75984141-bffe7b80-5ee1-11ea-93df-7e02544f37e4.png">

**Comment by haynesjm42** [comment]
I think this has to do with changing the size at runtime, probably due to this: https://www.ag-grid.com/javascript-grid-row-height/#height-for-pinned-rows

**Comment by TomTirapani** [comment]
Apologies for delayed response here - did not see John's reply

Please see PR with fix: https://github.com/xh/hoist-react/pull/1783

**Comment by lbwexler** [comment]
👍
