### ISSUE TITLE
Not all components forward refs

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1755]
Grid does not forward its ref, and to make things even more complicated it already gets a ref to its outer frame for its own use. This library looks promising for dealing with assigning multiple refs to the same DOM element: https://www.npmjs.com/package/@seznam/compose-react-refs

Mobile panel is another component which does not forward refs. We need to audit all components to ensure we are forwarding appropriately.

See https://github.com/xh/hoist-react/compare/gridRef for an example of using that library for dealing with multiple refs.

**Comment by lbwexler** [comment]
This is very promising and an important piece of the puzzle.  See this discussion here:
https://github.com/facebook/react/issues/13029

**Comment by cnrudd** [comment]
@haynesjm42 the lib https://www.npmjs.com/package/@seznam/compose-react-refs is pretty cool.

**Comment by lbwexler** [comment]
We have added composeRefs to develop, so we should now have all the tools we need to work on this.

**Comment by lbwexler** [comment]
Think we are now all familiar with the composeRefs tool, which has been great to let us wrangle external and internal refs whenever we need to and was looking to close this out,

Certainly for mobile `Panel`, I think we want to do this for consistency with Desktop Panel, and it seems like a basic function of `Panel`.  I will create a PR for that now.  

But I see that for the most part,  our big signature components with corresponding Models -- Grid, DataView, DashContainer,  Form, DockContainer, Chart,FilterChooser, GroupingChooser do *not* actually pass a forwardRef to the component they use for internal rendering.

I think it would be straightforward to do this, but I just want to make sure we want to?  Is this for purpose of this to be able to get a Dom element for  aligning things to these components or scrolling to them etc without putting them in other containers.   

The reason I ask is that another option (and I know it sounds crazy) would be to somehow have the ref that is returned from these components be an imperative handle to the *model* of the component in question.  That would be another "big" way of structuring apps, that I don' think we want to introduce, but just wanted to confirm here before we preclude it.
