### ISSUE TITLE
Select should more gracefully handle dates as values in options

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1756]
If a select is set up with the following opts:
const someTimeStampThatIsToday = ts
[
{label: 'Today', value: moment(someTimeStampThatIsToday).toDate()},
{label: 'Tomorrow', value: moment(someTimeStampThatIsToday).add(1, 'days').toDate()}
]

Select is then is bound to a field with the value of moment(someTimeStampThatIsToday).toDate().
 
-----
The select will not display the 'Today' label as you might expect but rather the date toString. I think this is because the two dates may have the same value but are not == as they are different instances of Date().

Oddly if you then select the 'today' opt, the select will not respect it, because all of a sudden it seems to think the values are in fact the same and its a no op (maybe form is smart about this? guessing...).

If you select tomorrow first, then today you are back in a normal state.

**Comment by lbwexler** [comment]
Why aren't we using LocalDate here? Or if it really must be a date then how about a timestamp?  

Seems like a lot to expect select to do specialized equals comparisons for date or any other objects.

**Comment by febbraiod** [comment]
Actually now that you mention it, LocalDate might fit my needs fine. Glad to add the fix I'm suggesting here (now that I'm assigned), but it seems to me you are arguing for "won't fix" here?

**Comment by lbwexler** [comment]
Indeed -- want to make sure I wasn't missing something.  Will do so now.  If it doesn't work with LocalDate, please re-open :-)

**Comment by febbraiod** [comment]
LocalDate is working beautifully for my purposes, thanks again for the nudge!
