### ISSUE TITLE
Support setting dimensions on DockViewModel

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1773]
Currently the dimensions of DockViews are determined by their contents. 

I ran into a case where dynamically adjusting the title of a DockView caused the width of the view to exceed the width of the contents, leading to a very weird looking layout.

I believe it would be generally useful and correct to support setting dimensions via the DockViewModel for cases where you wish to explicitly size the view and ensure that sizing applies all around.

@TomTirapani I can show you on Monday or Tuesday and we can discuss if this makes sense. I also want to look @ options for ensuring dock views don't exceed the height of the viewport.

**Comment by TomTirapani** [comment]
See PRs for setting dimensions:

https://github.com/xh/hoist-react/pull/1782
https://github.com/xh/toolbox/pull/381

The part about ensuring does not exceed viewport height requires a bit more thought, given that a DockContainer is not necessarily anchored to the bottom of the viewport - it could be any container. In those cases, would we still want to constrain the viewport, or to container? Not clear if there's a straightforward way to handle these cases without observing resizes.
