### ISSUE TITLE
Update router5 to 8.x

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1792]
We are currently on 7.0.2 - looks like 8.0 was released 23 days ago, although as of today (Mar 24) the [CHANGELOG](https://github.com/router5/router5/blob/master/CHANGELOG.md) does not appear to be fully updated.  Worse, the docs on https://router5.js.org/migration/migrating-from-6.x-to-7.x have a migration link from 7 > 8 but it's just the 6 > 7 content at the moment...

Not entirely sure what the breaking changes might be, or how much of an update this represents, but worth staying on top of this core library.

**Comment by lbwexler** [comment]
Just checked and docs are still out of date.  Filed this:

https://github.com/router5/router5/issues/461

**Comment by amcclain** [comment]
Closing as we have not had any issues with or needs from Router5, and docs still remain outdated
