### ISSUE TITLE
NumberInput.rightElement prop unusable

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1803]
I wanted to use the documented `NumberInput.rightElement` prop to display a right-aligned icon (in my case, a percent sign as my input was holding a rate), but the element did not render as expected. Using a simple text string also did not render properly.

It appears as though this element was getting a zero default width. Attempting to set a width just made things worse. (To replicate, try to do something useful with this prop 😄)

**Comment by febbraiod** [comment]
Appears to be particular to icons? Was able to use a span, which while not beautiful, at least was visible:

<img width="384" alt="Screen Shot 2020-03-31 at 9 43 13 AM" src="https://user-images.githubusercontent.com/15745614/78033292-343b0c00-7334-11ea-91a1-db2d3ad7708c.png">

Top input using icon, bottom has a span.

**Comment by febbraiod** [comment]
Blueprint also recommends minimal buttons, which work as well:

<img width="368" alt="Screen Shot 2020-03-31 at 9 55 05 AM" src="https://user-images.githubusercontent.com/15745614/78036594-7c5c2d80-7338-11ea-93c9-bd7121e67608.png">

**Comment by febbraiod** [comment]
Looks like this extends to any input that tries to use an icon as its rightElement. The wrapping (bp provided) span gets a 0 width. If instead you use a button with an icon, it gets a width of 30px. Somehow the child svg does not give its parent a width. CSS based solution in the works.
