### ISSUE TITLE
useOnResize on Chart never receives DOM element for 'current'

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#1808]
Have found that there are cases (seen in current Toolbox) in which useOnResize on Chart never receives DOM element for  ref.current.  This causes the resizeObserver to never be attached to the chart.

See the Price History chart on the Portfolio app: https://toolbox-dev.xh.io/portfolio/

![ChartNotResizing](https://user-images.githubusercontent.com/2573928/77948815-f8506a00-7293-11ea-928b-47863f95207f.gif)

**Comment by haynesjm42** [comment]
@lbwexler / @TomTirapani - perhaps this is the same issue we saw in a client app? I think we intended to circle back to look into the framework hook more closely, we had put in a hook in the app which worked for the use-case we had there

**Comment by cnrudd** [comment]
I have a fix that uses a useCallback hook...
will put in a PR

**Comment by cnrudd** [comment]
Same issue exists with useOnVisibleChange.  Will put a proposal for fixing that in the PR too.
