### ISSUE TITLE
Copy Cell not working on Column based on field:'id'

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1823]
From a Client:

> When we try to use the ‘Copy Cell’ option in the context menu, instead of copying the content of the cell it copies ‘undefined’.  This happens specifically for cells belonging to a column with a ‘field’ if ‘id’.
> 
>  
> ‘Copy Cell’ works for all other columns.
> Copying the whole row also gets the values correctly.

It looks to me as if agGrid's native copy-cell implementation is not actually using the column 'getValueFn' but instead trying to pull it right out of the raw data.

This is presumably an agGrid error, but it does again the raise the question as to whether we should go ahead and insert the id directly into our record data.  That would workaround this agGrid and just generally may be what users expect.

**Comment by haynesjm42** [comment]
This is actually on us, we implement our own "Copy Cell" context menu action, which is currently just doing this: `copy(record.data[column.field]);`

We should be using the Column `getValueFn` here
