### ISSUE TITLE
Panel support for rendering an ErrorMessage in place of items

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1825]
Would be nice if we had some easy way to show a mask over a panel which indicated that an error occurred. This could be a new type of mask component or an extension of the current mask component.

Could see how this could work nicely with `Panel` and `mask: 'onLoad`, we keep track of the last request error in `LoadSupport` models now, could determine if an error occurred on the last request to show the mask and default the message to the exception message.

For instances where you want something more minimal could also support this in the panel loading indicator by having it render an error icon and showing error information in a tooltip on the indicator.

**Comment by amcclain** [comment]
Would be interesting to revisit this now that we have `ErrorMessage`.

I was writing a small new component yesterday that loads some data via its `LoadSupport` enabled model and shows the data in a grid - like so:
```
render({model}) {
        const error = model.lastLoadException;
        return panel({
            item: error
                ? errorMessage({
                      error,
                      actionButtonProps: {onClick: () => model.loadAsync()}
                  })
                : grid(),
            mask: 'onLoad'
        });
    }
```

Not bad, but unfortunate how the error case dominates the render method.  I was thinking it would be helpful if `errorMessage` had a more compact way to enable a default refresh option, which is a different ticket, but I think the idea here is worth exploring more.  I think I would prefer having the component swapped out entirely with a pre-configured `errorMessage` vs. a mask, but happy to discuss.

**Comment by amcclain** [comment]
Closing as not directly actionable as a single Hoist feature - please see comment in the PR where we tried this out - https://github.com/xh/hoist-react/pull/2568#issuecomment-892213430
