### ISSUE TITLE
ExceptionHandler only shows dialog for the last exception

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1834]
Our ExceptionHandler class will only show the alert dialog for the last exception it was given. If another exception occurs while the dialog is open, then the exception dialog will be overwritten by the last exception. This is especially problematic if you have an error alert open which requires an app reload, but something else which is less critical and not marked as an error/requiring reload occurs then it will take the place of the more critical exception message.

This _could_ be handled by app code in some/most cases, where it could catch and bubble the exceptions, but our default handling here could use some improvement. We probably want the dialog to support showing multiple exceptions, and if at least 1 of them require a reload then the dialog should force an app reload.

**Comment by lbwexler** [comment]
This was intentional -- we decided not to try to pay the complexity cost of opening multiple dialogs, and especially wanted to avoid situations where a storm of them would look very bad and make the dom unwieldy and unuable.

But certainly see where it causes real problems here.  It may be easier for us to open up multiple windows with our new dialog model.

**Comment by haynesjm42** [comment]
Yeah that makes sense - the main problem really is that I had a severe exception occur first - then a less severe one overwrote it. If I have something which requires an app reload then I don't want a less severe exception to allow the user to dismiss the dialog and get back to the app when it is in a bad state.

Perhaps there is a smaller more strategic change we can make here to address that case? ExceptionHandler could check if the dialog is already open with an exception that requires reload, and skip showing the new exception.
