### ISSUE TITLE
Research Mobx "observer batching" option

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1835]
I am updating our mobxx-react dependency to 6.2.x and the addition of "observer batching" was noted in the [changelog](https://github.com/mobxjs/mobx-react/blob/master/CHANGELOG.md#620) - see [this doc which recommends](https://github.com/mobxjs/mobx-react-lite/#observer-batching) the inclusion of a new import statement to enable.

**Comment by amcclain** [comment]
Mobx is printing a warning to the console telling us we should include the documented import to enable observer batching. I confess I don't understand the issue, but I will push an update to develop now to include the import as per the docs / warning. 

My reasoning is that it's better to test this 6.2 mobx generally in the recommended configuration. If we see any issues, we could look into them or roll back to 6.1, although note that I ran into issues with a bad 6.1.x release they published that failed to compile,

**Comment by lbwexler** [comment]
Thanks for this. Totally agree.
