### ISSUE TITLE
CubeField should have an Average aggregator and string alias

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1839]

**Comment by lbwexler** [comment]
Don -- I think you showed me you work on this -- can you submit a PR?  Let's have it follow the same null semantics (ignore nulls) as SumAggregator.

Thanks!

**Comment by febbraiod** [comment]
Yes, I've been working on it and intended to being it back into your orbit today. Think we might have reason to open a ticket to improve our aggregators in general. Set up a test in toolbox and noticed that even before my change that the test cube grid can be very slow sometimes, might want to have a look at that too. Will ping you this morning.
