### ISSUE TITLE
ag-Grid: React Component 'undefined' not created within 1000ms

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#1853]
Sometimes happened just after page load.

Had seen this error in the console enough to notice over the last week, then again in CR with Lee.  Happened once more the next day, triggering this ticket, but I didn't see it at all yesterday.
[Deleted Picture -- see Don for more info]

**Comment by lbwexler** [comment]
Closing this -- we think this has been fixed.  Can always re-open if needed.
