### ISSUE TITLE
StoreFilterField loses value on tab switch

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1854]
Note this might well be the same (but a more serious / general issue) as #1799 

To reproduce, on Toolbox - 

- Open sample grid tab
- Quick filter the grid to limit to a small set of records
- Switch to another tab
- Switch back to sample grid - grid is still filtered, but SFF is empty, leaving no obvious active filter or way to clear filter.

**Comment by lbwexler** [comment]
> We have a little bit of a tricky issue surrounding StoreFilterFields in toolbar, I wanted to make you aware of. If you have a SFF, and its in a toolbar, and your version is Hoist is 31 or greater, you may have a problem. Just want to make sure we are all aware of it, so we don’t release bugs in to production, and fix any quickly. The problem is essentially that if the tab containing your SFF is hidden and reshown, it can ‘lose’ any value it had, and get out of sync with its underlying store.
> This results from an unfortunate interaction between our new toolbar enableOverflowMenu property (blame blueprint)  and SFF’s desire to maintain state internally.
> To avoid this you can do one of the following:
> + Ensure your SFF stores its state somewhere by using the ‘bind’ property to bind its value to an observable on its model.
> + Set your enableOverflowMeny: false on your toolbar.
> I’ll be doing a combo of the above on Toolbox and our Admin App shortly, but just wanted to get this info out there.
