### ISSUE TITLE
Toolbar with enableOverflowMenu remounts children

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1860]
Toolbars with enableOverflowMenu = true will remount their children everytime they are hidden shown (e.g. via tab switching).  

This can cause problems/instability with any components that holds state locally, or have external effects at mount time.

Looks like a clear problem with the underlying Blueprint control and how it handles resize.

**Comment by amcclain** [comment]
Developers warned in e39c40e98a0ae91b151a85191b39ed0c2b00c777
