### ISSUE TITLE
Enhance Usage Tracking Panel in Admin

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1861]
+ Need to add ability to group grid, especially by user.

**Comment by lbwexler** [comment]
The first bit might be tricky, and might be more appropriate for a Hoist Core ticket -- I'll move it there.

**Comment by haynesjm42** [comment]
Thanks for adding this ticket. To add a few more details from the client request:
* Client is really looking for this to be more of a BI tool, so we likely want a Cube with a Dimension chooser to let them group/aggregate as they see fit
* Some new aggregators may be required
  * Count (set dims to User->Message and show counts of how often that user has had that message)
  * Date range (set dim to User and set a message filter, would want to see the first and last dates that user has that specific message)
* Client would also potentially like some kind of heat map to show user activity, likely synced to the grid
