### ISSUE TITLE
App Menu Clips in Portrait Mode on Mobile

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1862]
Seen in client application.

**Comment by TomTirapani** [comment]
PR here: https://github.com/xh/hoist-react/pull/1865

**Comment by amcclain** [comment]
FYI I am seeing this still with one of our client apps loaded within a secure browser - can share screenshot privately.

**Comment by TomTirapani** [comment]
It's likely this regressed when we replaced the mobile Menu implementation: https://github.com/xh/hoist-react/issues/2230

Will take a look.

**Comment by TomTirapani** [comment]
Fix here: https://github.com/xh/hoist-react/pull/2401
