### ISSUE TITLE
EmptyFlexCol takes up minimum 24px width

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#1864]
Even if there are enough columns to scroll horizontally, the `emptyFlexCol` seems to have a minimum width of 24px. Ideally, it would shrink to nothing if the columns are scrolling horizontally.

**Comment by amcclain** [comment]
I seem to recall this being some base limitation of ag-grid columns, but don't recall the details. Agree with you here for sure - this has stopped me from using emptyFlex in some small grids where I would otherwise prefer to have it there.

**Comment by lbwexler** [comment]
What does emptyFlexColumn do for us now? @amcclain @TomTirapani  ? Am I missing something?

**Comment by TomTirapani** [comment]
At this point, I don't see any need for `emptyFlexColumn`. AgGrid now fills row striping all the way through the 'empty' space, and its presence or is more likely to confuse than to help our new sizing stuff.

I vote we get rid of it as a breaking change to force devs to remove them.

**Comment by amcclain** [comment]
I did not realize that ag-grid fills the horizontal space by continuing row striping - it always does that now?
