### ISSUE TITLE
Hoist GridModel.autoSizeColumns() follow-up issues

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1877]
Some minor follow-up items from #1874:
- [x] ~~Experimental flag should be `useHoistAutoSize` with upper-s for consistency~~ - everything moved to lowercase s for even more consistency.
- [x] Apply `Column.autoSizeOptions` min/max constraints after accounting for header, padding, etc. so those are really what you get.
- [x] Support `Column.autoSizeOptions.skipHeader` flag - default false, but if true would specifically not take header into account 
- [x] ag-grid masking not visible.  This actually is important, especially on mobile and larger grids, where it can actually take a few seconds to churn through these.  Do we want to actually use our own masking here?
- [x] Review #1747 - seems like we should be able to include a sanity check while all of this is fresh in our minds - or close it out if our new approach does not have the same limitations.

**Comment by amcclain** [comment]
Wait added in ab0022d6d459015e87ee3151edd4ec0c7dd8404d for masking.

**Comment by lbwexler** [comment]
👍
