### ISSUE TITLE
TreeGrid Alignment issue in smaller sizing modes

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1878]
It seems like leaves and nodes with children that are at the same level don't align properly in 'Tiny' and 'Compact' mode.  There is some spacing there that is not being adjusted properly.   

This was seen in an important client app where we have mixed siblings some that are leaves, and some that are not.  Will send you an image at client-site and also try to get an example in toolbox.

**Comment by TomTirapani** [comment]
PR here: https://github.com/xh/hoist-react/pull/1881

In the PR I added new vars to control the expand / collapse icon width across the sizing modes, so we can ensure the leaf indentation matches.

See below for example screenshots of indentations on a mixed dataset across the 4 sizing modes:

<img width="208" alt="Tree Grid Align - Tiny" src="https://user-images.githubusercontent.com/3017757/81183426-100fc200-8fa7-11ea-8906-881429a72bd2.png">
<img width="217" alt="Tree Grid Align - Compact" src="https://user-images.githubusercontent.com/3017757/81183443-1605a300-8fa7-11ea-8c61-040786356a2f.png">
<img width="216" alt="Tree Grid Align - Standard" src="https://user-images.githubusercontent.com/3017757/81183453-19009380-8fa7-11ea-8f18-69708b106140.png">
<img width="212" alt="Tree Grid Align - Large" src="https://user-images.githubusercontent.com/3017757/81183464-1c941a80-8fa7-11ea-9aa7-bff72d0e0138.png">

**Comment by TomTirapani** [comment]
Improved pr with a different approach: https://github.com/xh/hoist-react/pull/1884
