### ISSUE TITLE
Enhancements/Fixes to autosizing

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1888]
We talked about the following general enhancements to autosizing:

-  ~Add options for distributing extra space (when there are no flex columns).  This would help a lot to avoid over-squeezing columns.  One thought  was something on the order of fillMode: 'all' | 'left' | 'right' | 'disabled'.~  
-  ~Leave room for sort affordances in headers.  I feel that it is generally quite frustrating to have the header become unreadable, just as you click on it to sort it.  We could make it an option, but generally think as a default it would be better to make room for it, which would also generally give the grid a bit more room.  Also, we should certainly leave this room if we are not space constrained overall!~
-   ~Would be very helpful (if possible) to not depend on the headers being rendered.  This is going to lead to inconsistent results when resizing hidden grids (e.g. in hidden tabs) vs. visible grids, and also limits our ability to resize consistently in various other scenarios when we don't know if the grid is rendered yet (see below).~
-  Should a GridModel have an option where it throws in an initial sizing for you when it is first initialized?  Just to get you off to the right start in your sizing configuration?  Would obviously not be used if you had existing grid state -- would just be a first time thing.

**Comment by TomTirapani** [comment]
Finding header in a pinned section was fixed yesterday: https://github.com/xh/hoist-react/commit/f5d657bc352e7b5e9226e8e469f917ed636b632a

**Comment by lbwexler** [comment]
Think we have done everything listed in this ticket!  The bit about the initialSizing is going to be handled by https://github.com/xh/hoist-react/issues/1893
