### ISSUE TITLE
Build in support for `sizingMode` to Hoist

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1889]
We would like to extend the support for GridModel.sizingMode to Hoist itself.  This will save applications from needing to wire it up to individual grids, and will also open us up to tie limited additional non-grid properties to it as well  (e.g. toolbar sizing).  In particular, the proposal is to:

+ add an observable `sizingMode` property to XH.  Should probably be implements in the same way that darkTheme is implemented.

+ GridModel should default to using that sizingMode, unless specifically instructed to use another sizingMode in its constructor. 

+ We will probably want grid models to react to changes in the global sizing mode, and make a call to autosizeColumns() when sizing mode is changed.  May or may want to defer this for hidden grids.

+ Would like to do an initial sizing for any grid when its never been sized, or has not yet been sized for the current sizingMode in-force.

[I realize the word sizingMode is a little wonky, but it seems generic enough to extend beyond Grid in the way we need it to]

**Comment by amcclain** [comment]
This would be a great thing to clean up so we can encourage wider use of grid sizing mode as an app-wide option - making it a very easy thing to turn on all around.  Right now it's quite cumbersome, with the need to setup an observable property and then (even more annoying) reactions to update all app-level GridModels.

Marking as good-first-issue - it's not necessarily simple by any means, but could serve as a nice / comprehensive intro to a number of really key concepts.

**Comment by TomTirapani** [comment]
Opened a number of PRs:

https://github.com/xh/hoist-react/pull/2593
https://github.com/xh/hoist-core/pull/205
https://github.com/xh/toolbox/pull/518

Looking forward to discussing!
