### ISSUE TITLE
Visual Tweaks to Grid Headers

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1896]
+ Sometimes it is nice to have a grid column header just be an icon, and often in that case you also want it centered, but we are always adding some left margin to svg elements in our grid headers (presumably for the sort/filter icons) so things tend to look a bit off,
Offending css here: hoist-react/cmp/grid/Grid.scss - Line 55 in 597531e

+ Would it make sense to decrease/remove the spacing between the sorting icon and the header text?  It seems that we are pretty generous with that and it becomes increasingly important in the case of reserving size for headers. 

+ Would we consider *not* eliding the text of a header, but just clipping it?  (This is especially useful for grids not reserving space for the sorter, or the entire header).  It seems like quite often the '...' take up critical space that would give you one or two letters of context to understand what the header was....

**Comment by lbwexler** [comment]
I am removing my suggestion of putting the sorter on the left -- discussed with several folks and we agreed that it is too non-standard and finicky.

**Comment by amcclain** [comment]
Routing this ticket to you @petradish as you have been looking at the header component in the context of filtering and so hoping you might have this loaded into your brain. 😄

**Comment by amcclain** [comment]
Would also like to decrease default header height values - we did this for a client app where we were optimizing usage of space and data density and there doesn't seem to be any downside

**Comment by petradish** [comment]
I'm going to look into Lee's 3 suggestions above now -- thanks Anselm for getting the change to reduce header heights in: https://github.com/xh/hoist-react/commit/103273414544518cb25f54d382624fc7816c835a
