### ISSUE TITLE
Icons in grid headers always get a left margin

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1899]
Sometimes it is nice to have a grid column header just be an icon, and often in that case you also want it centered, but we are always adding some left margin to `svg` elements in our grid headers (presumably for the sort/filter icons) so things tend to look a bit off

Offending css here: https://github.com/xh/hoist-react/blob/597531e27c59b8fc852568f716d1f0e78b032ec2/cmp/grid/Grid.scss#L55

**Comment by lbwexler** [comment]
Moving this to a single ticket for updating header styling
