### ISSUE TITLE
Convenience method for displaying a Message

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#190]
...without needing to construct a model, insert a dedicated Message component into whatever other component might wish to show one.   Instead offer a method on HoistModel (or base AppModel, or...?).

Need to determine how best to implement support for multiple callers showing Messages without stomping on each other.

Routing over to you @johnbc but of course we're happy to discuss ideas anytime!

**Comment by lbwexler** [comment]
Adding myself to this -- John I was able to make some progress on this API on the train.   Will share with you shortly, but wanted to make sure to touch base with you about this.
