### ISSUE TITLE
Update highcharts to 8.1

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1919]
This is a minor update and should be safe to take as a drop-in, but there were some upgrade notes in https://www.highcharts.com/blog/changelog/ and HC is important/complex enough it warrants a careful look.

**Comment by febbraiod** [comment]
Changelog didn't contain anything too scary. Banged on our charts in toolbox, looked ok so far. Will discuss with Colin as well

**Comment by febbraiod** [comment]
https://github.com/xh/hoist-react/tree/updateHighcharts
