### ISSUE TITLE
Issues with Fullscreen/format buttons in JsonInput

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#1922]
These buttons depend on focus on the input, but when it is disabled clicking on the input doesn't focus it. I was able to get the buttons to appear briefly by right clicking on the input in some cases.

We might consider using `editorProps: {readOnly: true}` to handling disabling a JsonInput. That makes it so you can still select text in the input and focus on it, but cannot edit the contents. Having a JsonInput that you can't select the contents of is usually pretty frustrating and not what you would expect to happen.

**Comment by lbwexler** [comment]
Thanks for filing this John -- I have an additional concern I wanted to bring up -- when you have a big chunk of json on the first line --- and you really need these buttons to wrangle it -- you cannot actually see the buttons.

Wonder if they would be better in the bottom *right* corner, at the very least,

**Comment by haynesjm42** [comment]
The fact that the buttons cover the contents may be annoying in some cases also, as it could make it difficult to read the json. Not sure where we could put them to avoid that completely without introducing a toolbar, on the bottom-right might be less of an issue, but still possible they would cover data that the user wants to see. Could always move them into a context menu - in that case the auto-format would be consistent with our grid auto-size context menu

**Comment by lbwexler** [comment]
bottom right is rarely going to be a problem, no?  If the json not formatted its going to be all on the top-line, otherwise the last line should be a single character, no?

**Comment by lbwexler** [comment]
I guess it depends on scrolling, but I will say that having it not on the first is the main problem, I think.

**Comment by haynesjm42** [comment]
If you are scrolled all the way to bottom, yes. Putting them on the bottom should make it much less likely to be an issue and is probably sufficient for now
