### ISSUE TITLE
Headers not rendered correctly when grid has flex column with MaxWidth

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1928]
See our main toolbox grid example, currently configured with a "company" column that is flexing.
`{field: 'company', flex: true,  maxWidth: 350, ..}`.  Open it up with a nice window where it has more space than it needs.

This causes problems on the right hand -side with the header row, where it appears some kind of  flex header is occluding the headers on the right-hand side.  This is only a problem if the grid has *more* width than it needs when instantiated, and will go away by moving columns or other manipulations

This is almost certainly an ag-Grid bug that is now exposed by our lack of `emptyFlexCol`.
+ Body of grid is fine, only a problem with headers.
+ Things work great with either no flex column, or a flex without a maxWidth.
+ This is a regression, not visible in the released version of toolbox with hr v33.3.0

**Hopefully we do not have to bring back in `emptyFlexCol`, but I fear we might**

**Comment by lbwexler** [comment]
Probably worth trying 23.1.0 to see if that fixes it, but I am not too hopeful -- no obvious mention of it in the changelog.

**Comment by TomTirapani** [comment]
FYI, it seems they are aware of this issue: https://github.com/ag-grid/ag-grid/issues/3845
