### ISSUE TITLE
GridModel.ensureSelectionVisible() should try again, if grid data not immediately available

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1937]
A common issue with `GridModel.ensureSelectionVisible()` occurs when it is called with a record immediately after that record has been added to the grid's store - rec could be new, filter could have just been cleared, etc.

In that case, no row node has been assigned and the method can't do its job.  I just pushed 5480b04905ce9cf1f1945055bbe26b6c7701faf0 to avoid throwing, but if we were willing to make this method async, we could wait one tick if we detected missing records and attempt a go-round.

We could discuss if we want to rename the method as per our standard and make it a breaking change. But since it has no return and since it involves manipulating the scrolling state, I actually think it would be rare that any caller would await or otherwise use the returned promise, so we could consider an exception to our naming rule and leave the name as-is.

**Comment by lbwexler** [comment]
I wonder if there is a way we could generally add a new async method that would just resolve only when the grid -- eg.  ensureGridDataReadyAsync() -- might be generally useful for the implementation of this, of for applications to use directly.

I like the idea of having this thing quietly wait a tick and retrying.  Seems harmless and potentially useful.
