### ISSUE TITLE
Admin Activity Tab - follow-up improvements

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1943]
Hi - here are some suggestions from me re. the newly upgraded Activity tab - looking good, will be great to push a bit farther this week.

### Grid
- [x] Make Track + Username columns wider
- [x] Rename Day > "Day / Range" - the range is pretty heavyweight in terms of how long the field gets / how wide the col needs to be, but it does seem like it might be useful...
- [x] Rename Avg Elapsed (ms) -> Elapsed (ms) to get header to fit, drop commas from number format
- [x] Hide Impersonating and Data columns by default
- [x] Consider adding small detail panel showing all fields of selected row instead of needing to go into (somewhat bad looking) modal.
- [x] Expand tree row on double-click (I still expect tree grids to always do this)
- [x] Make sure (default hidden) 'data' and 'message' both have an autosizeMax (Activity)
- [x] Make sure 'error' has an autosizeMax (Client Error)

### Query
- [x] Make default grouping Date > User > Category > Message
- [x] Query start date should go back one month by default (unless we find that's too slow, would hope not)
- [x] Reset query button should reset all fields and be to the right of all of them.
- [x] Maybe remove refresh button. We have app-level refresh in top toolbar, but I see how some users might want it to ensure query update is run (vs. pressing enter key)

### Chart
- [x] Use ButtonGroup (instead of tabs) to switch chart type between Bar & Line
- [x] Use Checkboxes or switches to control which series on chart - entries, unique users, average elapsed. Any combo could be shown, first two could share a Y axis.
- [x] Could tie the series on/off controls to the plotline color w/a colored dot or square next to label, avoiding need for chart legend.
- [x] Drop X axis label "Days"

**Comment by lbwexler** [comment]
Like all of these changes.  Need to make sure (default hidden) 'data'  and 'message' both have an autosizeMax too!

**Comment by febbraiod** [comment]
Like the idea of a small detail panel, but think we'll want to keep the dialog as the data column can have a lot in it, and the jsonEditor in the dialog seems like the best way to display it to me. I guess we'll see.

**Comment by febbraiod** [comment]
Not sure about sharing axes here. Users and Logs for example could have a wide difference (other slices might be even worse)

<img width="1680" alt="Screen Shot 2020-06-08 at 12 21 09 PM" src="https://user-images.githubusercontent.com/15745614/84055360-b7a35a00-a982-11ea-83e0-d095374b4cb9.png">

**Comment by amcclain** [comment]
Let's not worry about any detail panel for now - or to put it another way, let's come back to that idea once we're happy with everything else.  (I was thinking if we did have a detail panel it could have a scrollable, readonly JSON input within it.)

I certainly see your point re. the axes. I would need to play with it a bit with real data to get a better feel for it, but I totally agree that the scale of entries vs. unique users will often be very different.  For me that might be more of an encouragement to the user to only check one at a time - seems like there is a tradeoff between having the multiple scales / Y axes to visually process vs. having a single "count" Y axis that would often force the unique users down to a very "short" series if shown alongside the all entries count.  Happy to have it setup as above for now.

One small nit - can you remove the label "histogram" - I am not sure if this would really be considered a histogram - it's a timeseries in both cases, just a bar chart vs. line chart.  You could try skipping the text labels on the buttons altogether - it should be pretty clear what they do.

**Comment by febbraiod** [comment]
Already coded up the detail panel so we might as well look at it. (Just have a couple more todos in the code to look at, but will push today)

Removing the labels on the chart buttons is a good idea, but just to be clear, it's not always a timeseries. The x-axis is determined by the dims in the grid above. If the first Dim isn't 'Date" it's a category chart.

**Comment by amcclain** [comment]
Sorry meant just bar vs. line then
