### ISSUE TITLE
ContextMenu occluded in Grid shown in Dialog

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#1944]
See Toolbox DockContainer example with Grid.  Maximize it in a Dialog and see that the context menu is no longer visible.

**Comment by lbwexler** [comment]
Interesting that GitHub says that the linked PR will close it.  Annoying!  I *think* Petra is indicating that the merged PR caused the problem!  Is that right petra?

**Comment by TomTirapani** [comment]
Fixed in PR here: https://github.com/xh/hoist-react/pull/1947
