### ISSUE TITLE
Support bulk actions on Admin configs + prefs

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2000]
I would like to support the following two actions as context-menu options on the Configs, Prefs, and User Prefs admin grids:

- Delete - will delete all selected entries, with a prompt of course.
- Set Group - will prompt user to enter a new group, and re-categorize all selected records accordingly (this one N/A for User Prefs)

I realize this might get into some work on RestGrid - notably for the delete option - although I would be in favor of supporting this as a custom action in these admin grids if that meant we avoided blocking on a larger change. I think it's worth it to allow us to better clean up and maintain these records, which we have identified as a priority for us across our apps.

**Comment by febbraiod** [comment]
Im going to take a look at this, looking for something to work on that wont require a terrific (or any) internet connection

**Comment by amcclain** [comment]
Thanks, Don - I think that's a great call.  This would be a useful feature, and help encourage the cleanup of outdated entries.

**Comment by lbwexler** [comment]
Deletion bit completed.
