### ISSUE TITLE
Some string values can cause URIError: URI malformed error when using  tooltipElement propery in grid column.

### ISSUE THREAD

**Issue by johnbc** [xh/hoist-react#2006]
For example, a column like 
```
{
                field: 'UserComment',
                headerName: 'User Comments',
                width: 200,
                tooltipElement:  (v)=>  div({style: {width: '400px', border: '1px outset grey', padding: '5px'}, item: v })
}
```

Will throw a **URIError: URI malformed** error while trying to activate the tooltip if the tooltip value contains a % sign.

This issue appears to be related to the usage of decodeURIComponent(value) this line in Columns.js

https://github.com/xh/hoist-react/blob/9a0537450cf7d99fd56b21760502585e6e1faf37/cmp/grid/columns/Column.js#L387

I'm not clear on the exact flow here, but potentially passing escape(value) instead of the raw value will fix the issue.

**Comment by lbwexler** [comment]
John - saw that you added this code in December, including a very specific comment about the encoding/decoding.  Can you take a look.  

Would we be better off passing our tooltipElement function the raw value to be rendered?  We can get it, using the record, which we have, and the value getter.  

Is the concern for grouped rows for which we have no record?  Not sure there is an expectation to get a tooltip on those.
