### ISSUE TITLE
Blueprint throwing console warning re. numberInput

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2018]
Seeing this console warning repeated multiple times in a client app - I expect it's pretty common:

```
numericInput.js:262 [Blueprint] <NumericInput> controlled value prop does not adhere to stepSize, min, and/or max constraints.
```

Not breaking anything AFAIK, but would like to understand and squelch if we can as it clutters up the console and indicates that _something_ is not as Blueprint expects.

**Comment by lbwexler** [comment]
I am looking at this -- needed a small ticket that hopefully does not require much of an internet connection

**Comment by amcclain** [comment]
@lbwexler curious if you had any luck with it?  Annoying spam on the console for sure.  I was getting motivated to look myself to stop it but didn't want to trip over you.

**Comment by lbwexler** [comment]
thanks for assigning me -- will look further

**Comment by lbwexler** [comment]
Weird -- I am actually seeing this now when I just use the decimal place, with what looks like a full console trace -- but *only* seeing this thing at dev time on my local machine, and not on the deployed version on the dev server

**Comment by lbwexler** [comment]
And furthermore, really have no idea how to squelch it

**Comment by lbwexler** [comment]
Took another look -- no change in the situation here -- still trivial to reproduce locally, can't reproduce deployed, and no idea how to squelch

Type 0.5 in `NumberInput1` in the Toolbox forms example on your local machine to reproduce.

**Comment by amcclain** [comment]
Moving to backlog to keep track of this - can also revisit with BP4
