### ISSUE TITLE
Column headers should show full text in title tip when elided

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2027]
If no specific tooltip is configured for a grid column header, and if the header text is elided due to it being longer than the column is wide, it would be a usability win if the full header text was automatically made available in a title tip on hover.

**Comment by cnrudd** [comment]
Here is a good starting point on how one might implement this: https://stackoverflow.com/a/52930448/1893251
And a good discussion about other approaches in that same SO article.
