### ISSUE TITLE
FilterChooser - enhancements

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2043]
## ✅  Confirmed / Spec Clear
- [x] Make `FilterChooserModel.store` as intended optional, `FilterFieldSpec.field` not required to be Store field. Will support app-level observer specifying and splitting off fields for e.g. server-side queries. 
- [ ] Allow `FilterFieldSpec.values` to be specified as a callback, work out API as to when it would be called to refresh values and where refreshed values would live (e.g. what is immutable?).  
- [x] One a query field and operator have been entered into a partially-completed query, the autocomplete should no longer suggest matches from other query fields. E.g. here I only want to see suggested "Instrument" values" 

<img width="331" alt="Screen Shot 2020-08-20 at 9 26 23 AM" src="https://user-images.githubusercontent.com/225806/90775838-558e9b80-e2c7-11ea-929e-0e56ce4bdcf1.png">

- [x] Change numerical comparisons (specifically `<`) to exclude `null` values. This matches Excel col filters, where val<100 returns only rows with val completed. PR #2051
- [ ] For Boolean fields, FilterChooser could autocomplete to `is true` and `is false` instead of needing to type `= true` which feels wonky. (If we implement the `is empty` suggestion below, I don't _think_ we have much need for FilterChooser to support the `!=` operator on booleans.) 
- [x] For all types, FilterChooser could support an autocomplete suggestion of `is empty` or `is unset` that would translate to a filter of ` = null`. We could discuss, but that filter could be evaluated loosely to be true for empty string values. This would be opt-in at the fieldSpec level, as many fields will never have empty values. Should also support is not empty. Need to discuss how to specify this in a filterFIeldSpec.
- [ ] Reconsider when to use filtered vs. all records for value suggestions. Working with the new filters in the context of a real app, against a simple store/grid datasource, I realize it might be most useful to use the filtered recordset to suggest values for a *new* field not yet in the query but use the complete recordset to suggest values for fields *already* in the query. This might result in a better balance of being able to expand your query (by adding new OR values to an existing field) without getting suggestions that will result in zero hits (by adding AND values for a new field where we know those values are not in the already-filtered results). 
- [ ] Support `id` as valid filter field (without requiring workaround to copy ID into another field and use that.) 
- [ ] Add support for "Height" related properties, to allow it to easily specify it as a multi-line control, and have it behave well.
 
## 🐞 Bugs

- [x] Typing `\` into FilterChooser throws with `Invalid regular expression: /\/: \ at end of pattern` 

## ⚙️  API Design / Discussion Required

- [ ] Improve default parsing for Dates and LocalDates.  See 70683b02551b0be5740709a86315d4e98afa19fc for a partial patch to this issue with TODO suggestion on making a more tolerant version of `parseFieldValue`. 
- [ ] Support `FieldType.ARRAY` with a `contains` operator - we have some use cases where Records have array values and it would be great to search inside of them (think of tags or user roles). You could workaround now with `like` and a concatenated string-copy of the value, but that feels non-intuitive to the user and would not be fully reliable out of the box unless you did something special with parsing and separators. (To file in distinct data ticket)
- [x] Option on `FilterChooserModel` to auto-apply selected filters to the configured store, instead of requiring reaction to be setup by developer to relay its changing value to the store. TWO STORES
- [ ] Allow Editable Tags 
- [ ] Compress multiple values on single field (OK, if only in favorites, group/sort fields)
- [ ] Consider filterChooser-level option to switch between an overall boolean mode of AUTO vs OR, where AUTO is our current field-aware handling and OR would allow matches to be added across fields.  This was the client request re. fields such as portfolio + subPortfolio.
- [ ] When chooser is in single line mode (e.g. in a toolbar, where it often lives) and more filters are active than can fit, the control scrolls but in a very non-obvious way - all you get is a tiny / difficult to manipulate square thumb in the input to indicate that there are more active options below. A better implementation might be to have the filter tags shrink and elide internally if needed - at an extreme they might become strange little squares themselves, but at least they would remain visible in some form (and could have tooltips). Note scrolling is much more OK in use cases where we are setting a height to make the entire input multi-line - in that case, the scroller is more obvious and usable.

## ✨ WIsh List

- [ ] Consider feature to allow user to turn on/off value persistence on demand. I am using the filter at dev-time to assist with coding up other features and finding myself toggling on persistValue in the code as it can be very convenient to keep across reloads, but I am wary of making this the (mandatory) behavior, as showing a grid of data such as transactions in a filtered-from-the-start state still seems too risky for many use cases.

**Comment by lbwexler** [comment]
Marking as "fixed" those items that are in the current refactor PR OR develop.

**Comment by petradish** [comment]
Related to scrolling, it would be nice to allow the developer to specify the menu maxHeight in rsOptions with the default being 'unset', or calculated based on the maxResults specified in the config.

**Comment by petradish** [comment]
+ [ ] Support for maxResults to show all results (maxResults: -1)

**Comment by petradish** [comment]
- [] 'auto' menu placement config is incompatible with filterChooser when it has a height set. It seems like the menu can't immediately find a reference to the top or bottom position of the input (if I click away it will react and readjust its reference), so depending on the maxMenuHeight, the menu could cover the input itself or overflow off screen.

**Comment by amcclain** [comment]
@TomTirapani and @petradish do you recall why we have the default maxMenuHeight set to `unset` ?  It was a deliberate choice, but I don't know when we would want an entirely unconstrained maxHeight. Was there a reason for it?

I pushed 8200218dc40ff825127d9ee6f3686a9641b46f8f which updates the default to `50vh` - half the viewport height. This is paired with an increase in the maxResults so we aren't truncating quite so aggressively. Please give a shout if you think this will cause any issues so we can discuss further, thanks!

(Also - note that you won't see the "displaying x of y results" truncation warning until we merge #2193 - just in case you check this out and are confused by that, as I was.)

**Comment by amcclain** [comment]
> * [ ]  Support for maxResults to show all results (maxResults: -1)
>   ^ This actually already works, but would be good to update the Docs and remind the user to specify a maxMenuHeight in the component so that the results will be visible + scroll (vs. unset height)

Was there a use case to not cap results at all? Note that because we are using the async (`queryFn`) feature of the underlying Select component, we can't use the "windowed mode" select variant with intelligent rendering of the option DOM nodes. This means that a very long list of hits will cause a lot of DOM rendering and create a noticeable slowdown. I don't mind that -1 works, that much, but in general I wouldn't want to encourage users to go with that setting. Better to set a "high" limit - whatever that means in the context of the app - and ensure that performance remains reasonable when we get close to that.

(Unless of course there is a reason for ensuring we never truncate in some use case, which would be great to review.)

The other note about encouragement to set `maxMenuHeight` is handled by the above, assuming that change I pushed is acceptable in general.

**Comment by petradish** [comment]
I think it makes sense that the maxMenuHeight is set to 50vh by default. The need for maxResults: -1 has passed in my app...and yes it was very slow to render!

**Comment by amcclain** [comment]
Closing this old umbrella ticket
