### ISSUE TITLE
FormField and Checkbox labelAlign prop inconsistency

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2045]
Both FormField and Checkbox have a `labelAlign` prop, but they do very different things and could use some disambiguation.

On FormField `labelAlign` is used for the text alignment, while on Checkbox it is used to determine which side of the checkbox input control the label will appear.

We might consider change one or both of the these props to make their effects more clear.

`labelTextAlign` on FormField? 

`labelSide` on Checkbox?

**Comment by lbwexler** [comment]
Looks like we have this issue for SwitchInput/RadioInput as well.  

I like adding 'labelSide' and deprecating/removing 'labelAlign' for the controls.

**Comment by amcclain** [comment]
👍   Proposed `labelSide` prop more clear to me for sure.  This one always gets me, for some reason.

Potential complication - both props could have a valid meaning for the checkbox/switch use cases, eh?

```
TheLabel        [ ]  // ls:left, la:left
       TheLabel [ ]  // ls:left, la:right
[ ] TheLabel         // ls:right, la:left
[ ]        TheLabel  // ls:right, la:right
```

🤔🤔🤔

**Comment by amcclain** [comment]
Maybe an argument for going with `labelTextAlign` as well, as verbose as that prop name is.

Thinking some more, it might be this exact issue that's confused me in the past, where I wanted to set the textAlign for a checkbox label, but unintentionally switched the side.
