### ISSUE TITLE
Select in 'multi' mode should allow sortable values

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2052]
Have a client use case where the order of the values matter. Not sure whether this sort-ability should turned on by default but sort-ability should at least be available. Example from React Select docs:

https://react-select.com/advanced#sortable-multiselect

Won't be as easy as adding a flag, as there is a wrapper component involved.

**Comment by lbwexler** [comment]
Don -- does the user need to manipulate the ordering with drag and drop?  Or does the programmer just need to be able to specify the order programmatically?

**Comment by febbraiod** [comment]
User drag and drop

**Comment by lbwexler** [comment]
Suggest closing this for now, if we have found an adequate workaround for client.  Our select component already groaning under the weight of all of its features

**Comment by lbwexler** [comment]
Don confirms we are using a drag and drop approach with a full grid that is working better in the client app in question.  Closing, as discussed.
