### ISSUE TITLE
FieldModel should allow for a customized setter

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2053]
Binding a HoistInput to a model allows you to create a setter that will allow the model to intervene and set the value based on whatever criteria is desired. However if using an input to bind to a formField you lose this ability. The FieldModel's setter just handles the simple case:

`this.value = v`

It would be useful to be able to intervene there, either in control, or form field.

**Comment by amcclain** [comment]
@febbraiod we are looking at this ticket and trying to determine if the extra complexity is worth it here - can you provide a general example that highlights why we would need this?  Or have you worked around and moved on, meaning we can close the issue?

**Comment by febbraiod** [comment]
Im sure I worked around in some acceptable manner given the age of this ticket. I will see if I can maybe figure out what I was working on at the time I filed this ticket and try to come up with an example so we assess if the use case makes it worth it.

**Comment by febbraiod** [comment]
Workaround is:

`this.formModel.fields.myField.setValue = myCustomSetter`

Which I suppose is fine. Since apparently the need to do this has never come up in any other app we could just close this ticket and move on. 

However, I would argue that the API would benefit here by becoming symmetrical with the binding behavior of HoistInputs. Not sure that the change is really all that complex. The field could take a setValue config and do exactly what the code above does in it's constructor.

**Comment by febbraiod** [comment]
Example:

https://github.com/xh/hoist-react/pull/2478
https://github.com/xh/toolbox/pull/488

**Comment by amcclain** [comment]
I think I just came across a use-case for this, where I need to edit a rate (percentage) value in a formField numberInput.

The raw rate that would be init'd into the formModel field + what we want to get out via getData() is scaled such that 0.5 == 50%. I want the user to see/type "50" into the numberInput and have that translate to 0.5 as the field value.

I can translate when initializing data and then translate again when getting data out, but that complexifies the app code.

(Perhaps another solution to _this_ particular issue would be if we had a `scaleFactor` or `multiplier` prop on `numberInput`....)
