### ISSUE TITLE
Returning null from a column's tooltip func will break the tooltip on subsequent loads

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2058]
Example branch in toolbox:

https://github.com/xh/toolbox/tree/nullTooltipBreaksNextLoad

To repro:

load sample grid, all citys will be set to New York, which will produce a null tooltip.
Refresh the tab to reload the grid, the city data is set back to normal, but the tooltip will no longer work.

If I'm not mistaken the tooltip function runs after the second load and does return the proper string, but we do not see the tooltip render it.

**Comment by lbwexler** [comment]
So this is actually the same as the following ag-Grid bug, which has a pending fix and PR.

https://github.com/ag-grid/ag-grid/issues/4039

If we don't wish to wait for this, we could always use the tooltipComponentFramework API internally.  Just need to come up with some sensible defaults, as simply a tooltipElement function that returns a string does not render well and needs styling

Arguably we need to improve those defaults anyway

**Comment by lbwexler** [comment]
So our friend Gil at ag-Grid reporting this is fixed and merged -- not sure when it will get released, but something for us to keep an eye on.
