### ISSUE TITLE
Remove use of inline pre-flight browser check script

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2062]
As per CSP (content security policy) we want to avoid inline scripts such as the one we embed in:

https://github.com/xh/hoist-react/blob/98a703a3b3bd76075c79551c48f98935b4682436/static/index.html

Having this in place requires us to use the `'unsafe-inline'` option within CSP header `script-src` directives. 

We should package this as a standalone file within static and ensure that dev-utils handles appropriately.

**Comment by TomTirapani** [comment]
I've moved the inline script into a standalone file, which is imported into each app bundle by hoist-dev-utils:
https://github.com/xh/hoist-react/pull/2063
https://github.com/xh/hoist-dev-utils/pull/27
