### ISSUE TITLE
Add commitOnChange functionality to ColChooser

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2084]
ColChooserButton's popover commits changes and omits the 'Save' button that exists in the ColChooserDialog implementation. We should give the popover an option to not commit on change and render the 'Save' button.

**Comment by haynesjm42** [comment]
While we are enhancing the col chooser could we also make a couple of usability improvements?
* Allow the size of the col chooser to be configurable (helpful when dealing with many columns)
* Provide a means of adding an entire chooser group in 1 click (perhaps just a button on the group row?)

**Comment by petradish** [comment]
I like those ideas! Maybe for the group, we can select all rows by clicking the group row?
