### ISSUE TITLE
Displayed value in Select input does not re-render if the value changes while Select is focused

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2095]
When a select input has a value in it (a selection has been made) and the select input is focused, if the value of the select is changed programmatically,  the displayed/rendered value of the select is not changed while the select is focused.

**Comment by lbwexler** [comment]
Colin -- I am unable to reproduce this in toolbox.  Can you put together a test case? I tried this to automatically change the value on a timer, and then focused the select box manually.  

Add the following constructor to InputsPanelModel:

 constructor() {
        wait(5000).then(() => {
            this.formModel.setValues({option1: 'MA'});
        })
    }

**Comment by cnrudd** [comment]
@lbwexler Ok, sorry, I realize I forgot to add that `enableFilter:true` needs to be set on the select component for the issue to happen.
This branch in toolbox: https://github.com/xh/toolbox/tree/selectIsFocused
has your constructor and `enableFilter:true` set on option1 and the issue is reproducible.

**Comment by lbwexler** [comment]
OK -- so this is a pretty clear consequence of the complexity we implemented to handle this:

https://github.com/xh/hoist-react/issues/880
