### ISSUE TITLE
ExceptionDialog closes instantly when it is open after hitting "Enter" key on TextInput that throws an error

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2096]
Noticed in a client app that when this sequence happens:
1 Hit "Enter" on a formless TextInput to commit a value
2 A reaction to the value change makes an ajax call that returns with an error
3 And opens an ExceptionDialog via .catchDefault()

The ExceptionDialog opens with the "Close" button autofocused, and the "Enter" key event is bubbling up/propagating
and activates the Close button so that the dialog closes instantly.

To the user/developer, this may look like the dialog:
1.  never opens
2. or flashes open and closes in an instant

I looked into solutions involving ev.preventDefault(), ev.stopPropagation(), ev.nativeEvent.preventDefault(), ev.nativeEvent.stopPropagation(), ev.nativeEvent.stopImmediatePropagation() on onKeyDown and onKeyPress on the TextInput component - in hoist-react  and in the app.    Nothing stopped the event bubbling in time to let the dialog render AFTER the bubbling had been stopped.

I ended up fixing this by delaying the ajax call with wait(500).  Could optimize that fix further by delaying the promise resolution only if an error is returned.   

But, of course this is something that would be better addressed with event management on textInput (doesn't seem possible)  or maybe delaying the autofocus on the dialog close button.

**Comment by cnrudd** [comment]
I think another possible fix that I prefer over the others is to add a check in the ExceptionDialog's close btn onClick handler to see if the ev.target value is the close button.  If it is not, ignore the event and do not close the dialog.   That seems like a clean solution if it works.

**Comment by cnrudd** [comment]
The ev.target idea did not work.  By the time the event triggers the close button click, the target is always the close button, whether the event started at the textInput, or at the close button.

**Comment by lbwexler** [comment]
Potential good news!  It sounds to me like this might be fixed by react-17

https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation

**Comment by lbwexler** [comment]
Before I forget, want to say that I saw this error in a client app with a hotkey that brings up a dialog, being input right in to that dialog's default text.  A slight delay fixed the issue, but it remains very surprising and ugly for app developers to have to work around in this way

**Comment by cnrudd** [comment]
@lbwexler I tested this toolbox branch: https://github.com/xh/toolbox/compare/exceptionDialogFocusDelay against Hoist-React with React v17 and I do not see that this issue is resolved.  (the branch name is a bit of a misnomer now, the branch doesn't do any delaying, it just sets up the bug)

React's moving of the native listener from document node to react root node doesn't seem like it changes the setup for this issue's situation: 2 enter/click listeners within the same listening parent node.

**Comment by lbwexler** [comment]
yea, thanks for testing Colin.

Sorry for the false hopes there.
