### ISSUE TITLE
Make TabContainerModel more dynamic

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2111]
TabContainerModel's tabs are currently static and not observable, but it would be great to add methods to add and remove tabs (with an x button to close in the component), and even to reorder them by dragging, similar to how tabs are managed in DashContainer.

**Comment by lbwexler** [comment]
Am closing this -- we have the core API of this in. including some nice cleanups to how we handle an empty container.  We (no longer introduce a dummy tab).  Will add a different ticket for additional issues.
