### ISSUE TITLE
Highlight application code line in log-viewer's stack dumps.

### ISSUE THREAD

**Issue by johnbc** [xh/hoist-react#2112]
Currently we can use the the handy log view to examine stack dumps when the grails application throws an error. Often the stack dump includes many lines from hoist, and library code. These lines can obscure the relevant lines from the application. It would be handy to have the lines from the application highlighted in some way.

For example, here I have made the "clientappname" bold.

31157: at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
31158: at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1247)
31159: at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
31160: at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
31161: at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:338)
31162: at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:269)
31163: at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
31164: at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
31165: at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
31166: at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2877)
31167: at io.xh.hoist.json.JSONParser.parseArray(JSONParser.java:46)
**31168: at com.cust.clientappname.dodahQuery.formatForJSON(AdhocQuery.groovy:39)**
31169: at io.xh.hoist.json.serializer.JSONFormatSerializer.serialize(JSONFormatSerializer.java:29)
31170: at io.xh.hoist.json.serializer.JSONFormatSerializer.serialize(JSONFormatSerializer.java:17)
31171: at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
31172: at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3697)
31173: at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3073)
31174: at io.xh.hoist.json.JSONSerializer.serialize(JSONSerializer.java:58)
31175: at io.xh.hoist.BaseController.renderJSON(BaseController.groovy:28)
**31176: at com.cust.clientappname.dodahLookupController.search(CompanyLookupController.groovy:13**)
31177: at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
31178: at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
31179: at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
31180: at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
31181: at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
31182: at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
31183: at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
31184: at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
31185: at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
31186: at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
31187: at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
31188: at io.xh.hoist.security.HoistSecurityFilter.doFilter(HoistSecurityFilter.groovy:27)
31189: at com.cust.web.security.FlexChain.doFilter(FlexChain.groovy:26)
31190: at jespa.http.HttpSecurityService.doFilter(HttpSecurityService.java:1596)
31191: at com.cust.web.security.JespaService.doFilter(JespaService.groovy:45)
31192: at com.cust.web.security.JespaFilter.doFilter(JespaFilter.groovy:16)
31193: at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130)
31194: at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
31195: at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105)
31196: at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123)
31197: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
31198: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
31199: at java.lang.Thread.run(Thread.java:748)

**Comment by lbwexler** [comment]
This is a very nice idea, but am closing this -- we have made a strategic decision not to invest too much more time in our log viewer.  Our enterprise customers are using dedicated log viewers for in-depth analysis of logs.
