### ISSUE TITLE
TabContainer Improvements to better support dynamic tab

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2117]
With the addition of Dynamic Tabs we have the following issues:  1 is the low-hanging fruit. I think dealing with 2 and 3 might require removing the last vestiges of blueprint from our implementation.  

1) Provide a built-in ability to provide a remove affordance on tabs.  See https://github.com/xh/hoist-react/pull/2116 for a possible solution.

2) Need to rethink what we do with overflow and scrolling or compressing tabs.   Blueprint by default is pretty dumb about this and just clips the tab selectors that are not visible.  This relates not just to dynamic tabs of course, so we need to be careful

3) Should we provide an affordance to re-order the tabs.  Probably overkill.

**Comment by TomTirapani** [comment]
For number 2, we could consider adding 'scrolling' functionality e.g. https://examples.sencha.com/extjs/7.3.0/examples/kitchensink/?modern#toolbar-overflow

**Comment by TomTirapani** [comment]
1) Has been completed and merged vis https://github.com/xh/hoist-react/pull/2116
