### ISSUE TITLE
Support an always read-only variant of FormField

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2122]
Forms often have some static data that is not (and will never be) edited by a user, but which is helpful to display inline with or alongside other, editable form fields and to maintain in the same backing FormModel.

To accomplish this now you must:
* Set your FormModel field to `readonly: true`
* Ensure your bound `formField` has an appropriate `readonlyRenderer`, if the very basic defaults don't work.
* Pass a stub input of _some kind_ to the `item` config of your FormField, as it requires that it be given a single HoistInput child. Even if you know you will never be rendering that input because nothing in the code will be changing that readonly flag.

The last step is really the silly one, although we could also do more work on the default readonly rendering (see #1845).

One way this might be clarified is via a `ReadonlyFormField` or `DisplayFormField` component that would:
* Still take a fieldName for binding to a FormModel, but never allow editing.
* Take a `renderer` prop but *not* allow any child/children (i.e. you never configure an input).
* Still respect `form.fieldDefaults` - but only applicable ones

~We should consider however if there is really an even more general component here - one that can be bound to a Model (really just `{}`), `FormModel`, or a `Record` and provide the standard styling / layout for label/value pair that plays nicely with editable forms but also would be usable standalone.  If bound to either a form or a record it could default its label from the associated Form/Store `Field`, but could be passed it directly as well if bound to a generic model property.~

**Comment by TomTirapani** [comment]
> We should consider however if there is really an even more general component here - one that can be bound to a Model (really just {}), FormModel, or a Record and provide the standard styling / layout for label/value pair that plays nicely with editable forms but also would be usable standalone. If bound to either a form or a record it could default its label from the associated Form/Store Field, but could be passed it directly as well if bound to a generic model property.

I think this is a really important consideration - without the ability to toggle to an input, this is really a label / value renderer and there's no need to tie it closely to Forms and FormModels. On mobile at least, we regularly make use of 'Record Views' (lists of labels / value pairs) that could benefit from such a component.

**Comment by amcclain** [comment]
Striking the more general use case idea simply to keep this issue more focused on the forms package.
