### ISSUE TITLE
Button css class bp3-active ignored

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2129]
The latest button css refactor causes buttons that are set to `active` by prop, and rendered as:
```
<button type="button" class="bp3-button bp3-active xh-button xh-button--enabled xh-button--intent-none xh-button--standard" >....</button>
```
to not show as active because the new class rules override the bp3-active class rule:
![image](https://user-images.githubusercontent.com/2573928/95998028-70324c00-0e02-11eb-9489-4ad277091956.png)

Blueprint button lets a button be programmatically set to active:
https://blueprintjs.com/docs/#core/components/button
which can be useful.

In my case I have row of buttons acting as tabs, so the 'active' state represents which tab is active.  I am using a custom tab bar with buttons because the tabs are draggable - they can be re-ordered or moved to other views.

**Comment by amcclain** [comment]
As discussed in Slack:
- We should look for that active prop and apply an xh-button--active class for consistency with our other state-related classes.  I’d like to keep our CSS rules as focused as possible on xh- classes, to minimize our ties to a particular library implementation / CSS changes.
- Seems like we will want two or more CSS vars for active buttons to set background color and box shadow, then we could key off that active class with a more specific selector to add them.  I don’t know how/if these need to work with intents or standard vs. minimal - my guess is that we can leave intents out of it, but it might well be the case that for minimal buttons we want them to be able to appear active without necessarily having a box-shadow.  Could see what BP does.
