### ISSUE TITLE
Nice to have:  app-wide timeout setting on fetchService

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2135]
It would be very handy if there were an app wide way to set the fetchService timeout value.
Something similar to how fetch default headers can be set app wide.

**Comment by lbwexler** [comment]
Agree this seems logical -- one question is whether we would want this to apply to internal hoist fetch usages, or whether we would look to hardcode values that we see as appropriate for hoist calls (e.g. prefs, tracking, initialization, etc.)

**Comment by cnrudd** [comment]
I think consistency across the entire app is important to maintain.
So, any call, Hoist or otherwise, that did not have a hardcoded timeout option, would adopt the app-wide default.

**Comment by lbwexler** [comment]
Not sure I agree.  Why should having a slow API for the bulk of your app's business logic effect what we are doing with loading preferences. 

 Also, the more I think of it, it seems like if you have a set of fetch calls that all should have a longer (or shorter) timeout, you could write a helper fetch function. (e.g. `AppModel.apiFetch()`) that installed the timeouts in question.

**Comment by cnrudd** [comment]
This same reasoning (_"Why should having a slow API for the bulk of your app's business logic effect what we are doing with loading preferences."_) could have been applied to object to the implementation of the default header:
"Why should requiring header XYZ for the bulk of your app's business logic effect what we are doing with loading preferences."
[The question was considered](https://github.com/xh/hoist-react/issues/1045#issuecomment-478099950), but dismissed.

This same reasoning ("_write a helper fetch function. (e.g. AppModel.apiFetch()) _") could be applied to Hoist calls:
You could wrap them all in a helper HoistCall function to isolate them from any app-wide default fetch configs.  

Doing this is a more "app developer first" answer to the question, rather than a "Hoist Framework first" approach which requires the app-developer to wonder how his defaults are going to affect Hoist features he may not even know exist.

Better than a helper function, [here is a branch](https://github.com/xh/hoist-react/tree/hoistFetchService) in which two fetchService classes are instantiated on XH:
XH.fetchService
and
XH.hoistFetchService

The hoist framework uses hoistFetchService for all of its business, and the app developer is free to use XH.fetchService customized as desired without risking Hoist side-effects.   Non breaking change, too.

**Comment by lbwexler** [comment]
Think we are conflating two things here -- 1) whether we want to maintain
tighter control over the hoist internal timeouts,  and 2) how best to do it.

Regarding 2):   Agree with the being AppCentric, not Hoist Centric for
sure.   Excellent point.    I would not add an extra service internally --
just an internal helper method.

Timeouts also not fully analogous to headers in my mind -- headers might be
necessary just to get through firewalls, proxies, etc.

**Comment by cnrudd** [comment]
Assuming we agree that a setDefaultTimeout method on fetchService is a good feature to add, 
then here are my thoughts on the two questions you list out:

1) "whether we want to maintain tighter control over the hoist internal timeouts":  Yes, I think absolutely we do.  We don't want Hoist fetch settings to be affected by other API fetch settings, and vice versa.

2) "how best to do it":   Having a separate fetchService for each different server that an app has to call is a pretty common pattern, that is supported by other XHR libs.    

- https://www.npmjs.com/package/axios#creating-an-instance
- https://www.npmjs.com/package/ky#kycreatedefaultoptions

The defaults for one server shouldn't be a concern when coding for the other servers.   I'm working on an app that calls 5 different servers, 6 if you add in Hoist.    They don't all need a 2 mn timeout.  Just one of them does.   The others might be good with 1 mn. Hoist is apparently good with 30sec.     But now all of them are defaulting to 30secs [since this change](https://github.com/xh/hoist-react/pull/1975/commits/6bec5546388319d3d7589b4210118d02e51f429b).   Having a separate fetchService instance for each server each with their own defaults would be great.

I agree, timeouts and headers are not analogous - the consequences of a bad setting are different - but I think they both fall into that category of settings that a developer shouldn't have to worry about it bleeding into another part of the app.

I think we should move the framework to the pattern of:
1 Hoist Framework using its own custom tuned instance of fetchService,
2 Giving an app an instance of fetchService for free, and encouraging other fetchService instances to be created for different API servers.

Using fetchService instances with custom defaults is nice because you get all the built in convenience methods with the new instance:  getJson, postJson, putJson, etc.   

If instead you wrap a helper function around an existing instance, 
AppModel.apiFetch() you have to do it for either all the helper methods, or just for fetch and then all your calls need to have the full options object.

**Comment by cnrudd** [comment]
As discussed with Lee today, here is an example of how I am setting a longer default timeout on a subclass of FetchService:
```
export class AppCustomFetchSvc extends FetchService {
    async withTimeoutAsync(promise, opts) {
        return super.withTimeoutAsync(promise, {timeout: 2 * MINUTES, ...opts});
    }
}
```

**Comment by lbwexler** [comment]
So I finally get the value -- Colin does not want to import a new set of configs, and have to spread it in to every json request he makes.   

This is a clever solution, but still relies on overriding a 'private' method.  We could make it a bit more general, by supporting a method to set the `defaultTimeout` on the service.  This is analogous to setHeaders.

Could be useful for someone who really wanted to increase the global timeout as well -- but don't want to overly advertise that pattern
