### ISSUE TITLE
Document DashContainerModel.initialState

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2136]
Just spent a long time trying to figure out how to configure initial state for a dashboard, specifically how to size items with a mix of fixed and relative sizes. Couldn't figure it out or find any docs or examples explaining how it works.

Can you please document in some way? Would appreciate greatly - I didn't have any luck accomplishing what I was hoping to do, and I imagine any other developer would be in the same or worse place.

**Comment by amcclain** [comment]
Edit - I think I figured out how to get sizes working 😄 but would still be great to have some doc comments / examples explaining approaches to sizing.  Doesn't need to be elaborate - I think a basic comment on the relevant class(es) and then some more explicit sizing info in the Toolbox example would go a long way. Thanks!

**Comment by TomTirapani** [comment]
https://github.com/xh/hoist-react/pull/2137
https://github.com/xh/toolbox/pull/434
