### ISSUE TITLE
Tab Switcher Enhancements

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2144]
+ Handle overflow gracefully
+ Allow specification of size constraints on tabs (minSize, maxSize) to allow them to compress/expand within limits, or alternatively be a constant size across the container.

Realize the last item it a little under-specified.  Not exactly sure what is possible here and we need to explore.

**Comment by lbwexler** [comment]
Also -- please note that regarding overflow, we should consider the behavior that the intellij IDE uses, where all of the partially offscreen tabs appear as a little dropdown list that you select from and have the tab container scroll to that.  Its actually really nice!

**Comment by TomTirapani** [comment]
Opened a WIP PR for the overflow behaviour here: https://github.com/xh/hoist-react/pull/2162

Could use some polish and testing before merge - at this point, I'm just looking to see if we are happy with the overall user experience. I also intend to fold the tab size constraints into the same PR.

**Comment by petradish** [comment]
Hi Tom! Spoke to Lee about this in the context of our new app-- could you also add support for a bindable tooltip on Tab model? Let me know if I should create a separate ticket for it :)

**Comment by TomTirapani** [comment]
Hey Petra - sure thing, sounds like a great idea and should be straightforward enough to fold in :)

**Comment by TomTirapani** [comment]
I've updated the PRs to include the following changes:
+ TabContainerModel can be passed `switcherProps`, which it passes along to its TabSwitcher.
+ TabSwitcher supports `tabSize`, `tabMinSize` and `tabMaxSize` props.
+ Added bindable TabModel.tooltip and display in the TabSwitcher.

**Comment by lbwexler** [comment]
👍
