### ISSUE TITLE
Mobile NavigatorModel should support a `track` property

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2148]
Its the mobile equivalent to TabContainer, so would be nice to have this convenience as well.

**Comment by lbwexler** [comment]
And we can definitely use it in toolbox

**Comment by lbwexler** [comment]
Thinking about this some more, thing we should go ahead and make TabContainerModel and NavigatorModel just maintain a cache and only track the first time you visit a tab for Page.

Realize that is not what you always want, but think that is more likely to be what you want.

Thoughts?

**Comment by amcclain** [comment]
Yes, I agree - a user swapping between two tabs within a browsing session would ideally not trigger a stream of back-and-forth tracking logs.  Main goal here was to track if a given tab was being visited/used _in general_ - I think that tracking once-per-session would accomplish this and be a net win.
