### ISSUE TITLE
Store lastLoaded is set to Date.now() in constructor

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2151]
Store sets its properties lastLoaded and lastUpdated to Date.now() at construction time before any data is loaded

**Comment by lbwexler** [comment]
I think this is wrong, but worry that leaving them at null  could break apps that assumed they were never going to be null.

**Comment by lbwexler** [comment]
I think you could argue that the semantics for lastUpdated make sense.  I have edited this bug accordingly.  Will create a PR for the other behavior.  I think its worth it to fix.
