### ISSUE TITLE
Custom tabSwitcher in toolbar does not show overflow items

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2171]
When tabSwitcher is nested in a toolbar (or possibly any flex-like container), scrolling/overflow behavior is lost.
See example: https://github.com/xh/toolbox/commit/94ef7305ca51168957f8e28554a0b9a16b1b13bb
<img width="782" alt="Screen Shot 2020-11-02 at 7 38 28 PM" src="https://user-images.githubusercontent.com/49966727/97934343-6df94880-1d43-11eb-9863-03f5fc11d77c.png">

**Comment by TomTirapani** [comment]
Yikes - thanks for catching! Will take a look

**Comment by TomTirapani** [comment]
PR with fix here: https://github.com/xh/hoist-react/pull/2172

**Comment by lbwexler** [comment]
Thanks for catching Petra and quick fix tom!
