### ISSUE TITLE
GroupingChooser (DimensionChooser 2.0)

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2177]
DimensionChooser showing its age, especially next to some of our recent work on FilterChooser.  Thinking about:

+ More of a omni-box based approach, like FilterChooser?
+ Drag and Drop,  like our recent client work on column choosing?
+ Use Favorites, rather than History, to be like FilterChooser?

Also thinking to make a new control rather than breaking the API of the existing control.  Not sure about this one.

**Comment by TomTirapani** [comment]
Opened up draft PRs for review and feedback:
https://github.com/xh/hoist-react/pull/2200
https://github.com/xh/toolbox/pull/446

**Comment by TomTirapani** [comment]
<img width="427" alt="Screenshot 2020-11-24 at 13 28 24" src="https://user-images.githubusercontent.com/3017757/100100651-07a2aa00-2e59-11eb-9e28-9b9988357bbb.png">

**Comment by lbwexler** [comment]
This image is enough for me.  Its love at first sight.
