### ISSUE TITLE
StoreView

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2202]
I would like to have a StoreView which functions similar to the CubeView in serving as an instance of a centrally managed data store applying filtering and any other instanced state onto the data. It should also allow for being connected to a Store so any updates made to the primary Store are automatically sent to connected StoreViews and their associated Store instance.

The reason to have a StoreView in addition to CubeView is that Cubes don't really deal with hierarchical data, so while they work fine for flat data sets even if you aren't using the dimension grouping capabilities, it does not work with hierarchical data. Cubes and CubeViews are also pretty heavyweight when you aren't looking to do anything with dimensions or aggregation.

**Comment by amcclain** [comment]
@haynesjm42 can you review this older ticket and let us know if you have active app code that would benefit from such a system? Any more specific examples (still suitable for posting here) could be helpful.
