### ISSUE TITLE
Add CSS var to control Blueprint popover background + border

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2203]
....and default to theme standards - right now we get default BP theme colors.

**Comment by amcclain** [comment]
Closing this small ticket - but let's please review and include as part of #2288

**Comment by cnrudd** [comment]
Noticed that an effort to address this in a client app with:

```// Standardize popover bg - test+remove if https://github.com/xh/hoist-react/issues/2203 completed.
.bp3-popover-content {
  background-color: var(--xh-bg) !important;
}
```
did not address the text color in Blueprint tooltips, which use popover.

So, when this is addressed, it should be reviewed?tested on tooltips, too.

<img width="383" alt="tooltipStyleIssue" src="https://user-images.githubusercontent.com/2573928/122975448-58cc3b00-d361-11eb-8ad3-520cf44502bd.png">

**Comment by amcclain** [comment]
Thanks - agree and good to keep in mind.  (Still gonna close this one in favor of the larger ticket for now)
