### ISSUE TITLE
FilterChooser parsing should enforce space before "is" operator

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2204]
We have a valid record field value of "AIS" in a real-world use case - attempting to search for this value in filter chooser by typing "ais" yields the inline message `No matching field found for 'a'`.

I like that we allow the user to skip the leading space when entering an operator - e.g. `foo=` - but for the english word operators we need to require that space to avoid this ambiguity (and because no one would elide it for those operators).

**Comment by lbwexler** [comment]
frustrating -- we clearly have code here intending to do the right thing!

**Comment by lbwexler** [comment]
Simple typo -- fixed here https://github.com/xh/hoist-react/commit/a0420bfc2f58629eb98caa292a275f39a4954355
