### ISSUE TITLE
Default Select filterFn should test search input by word start and include special chars

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2220]
In a client app we have a long list of options that include special symbols -- searching 'a' would potentially return many hits with '@a...'  before 'a...' results. Lee and I discussed and think it would be better to search by word start or after whitespaces only.

**Comment by lbwexler** [comment]
So I spent some time looking at this.  I think what we have is generally defensible, and a reasonable default.  In many cases, its what you want -- e.g.  you are looking at email addresses and you indeed want to match something that comes after '@'

Or you want to find the second half of a hyphenated name.

Not sure we need to make it a special option, however -- seems far too specific.

In this case, I think the client app in question should probably just use the 'filterFn' attribute to go ahead provide a custom function which just looks for candidate.lowerCase().startsWith(s.toLowerCase())
