### ISSUE TITLE
`GroupingChooserModel.dimensions` should be settable/updatable

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2238]

**Comment by amcclain** [comment]
Adding to backlog - if there is any extra priority or push from a client around this pls give a shout.

**Comment by febbraiod** [comment]
No push or priority. I'm just using a less desirable component to achieve my ends. The client has no problem with what they have now.

**Comment by amcclain** [comment]
One thing to check here is to ensure that the model handles things reasonably in the case where it already has a current value (a list of _selected dimensions_ to group on) and then a new set of _available dimensions_ is set via this new API. If the current value includes a dimension that is no longer supported, we need to modify it.

We could either clear out the value entirely, or we could strip out only dimensions that are no longer supported.  I.e. a groupingChooserModel with value `[portfolio, strategy, trader]` would have its value automatically reset to `[portfolio, trader]` if a caller set `groupingChooserModel.dimensions = [portfolio, trader, country]`
