### ISSUE TITLE
LogViewer enhancements

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2239]
## For immediate action

- [x] The viewer starts in a confusing state w.r.t. the toolbar controls. I think it might not be flushing the current values (including tail mode setting) into the toolbar controls. 
- [x] Send last modified time and size of each log file down to client for display in the docked grid. It's OK if it would scroll horizontally - we can keep that file grid skinny - but having that log file metadata would be very helpful in terms of identifying active logs, cleaning out old ones, etc. Note this will require a hoist-core update to support - the hoist-react code should be tolerant of back-end servers that don't send the new metadata - it's OK if the new cols are blank if the server doesn't send the enhanced listing, but it should not throw.
- [ ] Allow actual selection of one or more log lines in the viewer grid. Helpful to support focusing on the contents of a particular line you want to be able to keep your eyes on. Note we will need to look carefully at how this interacts with tail mode and any auto refresh/scrolling.
- [ ] Allow copying multiple log lines to clipboard via context menu option, after above TODO re. allowing multiselect.
- [x] Render a `clock` component in the log toolbar set to the timezone of the server, so you can quickly see what time it is "now" as far as the server is concerned and don't have to do the TZ conversion in your head.

## Speculative - for future consideration - to discuss prior to implementation

- Using grid with more advanced filtering to enhance browsability (consider server-side row model)
- Parse datetime into a dedicated column -- would allow for viewing date times in the time zone of your choosing.
-  Add support for grouping of logs by day, or perhaps into buckets like today/yesterday/other.

**Comment by jskupsik** [comment]
[hoist-react branch](https://github.com/xh/hoist-react/tree/logViewerEnhancements)
[hoist-core branch](https://github.com/xh/hoist-core/tree/logViewerEnhancements)
