### ISSUE TITLE
Need built-in validator for JSON in a form field

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2241]

**Comment by amcclain** [comment]
To clarify/confirm - this ticket would add an `isValidJson` constraint to https://github.com/xh/hoist-react/blob/develop/cmp/form/validation/constraints.js - is that right?

Typical usage then would be to spec'd this as a `rule` on the backing `FormModel.field`, with the expectation (not not requirement) that the dev would use a `jsonInput` control for the component.
