### ISSUE TITLE
TreeMap forces attached grid to scroll to selection on every data update

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2244]
`TreeMapModel` is re-building it's data whenever the associated store records change, which will trigger a call to `ensureSelectionVisible()` on the associated `GridModel` via a reaction in the `LocalModel` for `TreeMap`. This would also be triggered by other state changes in `TreeMapModel` - such as expand/collapse state changing in the `GridModel` - which could be quite annoying for a user as well.

I'm not sure why we are syncing selection when the tree map data changes, seems like we should be ok to just do that when the selection in the `GridModel` changes - but I am not very familiar with the inner-workings of the `TreeMap`

**Comment by lbwexler** [comment]
John seems to me you are pretty familiar with how to reproduce this one in a client app.  Wonder if you could take a look?  Thanks.
