### ISSUE TITLE
TreeStyle background color overrides row hover on odd rows

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2248]
This makes row hover coloring not appear at all on these rows, while it is fine on even rows. Looks like the row hover css might need to get more specific to allow it to override the css for tree styling on odd rows

**Comment by febbraiod** [comment]
Notes: 
This refers to parent rows.

This every-other problem is only in dark theme. In light theme the hover and the highlight are nearly the exact same color and hovering appears to do nothing on the parent rows.

Not sure how to proceed yet. If we fix the every other row problem in dark theme, it creates an asymmetry with light mode where one has row hover and one doesn't. We could just kill hover in dark theme but not sure if people will miss it. Or we could have a special color in light mode for hovering over these special painted parent rows in light mode.

**Comment by febbraiod** [comment]
Spoke to John we agree that we should keep hover styles in both themes and tweak the color in light theme to play better with the highlighted tree rows

**Comment by febbraiod** [comment]
Fixed by https://github.com/xh/hoist-react/commit/ddbac783c961df7287a4cbe12d8c398b55937872
