### ISSUE TITLE
TreeStyle.NONE still affects display of rowBorders

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2253]
With `TreeStyle.NONE` I would not expect to see any special styling to differentiate parent/child rows, but if `rowBorders` are enabled we are getting the bolder tree borders + the styling looks off:

<img width="1221" alt="Screen Shot 2021-01-15 at 1 11 50 PM" src="https://user-images.githubusercontent.com/225806/104779240-97ffbb80-5733-11eb-9583-aedddbd52e6c.png">

**Comment by febbraiod** [comment]
Very surprised to hear this, those styles are wrapped in: &.xh-grid--tree-style-borders which I would NOT expect to apply here. Will look

**Comment by febbraiod** [comment]
This effect is not coming from the tree styles but rather that the ag-group-row has a preexisting definition to apply bolder borders. The tree border actually have a blue tinge that these do not. 

`
  // Row borders
  &--row-borders {
    .ag-row {
      border-color: var(--xh-grid-border-color);

      &.ag-row-group {
        border-color: var(--xh-grid-group-border-color);
      }
    }
  }`


Not sure wether or not we would still want to undo this, but would be a very easy change

**Comment by amcclain** [comment]
Thanks @febbraiod  for looking at this and pointing me in the right direction.  I think I've fixed it in the commit I pushed to close the issue - please take a look whenever you have a chance and give a shout if anything looks amiss.
