### ISSUE TITLE
LoadSupport should provide a means of detecting 'stale' loads

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2257]
It would be nice if LoadSupport could detect if a call to `doLoadAsync()`  was the latest call made, or if there was a more recent call made, so applications can check whether they should throw away the results of whatever asynchronous requests they may have made in the `doLoadAsync()`

In discussing with Lee, LoadSupport could keep track of the most recent `loadSpec` that was passed to a `doLoadAsync` and potentially install a function on the `loadSpec` which would make it easy to check if the current closure is the latest call or not.

**Comment by lbwexler** [comment]
Thinking a flag of the form `loadSpec.isObsolete` or `loadSpec.isCurrent` that could be checked by async processes to early out, if another load has been requested.

**Comment by lbwexler** [comment]
Seems like you almost want to know if

 a) a later load has been kicked *off* or 
 b) a later load has completed.
 
 In the former case, you might want to stop your loading.  In the latter case, you definitely want to stop your loading!

**Comment by lbwexler** [comment]
I'll do this as soon as the latest Hoist v38 refactor is in.
