### ISSUE TITLE
RestStore reload after bulk actions broken

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2260]
Uncaught (in promise) TypeError: this.loadAsync is not a function
    at RestStore.bulkUpdateRecordsAsync (vendors~admin~app.77aefb86.js:1)
    at async RegroupDialogModel.saveAsync (vendors~admin.dd6b43ae.js:1)

Probably caused by changes to remove @LoadSupport from parent class

**Comment by lbwexler** [comment]
Thanks for finding Don!  fixed.

**Comment by lbwexler** [comment]
https://github.com/xh/hoist-react/commit/88c7d2f050b7a6541e1b99fd85cda5c6deff1e93
