### ISSUE TITLE
Update to new major releases of react-select / react-windowed-select

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2263]
New major versions released of these libraries - doesn't look like they would require many or any changes in Hoist or app code, but have updated to expect React v17.

https://github.com/JedWatson/react-select/releases
https://github.com/jacobworrel/react-windowed-select/blob/master/CHANGELOG.md

**Comment by lbwexler** [comment]
Colin -- can you take a look at this one when you get a chance?

**Comment by lbwexler** [comment]
So took a quick look at this --- running into a bunch of errors below when building:

I did notice that post-release checkins from a few days ago REMOVE this dependency.  
              https://github.com/JedWatson/react-select/compare/react-select@4.0.2...master
Very suspicious -- we may be best off just waiting for the next release.



ERROR in /Users/lee/sbox/toolbox-wrap/hoist-react/node_modules/@emotion/cache/dist/emotion-cache.browser.esm.js 245:53-60
"export 'COMMENT' was not found in 'stylis'
 @ /Users/lee/sbox/toolbox-wrap/hoist-react/node_modules/react-select/dist/react-select.browser.esm.js
 @ /Users/lee/sbox/toolbox-wrap/hoist-react/desktop/cmp/input/Select.js
 @ /Users/lee/sbox/toolbox-wrap/hoist-react/desktop/cmp/input/index.js
 @ ./src/examples/portfolio/AppModel.js
 @ ./src/apps/portfolio.js
 @ multi /Users/lee/sbox/toolbox-wrap/hoist-react/static/polyfills.js ./src/apps/portfolio.js

**Comment by lbwexler** [comment]
Stil seeing this error even after trying 4.1.0.  Hmm.

**Comment by amcclain** [comment]
Oh dear - me as well.  I thought it might be an issue with local Toolbox having the old versions of the two react-select deps (included via its dep on hoist), but adding a `resolutions` field to my toolbox package.json to fix it at the same version didn't help.  Neither did deleting node_modules in both projects and forcing a reinstall there.  

Those were my two immediate ideas...will have to come back around to it. Surprising not to find any references to the same error - makes me think it's something related to our webpack processing or...not sure.

**Comment by amcclain** [comment]
Updated in b6c3c21fef5fc66b793e8a34fe1587f6fed9656f

Runtime issues with bundling / stylis imports (hopefully) resolved via https://github.com/xh/hoist-dev-utils/commit/26d7a7e31443424dd2bee9dd93d8ad2239c95a56 - included in @xh/hoist-dev-utils v5.6.0
