### ISSUE TITLE
Issues with Refs in latest Blueprint

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2272]
UPDATE:  This effects DateInput, GroupingChooser, and Checkbox.  Problems are caused by passing a ref with a `current` property.  Passing a function seems to solve the problem.

This bug can be seen in toolbox dev at:
https://toolbox-dev.xh.io/app/forms

Click in the "Hire Date" field, on the date value.

This will produce this error in the console: 
```
vendors~admin~app~fileManager~mobile~news~portfolio~recalls.c85b14b1.js:2 Uncaught TypeError: this.popoverElement.contains is not a function
    at Popover.isElementInPopover (vendors~admin~app~fileManager~news~portfolio~recalls.255d1d61.js:formatted:8136)
    at Popover._this.handleTargetClick (vendors~admin~app~fileManager~news~portfolio~recalls.255d1d61.js:formatted:7973)
    at Object.Rb (vendors~admin~app~fileManager~mobile~news~portfolio~recalls.c85b14b1.js:2)
```

but does not otherwise disrupt the DateInput functionality or user flow.

The error does not appear in production toolbox:
https://toolbox.xh.io/app/forms

**Comment by lbwexler** [comment]
This is effecting groupingChooser as well.   Seems to relate to the provisioning of any 'popoverRef' property to the Blueprint popover component.

**Comment by lbwexler** [comment]
This seems likely related to the blueprint upgrade

**Comment by lbwexler** [comment]
We could decide whether to go ahead and just upgrade to BPs Popover2 and Tooltip and 
see if that fixes the problem

**Comment by lbwexler** [comment]
This one extremely interesting.  A few findings:

+ Colin did some early work on moving to popover2, but that seems quite disruptive with the styling, so we want to wait on that. Also seems like BP is a a work in progress.

+ it seems like these blueprint components are choking on the modern refs with a `current` property (either from React.createRef, or our createObservableRef.  they do fine on functional refs (!?)

I am patching the two props that seem to be causing us problems, to wrap them with a functional ref.  We could do  a code bombing for the other refs, but not sure that is needed.

Also not quite sure how best to report this to blueprint, as the failure mode is a bit weird.
