### ISSUE TITLE
StoreMenuItems should take an 'hidden' property

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2277]
Right now to conditionally hide the item a dev needs to use the displayFn to return {hidden: true}. Reviewed with Lee, it's a bit clunky.

**Comment by lbwexler** [comment]
So changing the name of this to reflect the fact that for menus, we are using "hidden" to remove them, and that the problem is with the "StoreMenuItems" (used in grids) and not
"MenuItems"

**Comment by amcclain** [comment]
I'd actually favor a breaking change to move to `omit` here instead of `hidden`.

But to ensure I understand the ticket, can you not specify some condition up-front on a menu item to set its `hidden` config to true?  Or do you have to spec a `displayFn` for some reason?

**Comment by amcclain** [comment]
@febbraiod can you please clarify? We are reviewing this now in our ticket triage and are having a hard time determining what should be done.  Thanks.

**Comment by febbraiod** [comment]
Honestly, I don't recall what prompted this. I reviewed the work I was doing back and February and tested the cases that looked like they may have prompted this ticket, but I can't find any problem using "hidden" on menu items of any kind (app or context). going to close and can maybe refile if this ever seems to present an issue again.
