### ISSUE TITLE
Mobile MenuButton should accept a title prop

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#2280]
The mobile MenuButton component should accept a title prop, and render it like a panel title at the top of the menu

**Comment by TomTirapani** [comment]
Preview:

<img width="388" alt="Screenshot 2021-02-10 at 16 21 53" src="https://user-images.githubusercontent.com/3017757/107538659-1ed17800-6bbc-11eb-8837-678e362f02e9.png">

**Comment by lbwexler** [comment]
👍
