### ISSUE TITLE
Dynamic Tabs and Routing

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#2286]
TabContainers with dynamic tabs need to support routing. There are a number of questions that need to be resolved:

+ What happens if a user arrives at a route that corresponds to a dynamic tab? Should the TabContainerModel auto-create it?
+ How can we support routing with multiple "instances" of the same tab?
+ A bit of an edge case, but do we need to think about nested routes (i.e. a dynamic tab within a dynamic tab)?

**Comment by lbwexler** [comment]
Closing.  As discussed with @TomTirapani, this type of behavior is going to be handled in custom app code.
