### ISSUE TITLE
TextInput does not pass DOM props onto the HTML input element

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2289]
This can cause inconveniences such as needing to wrap the TextInput component in a DIV to size it correctly or add event handlers like onPaste.

**Comment by lbwexler** [comment]
Interesting idea, but am wondering why we would do this for just TextInput.  Seems like something we would to do consistently for all inputs (or at least most inputs)

For example, wouldn't the user using this feature expect NumberInput to work as well?
