### ISSUE TITLE
Grid State including some new undefined keys

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2304]
Cause issues with client app when comparing state on the client to state saved as a JSON blob (which cleans up undefined values with JSON.stringfy() before sending to the server

<img width="637" alt="Screen Shot 2021-02-19 at 9 42 25 AM" src="https://user-images.githubusercontent.com/15745614/108519734-eefb3200-7297-11eb-913a-666173730d68.png">

**Comment by lbwexler** [comment]
discussed with Don, and it appears to be just `pinned`.

I can't reproduce this in toolbox yet, although certainly see some paths where it could come about

**Comment by lbwexler** [comment]
As I said, could not reproduce, but this seems like it should fix the problem, and is safer/clearer
