### ISSUE TITLE
Review practices for rehydrating component state from JSONBlobs

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2314]
In a client app we are managing views by saving, for example, a GroupingChooser's state coupled with a GridModel's state using our jsonblobservice. In both cases, loading this state into the corresponding component seems to be a bit more onerous than it may need to be. And, in the example of GridModel, it becomes desirable (if not necessary) to call a method marked as "Implementation".

<img width="812" alt="Screen Shot 2021-02-24 at 9 33 02 AM" src="https://user-images.githubusercontent.com/15745614/109168248-9cfd5500-774c-11eb-8282-56841a7fe281.png">

The code for the grouping chooser is similar.

I think it might be a good idea to provide public helper methods in Hoist that we can just pass the bit of state to and have hoist do the actual rehydrating. Then we could have one liners in the app code.

**Comment by amcclain** [comment]
Added #2492 as a very specific TODO out of this ticket - otherwise closing for now as it's a relatively general issue and we're looking to triage where possible.
