### ISSUE TITLE
Toolbar - add compact mode support

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2333]
We often have a use-case for more compact / minimal toolbars in supporting panels such as detail views and widgets, where the full-height toolbars take up too much room relative to the overall panel size.

I'd suggest a new boolean `compact` prop on `Toolbar`, default false, to enable such a mode. We could also discuss going with a `sizeMode` prop instead to mirror where we landed with `Grid`, but I really doubt we would support more than compact/standard in any near-term timeline. (I was trying to justify some case for `large` such as a "ribbon" style toolbar, but it seems like a real stretch.)

Main challenge is to supply style overrides as needed to get standard / common components such as buttons and form inputs fitting and looking good within a compact toolbar.

**Comment by amcclain** [comment]
Note that `Panel` has a `compactHeader` prop. I've been considering if it would make sense to support a `Panel.compactToolbars` prop, but I do _not_ think so. Would require cloning and modifying toolbar element if passed in, and I think you might commonly want e.g. a compact bottom bar but standard size top bar.  I think it's more clear and just as easy to have the dev configure each toolbar appropriately.  (But as always open to discussion - flagging it here as I thought it might well come up in review.)

**Comment by TomTirapani** [comment]
Opened PR which adds the prop to toolbar, corresponding CSS vars and special handling for common toolbar inputs

<img width="724" alt="Screenshot 2021-03-15 at 12 59 43" src="https://user-images.githubusercontent.com/3017757/111157165-7c2b6100-858e-11eb-9902-3a01449cfe14.png">

**Comment by lbwexler** [comment]
I like the API -- re: `compactToolbar`.  In practice, we want people actually breaking out toolbars in to their own components, and to do that, you already need to explicitly instantiate the toolbar rather than providing the raw items.
