### ISSUE TITLE
Flex columns don't adjust their size in response to autosizing

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#2341]
e.g. You have 2 columns:
```
[
  {field: 'foo', flex: 1},
  {field: 'bar'}
]
```

If upon autosize column `bar` becomes wider, the expected behaviour is for column `foo` to shrink. Instead, the grid starts scrolling horizontally. I believe this is a regression.

Upon sorting the grid, the flex column is recalculated.

**Comment by lbwexler** [comment]
This seems like a high priority item to fix.

**Comment by amcclain** [comment]
@TomTirapani + @lbwexler - based on your recollection, would this be worth re-testing with the latest ag-grid? I.e. any chance that the regression noted in our comment here has been resolved by the library, and we might now be triggering an extra resize run?
