### ISSUE TITLE
Add FormModel.fieldDefaults config

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2369]
There are not that many config options on ~`FormField`~ `FieldModel` that can be set, but it might still be useful (and consistent with other areas in the code) to support a `fieldDefaults` config object in the `FormModel` ctor.

An example use case I've encountered is where we want _all but one field_ in the model to be readonly. We can't set `readonly:true` for the entire`FormModel`  since that would not allow for our one exception, so we must set for each field except the one that needs to change.

edit - fixed to properly refer to FieldModel

**Comment by lbwexler** [comment]
We already have a `fieldDefaults` for contained `FormField`s on the `Form`.

Do you mean you want a `fieldDefaults` for the `FieldModel`s in the `FormModel`?

Overuse of the word `field` definitely hurting us here.

**Comment by amcclain** [comment]
Closing as not a high-value change, and would add some net confusion given existence of `Form.fieldDefaults` prop
