### ISSUE TITLE
Promote Experimental Flags for V40

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2371]
We would like to promote/resolve

GridModel.externalSort
Store.shareDefaults

**Comment by amcclain** [comment]
Would like to discuss default enabling of `Store.shareDefaults` - all for promoting out of experimental, not as sure that it should be the default.  My concern is that the behavior is a bit surprising.

**Comment by lbwexler** [comment]
yes -- we need to discuss -- I was actually hoping we would go even further than defaulting it, and actually make it *always* true.

Think there is value to not having such a core data structure have two different forms, unless we really need it.  We know we need the shareDefaults form.  Seems like it will be that much harder to maintain/test both forms.

Let's discuss!

**Comment by amcclain** [comment]
Yes, I agree - needed a bit of time for the entire idea to burn in, but better to have it always behave a certain way for sure and fully commit to the change.
