### ISSUE TITLE
Support empty grid exports

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2376]
Currently exports are disabled for empty grids, and Excel throws an Alert message to confirm repairing the sheet.

![Screen Shot 2021-03-25 at 1 21 05 PM](https://user-images.githubusercontent.com/49966727/112519585-e56e5980-8d70-11eb-910b-6b65152be162.png)

![image](https://user-images.githubusercontent.com/49966727/112519479-cc65a880-8d70-11eb-90d2-07be3de0b8b2.png)

One solution to the repair error is to add a stub row of null values under the column header row. (Note: No repair is needed if the rows are empty (from a filter) and a total row is included) PR forthcoming

**Comment by lbwexler** [comment]
This has been fixed in Hoist Core!  Thanks Petra 👍
