### ISSUE TITLE
Write built-in "navigation" track logging only once-per-session

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2399]
`TabContainerModel` and `NavigatorModel` (soon - see #2150) support a `track` config to automatically post an activity track log entry when the user activates a page or tab.

See discussion in #2148 - would be a likely improvement if this auto-tracking happened once-per-browsing-session, instead of every time a user flipped back/forth between pages or tabs.

If we needed to, we could support `track` as both a boolean for default behaviors, or as a config object to allow customizing the category, message, and potentially some new flag to control this behavior (e.g. `onEveryShow` or similar, default false).

**Comment by lbwexler** [comment]
*Really* like the idea of having the track system support this in general.   Could be something like assigning a `oncePerSessionKey` to the track options.  Will actually make supporting this in TabContainerModel and NavigatorModel much, much easier
