### ISSUE TITLE
Formatters should not mutate the options object that they get passed

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2403]
If the formatter needs to make these types of changes it should defensively clone the object first.

One Example, fmtMillions applying the 'm' label:

```
export function fmtMillions(v, opts = {})  {
    saveOriginal(v, opts);
    if (isInvalidInput(v)) return fmtNumber(v, opts);

    v = v / MILLION;
    **if (opts.label === true) opts.label = 'm';**
    return fmtNumber(v, opts);
}
```

We have a use case where that opts.label needs to remain 'true' for reference in subsequent calling code

**Comment by lbwexler** [comment]
This is very familiar -- I recall that we made the early decision in hoist-sencha (perhaps incorrect?) to go ahead and do this mutation for efficiency purposes.  Users were to be warned via documentation to pass in a dedicated config object for the call.  Disappointing that this is not documented if that is indeed the case.  

We should revisit this ASAP.

**Comment by lbwexler** [comment]
FWIW We do actually comment on this in our docstring for createRenderer


/**
 * Generate a renderer for a given formatter function.
 *
 * The returned renderer takes an optional config for its assigned formatter and itself returns
 * a function that takes only a value, for convenient use with e.g. grid cell rendering.
 *
 * If the formatter config is an object it will be cloned before being passed to its formatter
 * to ensure that the formatter gets its own clean copy each time it is called.
 *
 * @param {function} formatter - an existing formatter method.
 * @return {function(v: Object):function} - a configurable renderer.
 */
