### ISSUE TITLE
Introduce new private fields syntax to protect key Hoist classes

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2413]
We recently ran across an application that was writing the `fields` property of Store.  This property is intended to be set up internally in the constructor of Store and never changed.  The application in question broke on upgrade to Hoist

In general, we aren't always good about clarifying/enforcing this in our API.  We should look for key properties like this and harden them.  Especially important are properties like `Store.fields` which applications may be tempted to modify directly.

**Comment by amcclain** [comment]
I think it might be time to start using the official syntax for private fields - I would vote we begin doing so.

It's just moved to stage 4 and is [enabled by default in the latest Babel 7.14](https://babeljs.io/blog/2021/04/29/7.14.0). While I know the syntax (a leading `#`) doesn't make us shout with joy, this appears to be how they're gonna work, and we want to be first-class in our support and use of the JS class system.

Note, private fields are part of the overall class fields spec @ https://github.com/tc39/proposal-class-fields

**Comment by amcclain** [comment]
(Sorry for the confusion, put this note on this ticket, which isn't really about private fields so much as readonly properties, but wanted to queue up a discussion on both interrelated matters - if we were going to do an audit of our highest-priority classes and their public/private/readonly APIs, good I think to look at it all together)

**Comment by lbwexler** [comment]
yes, noticed that as well.   Sounds good.  Looking forward to seeing how it
works!
