### ISSUE TITLE
Improve rendering of GridModel.treeStyle when some top-level nodes have no children.

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2414]
We have a number of usages in a client app where some root level nodes have children, and some don't.  
(think, e.g. Traders and Trader Groups).  

They should all have the identical tree styling to indicate that they are siblings, but the nodes without children are themselves styled as children, which ends up being quite confusing.

**Comment by lbwexler** [comment]
Saba to look at this with Don, who did the original implementation.

**Comment by amcclain** [comment]
Note that you can see these kinds of "ragged" groups in https://toolbox-dev.xh.io/admin/tests/grid by enabling tree mode
