### ISSUE TITLE
Support commitOnChange for DateInput

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2415]
DateInput deliberate has not supported `commitOnChange`, instead requiring the user to use the picker, blur the input, or press enter to flush in their updated value. 

IIRC this is because we didn't want to make assumptions about when the user had completed adjusting or entering a date by manually editing/typing - e.g. we didn't want to simply throw any changing input at moment and use the date it produces, as then a user typing "2020" who pauses for a sec could end up with "2020-01-01" as their value (due to moment's eager acceptance of partial date strings).

However with inline grid editing (PR #2384) we are running into issues where inline dateInputs don't flush their values eagerly enough to capture their update before ag-grid unmounts the component - e.g. when tabbing from a dateInput editor cell to the next cell, or clicking another cell, the previous dateInput is dismissed and the resulting record value remains unchanged. 

If we were more eagerly evaluating keyed-in changes to the textInput and committing a new value if valid, that would be one way to avoid those issues.

It might also generally be desirable to have this input component support a notion of `commitOnChange` in line with the others, on its own merits.

One option to keep this sane would be to check the input string against the component's `formatString` prop (or default) and only parse when matched.  I.e. do nothing with input of `2020-01` but once user has typed `2020-01-13` recognize that a complete date string entry is in place and parse / commit.

Open question if we want to still try to be friendly in terms of recognizing common partial inputs, accepting an array of valid alt formats ([like the Sencha component does](https://docs.sencha.com/extjs/6.5.2/classic/Ext.form.field.Date.html#cfg-altFormats)), etc.

**Comment by lbwexler** [comment]
We fixed this as part of recent work on inline editing.  Behavior is now consistent with its (fixed) setting of commitOnChange: true
