### ISSUE TITLE
Components should support a consistent way of setting a "testId" for use with automated tools

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#2417]
Automated UI tests need to uniquely identify visual components such as buttons and form inputs so they can be manipulated. Best practice in frameworks such as Cypress is to set the `data-test` attribute of DOM elements. 

It would be helpful if all `HoistInput` and other manipulatable components support a `dataTest` property to set the `data-test` attribute and uniquely identify them. Alternately, the property could be called `testId` or something similar.

**Comment by amcclain** [comment]
I would definitely vote for `testId` as the consistent top-level prop accepted by Hoist components, rendered perhaps to `data-testid` to use a `data-` attribute from Cypress's list of default selectors - see https://docs.cypress.io/guides/references/best-practices#Selecting-Elements.

**Comment by amcclain** [comment]
Updated ticket to reflect that this would not be limited to HoistInputs - as mentioned, applies to buttons, but really any component where we can support I think we should, to allow for e.g. ensuring that a panel has been rendered, focusing a grid element, etc.

Would certainly be an iterative process to get "full" coverage, or as close to it as possible, but we could start with the high-priority components already identified - buttons, inputs, and other interactive elements.

**Comment by jskupsik** [comment]
Will be working on this.

I think we've decided the name `testId` for the top-level prop name and `data-test-id` for the tag attribute.

What it will look like to tag a component in hoist:
```js
button({
//...
testId: "test-example",
//...
});
```

How to find a tagged element using cypress:
```js
cy.get('[data-test-id="test-example"]').click()
```

**Comment by jskupsik** [comment]
Additionally, for form fields (and, later, for menu / submenu items), we talked about adding a `data-field` attribute automatically set to the linked field name.
That way, form fields can be accessed easily using cypress via:
```js
cy.get('[data-field="lastName"] input').type('foobar{enter}')
```

Cypress' best practices page recommends the use of custom methods to encourage the use of these selectors:
```js
// cypress/support/commands.ts

Cypress.Commands.add('getByTestId', (selector, ...args) => {
  return cy.get(`[data-test-id=${selector}]`, ...args)
})

Cypress.Commands.add('getInputByField', (selector, ...args) => {
  return cy.get(`[data-field=${selector}] input`, ...args)
})
```

which would be used like

```js
cy.getByTestId('test-example').click()

cy.getInputByField('lastName').type('foobar{enter}')
```

**Comment by jskupsik** [comment]
Navbar tabs already have a `data-tab-id` attribute.

**Comment by jskupsik** [comment]
Hoist-react branch: https://github.com/xh/hoist-react/tree/2417-cypress-testId
Toolbox branch: https://github.com/xh/toolbox/tree/cypress

**Comment by pauldelano** [comment]
Some additional requests from client experience with end to end integration testing with Playwright...

1. Important to be able to set testId on purely visual components like span, which is needed to verify displayed values.
2. Can select components with test id also set each option with a test id with the value of the choice. For example, if the test id of the select is 'user-select' each option would have test ids like 'user-select-George', 'user-select-Ringo', etc.
3. Confirm that form field labels are always the DOM "label" of the corresponding input. Important for selectors.
4. Have a preference to set the DOM field to Playwright default 'data-testid' (not 'data-test-id'). Not critical since Playwright can be configured to use alternate test id name.

**Comment by amcclain** [comment]
Closing this older ticket as I think the existing history here might be more confusing than helpful. Will open a fresh issue to better document the initial scope of our work here.
