### ISSUE TITLE
Grid column tooltips display on top of one another

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2425]
There is a timing issue here with how we bring up these tooltips that causes them to be super-imposed on each other when mousing over the grid at normal speeds. Easily reproducible in "Standard" toolbox grid by just mousing over the "Company" column.

Perhaps need to increase the delay before bringing a new one up, and decrease the delay before hiding the old one!

**Comment by lbwexler** [comment]
Cannot reproduce this on ag-Grid site -- but note was not able to find an example of `tooltipComponentFramework` being provided on the column.  All tooltips are provided via registration with `frameworkComponents` prop.

**Comment by lbwexler** [comment]
https://www.ag-grid.com/react-grid/component-tooltip/?

**Comment by TomTirapani** [comment]
PR: https://github.com/xh/hoist-react/pull/2427
