### ISSUE TITLE
Improve error when dev attempts to updateData on a grid using XH.genId for idSpec

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2429]
In this case, the 'id' passed to the store.updateData (eg {id: gridModel.selectedRecord.id}) method will not match the id that the api will generate using the idSpec to find the record in the grid. The errors simply says something like "cannot find record with xh-id-95", and the dev is left wondering how they are passing an id that doesn't even exist in the grid.

Could add to the message something along the lines of: "in order to update grid data, records must have consistent persistent ids. Perhaps you are using XH.genId?"

**Comment by lbwexler** [comment]
Don -- I am not sure I get this -- feel free to summarize, or just put up a PR to fix. :-)

**Comment by febbraiod** [comment]
Yes hard to explain. Reviewed issue with John H. Will put a PR in next week, and we can look at to together.
