### ISSUE TITLE
Highcharts navigator does not allow dragging of range when hosted in a BP dialog

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2433]
This is a minor bug report from a important client app. Confirmed that the same component works find in when not in a modal. And also confirmed this same problem presents in dialogs in another client app.

**Comment by febbraiod** [comment]
https://github.com/xh/toolbox/tree/brokenChartNavigatorExample

**Comment by lbwexler** [comment]
Don -- did we just disable the behavior in the client app?   

We should also try this with the latest highcharts.

**Comment by febbraiod** [comment]
No need to disable in client app. It just doesn't even display the <-> dragger, nor does it respond to dragging.
