### ISSUE TITLE
Form should support setting readonlyRenderer within fieldDefaults

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2444]

**Comment by lbwexler** [comment]
Let's also just consider any other props that should be handled by fieldDefaults as well.

**Comment by amcclain** [comment]
See https://github.com/xh/hoist-react/blob/8b65a4f15c74b3a1e0979de54bf5be3c3e6b42b5/desktop/cmp/form/FormField.js#L84 for the block of code that is controlling which `FormField` props can be defaulted in this way.
