### ISSUE TITLE
Issues with Mobile Exception Dialog

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2451]
Seems like the "details" of our Mobile Exception Dialog is a bit clunky:

1) If I want to type in a message, the keyboard comes up over the buttons, and the details, making for a clunky experience.  Perhaps we should let the user type in the message with a dedicated modal?

2) The form is not re-validated aggressively enough.  I actually have to tap somewhere outside the form to get it to validate and then allow me to send my message.  This was very frustrating.
- We should use commitOnChange on this form for sure
- Do we need to fix our mobile text area to validate on enter?
- In the absence of a quick fix on both of the above, we should certainly just remove the validation, so that the user can always just "submit" -- what's the harm in getting an empty message here now and then??

**Comment by lbwexler** [comment]
Tom -- please take a look -- note that a couple of the items on the list are quick wins that might be handled seperately.

**Comment by TomTirapani** [comment]
Improved the experience by opening the message input in a dedicated prompt, which moves to accommodate the on screen keyboard. The prompt itself uses commitOnChange to validate the message requirement.
https://github.com/xh/hoist-react/pull/2592
