### ISSUE TITLE
Allow apps to customize what it means to "reset" preferences

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2452]
Our default implementation of "restoring defaults" in XH.js  is a pretty blunt tool 

 ```
async restoreDefaultsAsync() {
        await this.prefService.clearAllAsync();
        this.localStorageService.clear();
        this.reloadApp();
    }
```

For example, removing all preferences might be overkill (think cross-platform apps) and you may want to also clear other Domain object, JsonBlobs, custom server APIs, etc.

Considering having the XH client-side implementation perhaps whack Local Storage, but then delegate to a server-side method of the form:

`restoreDefaults(String appName)`

We could provide a default implementation that whacks all preferences and JsonBlobs, but we would allow that to be overridden by apps.  Just need to decide the best place to hang this method.

**Comment by amcclain** [comment]
I would vote that we host the implementation in an overridable method on `HoistAppModel` - we could keep the implementation the same to avoid introducing any behavior change while allowing an app that needs to customize to do so (e.g. mobile app can clear a much more limited set of prefs to avoid unintentionally disrupting its desktop counterpart)

**Comment by lbwexler** [comment]
It is weird to have the server-side take an `appName` where `appName` is largely a client-side concept.  But still might be worth it, to allow easy access to all state.
