### ISSUE TITLE
Improve documentation describing requirement of "owned" model

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2458]
Some examples of what methods create an "owned" model would be very helpful here:
https://github.com/xh/hoist-react/blob/de9d34955e24d8e6ad68b58bed17ed4e9cc4298f/core/refresh/RefreshContextModel.js#L27
uses ?
creates ?
useLocalModel?

The definition of "owned" can be acquired by reading through a fair bit of code, but if possible to list at least the most frequently used means of creating an "owned" model, and the most frequently used means that do not create an "owned" model, that would be very helpful.

Not sure the meaning of "directly" can determined by an app developer here.

**Comment by amcclain** [comment]
Yes, agree this important concept needs some strong clarification.  (I saw the support thread from earlier and was going to to reply noting this gotcha, but then I saw this ticket first!)

I'm happy to take a look at adding something as I'm thinking about the overall documentation approaches we can use for cross-cuttong concepts like this one.

**Comment by lbwexler** [comment]
Closing this -- we know we need to improve our core documentation here -- this ticket not adding alot.
