### ISSUE TITLE
Include full URL with client error reports

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2462]
Including the full URL with client error reports could be an easy way to provide some additional troubleshooting context to us when we get these alerts.  Would show the exact route, flag alerts accidentally sent from localhost during development, and potentially distinguish other cases like non-unique environments or alternate deployments.

Would require coordinating a matching hoist-core update.

**Comment by lbwexler** [comment]
looking for the current url in the browser here, especially to catch routing info.
