### ISSUE TITLE
Column autoHeight doesn't adjust without first clearing the store

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2465]
If editing a field changes the row height, you currently need to clear the store before loading the data in order to get the height to adjust without needing to refresh the browser. This happened when editing a task in the todoApp.

 //  Clear store so description field's auto height readjusts after edit
        this.gridModel.clear();
        this.gridModel.loadData(tasks);

**Comment by TomTirapani** [comment]
Thanks for catching and filing!

I've opened the following PRs which should address the issue:
https://github.com/xh/hoist-react/pull/2471/files
https://github.com/xh/toolbox/pull/485
