### ISSUE TITLE
Desktop Panel: support not requiring a defaultSize value for a collapsible Panel

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2473]
There is this use case for our Panel component:
A collection of Panels in a vFrame that is y-scrollable.  The user may want to collapse several panels and leave one expanded in order to focus on just that one expanded panel.   The panels all expand vertically to fit their content, of which the final dimensions are data dependent.

This use case is blocked by the Panel model config's requirement of a numerical value for `defaultSize` when the Panel is collapsible.  This requirement means the panel is not allowed to auto-size vertically to fit its content, which it does when the Panel is not collapsible, and no defaultSize value is needed.

Could the model config accept a config like below, to handle this use case:
```
model: {
   collapsible: true,
   resizable: false,
   showSplitter: false,
   side: 'top',
   defaultSize: 'auto|fitContent'
}
```

**Comment by amcclain** [comment]
I suggest we discuss this together with a review of what we have in PR for #1856.

**Comment by amcclain** [comment]
@cnrudd we are closing this as the linked PR allows passing string values through defaultSize - @haynesjm42 reports that this is working in a similar use case he has tried.
