### ISSUE TITLE
Record IDs are incorrect when a tree grid is filtered by 2 or more dimensions in its filter chooser 

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2487]
I have found this bug in a client's dashboard app.

In a tree grid with the following accessories:
GroupBy
FilterChooser

If a user filters in the Filter Chooser by at least the 2 top groupBy fields, the store produces record ids that look like this:
```root>>undefinedAND[]>>dimension1=[userstring1]>>dimension2=[userstring2]```

Application logic that subsequently tries to extract the filter out of the ID throws when trying to parse ```undefinedAND[]```

**Comment by lbwexler** [comment]
Looks serious

**Comment by cnrudd** [comment]
It probably doesn't happen too often.  The effect in this app is that the grid context menu doesn't appear.

**Comment by lbwexler** [comment]
We have determined that encoding the query filter in the ID is not something we want or can effectively support here.

App will be rewritten to get that query filter out-of-band, not from the id.
