### ISSUE TITLE
Add GridModel.setColumnState() API method

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2492]
See #2314 - app code should expect a clean, public API for taking a previously saved copy of `gridModel.columnState` and applying it back to a GridModel in one call.

**Comment by lbwexler** [comment]
don -- any progress on this?  Seemed like you had a branch going.  Looking to close out this one

**Comment by febbraiod** [comment]
Yep slipped off my radar, I think I might have thought I already opened the PR:

https://github.com/xh/hoist-react/pull/2540/files
