### ISSUE TITLE
Investigate changes WRT selection handling in either Hoist or Ag-grid

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2503]
We have recently seen unexplained changes with the behavior of selections in a flagship client app on Hoist 41-SNAPSHOT. The observed changes have manifested two ways:

1) In a grouped grid that displays tickets, one can now click on a group row and have it display as if it is truly selected (ie with borders around it highlighting it as a selection. Then, an auto refresh might come in, and select the first row automatically (indicating that the "selected" group row is not truly considered a selection), but confusingly also leaving the group row confusingly display as if it is still the selection.

2) In another grid there are a variable number of grid thats should only allow one selection between them. If a row is selected in one grid, the other grids selections are cleared. For an extended period of time @lbwexler and I both recall the code in place for this working fine. Recently QA reported that clicking on a second grid clears the selection entirely from all grid. (this one may or may not relate API changes as there has been other work done surrounding these grids)

**Comment by lbwexler** [comment]
Don -- lets go over case #2 and make sure we are ok there in the app in question.  If so, we would like to just close this bug.  The current behavior does not necessarily seem broken.

**Comment by febbraiod** [comment]
We made some adjustments to compensate. You and I were reviewing that at the time of the breakage IIRC. Then we noticed the group rows being highlighted as selected, hence this ticket.
