### ISSUE TITLE
Add expand/collapse all button to tree column header

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2521]
Installing a small expand/collapse caret button in the tree column header is a convenient shortcut for users wishing to expand/collapse all records in a tree grid.

Note that the state and action taken by the button will naturally depend on the current expand state of the rows. 
- If they are all collapsed, it should display as `>` and expand all when clicked. 
- If they are all expanded, it should display as `v` and collapse all when clicked. 
- If they are mixed, it should (probably) display/act as if all collapsed, although we could review and decide if it should flip based on the majority state.

**Comment by lbwexler** [comment]
Should probably be optional -- might be overkill on many grids.

Agree this seems like a nice enhanceent.
