### ISSUE TITLE
Ag-grid grid property `stopEditingWhenCellsLoseFocus` doesn't work with DateEditor day picker popover

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2530]
If you turn on the ag-grid grid option `stopEditingWhenCellLosesFocus` then the date editor day picker will cause the cell to lose focus and stop the editing without applying you selection (also happens if you try to change the year, etc). 

We might want to consider turning this property on by default as it seems like desirable behavior to not leave a cell in an active editing state when you click elsewhere on the screen. It can in fact be problematic if you click on something like a save button - the change you had been making will not be reflected in the store record until the editing finishes.

The select editor does not appear to have any issues with this so perhaps there is something we are doing there which eats the click event before ag-grid can process it?

For reference: https://www.ag-grid.com/javascript-grid/cell-editing/#stop-editing-when-grid-loses-focus

**Comment by lbwexler** [comment]
John -- can we go ahead and move forward on this for this friday's v43 release.

At the very least, seems like we could change the default now, for pickup in the other editors, even if not working on dates...
