### ISSUE TITLE
Grid Import/Paste from Excel

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2535]
Would like a built-in feature which enables importing and/or pasting data from excel into a Grid, having them added to the Store. Fits nicely with inline editing, so users can do a bulk import of data, tweak as necessary in the UI, and then persist/commit the data.

The approach to this I have done in a client app, and I recently heard was done by another client, was to build an import excel template which included column headers matching the grid and which enabled lining up of columns from the excel data to store fields. Expectation would be to have a context menu option for downloading an import template (I generated one with https://github.com/egeriis/zipcelx) for a grid, and then being able to copy the rows (including headers) from the excel file or dropping the file onto the grid and having the data extracted and added to the store.

**Comment by febbraiod** [comment]
Have a client app that would benefit from this feature as well

**Comment by lbwexler** [comment]
We think that the diversity of needs here, and the specificity of this argues for leaving this functionality in application code now.

**Comment by lbwexler** [comment]
We could put an example in toolbox and let this idea bake a bit more
