### ISSUE TITLE
Review/rationalize public GridModel and StoreSelectionModel getters

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2538]
It would be nice to get these a bit more consistent - 

|   Type   |    GridModel     | StoreSelectionModel |    Proposed?    |
|----------|------------------|---------------------|-----------------|
| Record   | selectedRecord   | singleRecord        | selectedRecord  |
| ID       | selectedRecordId | selectedRecordId    | selectedId      |
| Record[] | selection        | records             | selectedRecords |
| ID[]     | *missing*        | ids                 | selectedIds     |

Of course happy to discuss - can see `selectedRecords` being more awkward, if more clear/consistent. Would propose a deprecation cycle to avoid any sudden breaking change with this cleanup.

**Comment by lbwexler** [comment]
consider deprecation vs. removal.  

Removal might be better in this case, to avoid a *really* confusing intermediary state, and also lots of deprecation warnings due to the heavy use of these getters in apps.
