### ISSUE TITLE
Editable Cells in a grid should indicate that they are editable

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2553]
This could be something left up to the app developer, but it might be nice to have in the framework.
If built into the framework, it could be a config, either at gridmodel level or column level, that turns on a css rule on a cell when it is not being edited that helps indicate that the cell is editable.

The CSS could:
1: switch to pointer cursor on cell, to indicate that the cell would "respond in some way to a click"
2: put some special border or inset shadow on the cell to make it special.

The CSS could of course be overridden at the app level.

This feature would be especially useful in grids where only a few of the N columns are editable.  With this feature, new users don't have to guess or read the app docs to find out which columns are editable.

**Comment by lbwexler** [comment]
Need a css class as a handle for app changes.   Let's leave the styling to apps, however.
