### ISSUE TITLE
Implement ChildCount, LeafCount Aggregation

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2562]
Useful when we need to provide this data for rendering in Tree Grids, especially the Label Column

Another option is to just build this into the Cube API, such that a "childCount" and a "leafCount" will *always*  be available on view data (and automatically loaded into Store Fields with the same name).  In that case would just need to be careful about triggering more store/grid updates than are actually need if user does not actually want to use the counts.

**Comment by petradish** [comment]
It looks like we already have such aggregators in our admin package: https://github.com/xh/hoist-react/tree/develop/admin/tabs/activity/aggregators - should we promote these?

**Comment by lbwexler** [comment]
Hah -- and only a year ago -- I knew we had done that several times
before,  but had not realized it was in the context of hoist-react.

Great find -- yes, I think we should, with documentation.
