### ISSUE TITLE
TabContainerModel should have flag to allow showing title of active tab in browser title

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2566]
This would be useful in Hoist React's own Admin app, where I often find myself using several browser tabs to keep views of Config, Logging, Level, and Activity open.  All of the Chrome tabs say "Admin" so I cannot tell which browser tab is which view.

If the title of the active tab were reprinted in the browser tab as, for example: "Admin | Config",  this little problem would go away.

**Comment by amcclain** [comment]
Reviewed and determined that this should be easy enough to implement in your AppModel via a reaction, which could be against the main tab container model and/or other state (nested tabs, etc)

We could revisit as a Toolbox enhancement.
