### ISSUE TITLE
Disable mobile browser "swipe to go back" gesture

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2576]
We would like to be able to do this whenever `NavigatorModel.swipeToGoBack` is true in order to avoid conflict and confusion.

Right now, we intentionally avoid starting our gesture on the left-most side of the screen to avoid conflict, but would be best if we could simply disable the native browser behavior.

**Comment by amcclain** [comment]
This might or might not be possible - research required.

**Comment by lbwexler** [comment]
My research is not finding that this is stoppable in code.  Don't think this ticket is adding any value at this point.  Closing.
