### ISSUE TITLE
Missing PersistOptions typedef

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2584]
We have several persistence-related APIs doc'd as taking a `PersistOptions` object, and several more specific typedefs doc'd as `@extends PersistOptions`

But there is no `PersistOptions` in the codebase ☹️

**Comment by TomTirapani** [comment]
Took a stab at this: https://github.com/xh/hoist-react/pull/2594

A bit tricky to define, since it gets handed off to the subclasses based on which properties are provided, but at the same time I didn't think it would be useful to have a typedef for each subclass.
