### ISSUE TITLE
Dragging grid columns on ipad can result in "ghost" artifacts

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2590]
Not sure what else to call this. But it's very easy to reproduce, most easily by trying to pin a column, but any dragging of a column header that does not land perfectly within the grid headers can produce this. Only way to clear up is to completely reload in the browser:

![1F1FC0EA-E738-4DD5-9B96-650E03C32343_1_105_c](https://user-images.githubusercontent.com/15745614/129214503-b44e020a-d305-4d66-bfef-268ce0b5b0a9.jpeg)

![440CAEE5-B2A4-4E4A-822E-94AB1DD88E47_1_105_c](https://user-images.githubusercontent.com/15745614/129214529-5bb9fe64-6377-4524-960c-5c9cd6508d64.jpeg)

**Comment by amcclain** [comment]
First step would be to ensure we can repro on ag-grid's own examples - if so we could file a support ticket.

Backlogging for now given relatively minimal iPad usage, but great to have the ticket in case it comes back as a user bug report.
