### ISSUE TITLE
GroupingChooser: Level Labels should indicate they are editable

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2598]
We need to improve the display of the GroupingChooser such that users understand they can click on a level and edit it with a select box. 

Perhaps some minimal chrome, or at the very lease some mouseover chrome?   

As part of this change, we should always show the same editability, even if all levels have been selected.  Right now we are too clever, and we remove the editability completely if all levels are used.  It makes it seem like the control is broken, or we are using it wrong.

**Comment by TomTirapani** [comment]
PR opened here: https://github.com/xh/hoist-react/pull/2601/files

I went with material-style underline and a pointer cursor. On desktop, it's shown on hover (to match the remove button), and is always shown on mobile.
