### ISSUE TITLE
Add maxMenuHeight prop to Select

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2599]
It's a react-select prop that can be useful when you know you wish to allow more than the default 300px of height. 

Might as well also support minMenuHeight.

**Comment by lbwexler** [comment]
only problem here is minMenuHeight seems to govern very different behavior related to 'flipping'.

**Comment by saba-mo** [comment]
Yes, maxMenuHeight governs the height at which the menu should scroll, and minMenuHeight governs the height at which the placement of the menu should flip to the opposite side of the input control - not as related as their names suggest. Do we want to promote minMenuHeight?

**Comment by lbwexler** [comment]
I would be happy to just add maxMenuHeight at this point. No need to take
on the burden of describing the additional option in Hoist if we don't
understand it, or have a use for it.

-Lee
