### ISSUE TITLE
Icon factories should take an intent config

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2600]
Would be a shortcut for applying matching classname, e.g. instead of:

`Icon.check({className: 'xh-intent-success'})`

you could do:

`Icon.check({intent: 'success'})`

**Comment by TomTirapani** [comment]
This seemed straightforward enough to jump on:
https://github.com/xh/hoist-react/pull/2602
https://github.com/xh/toolbox/pull/520
