### ISSUE TITLE
Cell in pinned column loses separator on click/touch

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2613]
<img width="1251" alt="Screen Shot 2021-09-01 at 3 04 29 PM" src="https://user-images.githubusercontent.com/67703233/131751753-5efc211f-5a95-4daf-bdde-d737b38eac1b.png">

<img width="443" alt="Screen Shot 2021-08-25 at 1 40 53 PM" src="https://user-images.githubusercontent.com/67703233/130865389-8636cd39-0591-42d5-8114-a3513876d2e6.png">

**Comment by amcclain** [comment]
Closing this ticket - we will open a more general one around reworking grid styles to leverage AG CSS vars
