### ISSUE TITLE
Investigate if we can force onsenui to use core-js v3

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2621]
Noticed this relatively extreme warning when running `yarn upgrade`:

> warning @xh/hoist > onsenui > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

We have latest core-js 3.x as a dependency for the rest of our code - could we use [a `resolutions` block](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) in our `package.json` to force the use of v3 and avoid v2 coming in as a transitive dep from onsen? Would onsen still work / care if the newer version was used?

**Comment by amcclain** [comment]
@TomTirapani as per comment on #2629, can you pls try the same resolutions block within Toolbox and verify that a) we can get only core-js 3 in play and b) onsen still works

If so, we can leave the resolutions in hoist-react as a guide for what transitive deps should be resolved to a newer version, even if we have to copy that into each affected app for it to do anything

**Comment by lbwexler** [comment]
Thanks Tom!  Closing, Take 2.
