### ISSUE TITLE
Chart tooltip z-index too low for charts hosted in a dialog

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2622]
Specifically seeing this in a treemap in a dialog (in a client app under development), but would imagine this is the case for any type of chart. The default z-index is 3, but this leaves the TT behind the dialog (initially appears that the TT is absent entirely).

Can fix via css:

```
.highcharts-tooltip-container {
    z-index: 9999
}
```

But thought we might want to have these tooltips always at the top via hoist.

**Comment by amcclain** [comment]
FYI tried to repro on https://toolbox-dev.xh.io/admin/activity - the little chart in the bottom left has a tool to pop out into a dialog. Not seeing an issue with the tooltips - perhaps we have an override that's not being applied to treemaps, or something similar?

Agreed we should not require apps to override.

**Comment by febbraiod** [comment]
Apparently this isn't an issue if the chart uses the default tooltip. As a matter of fact in that case the 'highcharts-tooltip-container' class doesn't even appear in the DOM. Treemaps add this to the HC config:

`tooltip: {
                enabled: !!tooltip,
                useHTML: true,
                padding: 0,
                shape: 'square',
                shadow: false,
                outside: true,
                pointFormatter: function() {
                    if (!tooltip) return;
                    const {record} = this;
                    return isFunction(tooltip) ? tooltip(record) : defaultTooltip(record);
                }
            },`

If something similar is added to the Admin chart mentioned above, the problem presents itself. Think the "very high z-index" is the recommended solution: https://www.highcharts.com/forum/viewtopic.php?t=42421

Happy to add this css block if we are ok with that.

**Comment by amcclain** [comment]
(Fixed in 8e381e6eaf5661c8f6a9dbae74798684097a7030)
