### ISSUE TITLE
Admin status monitor timeout does not leave view in clear state

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2634]
Workign with client app that is having real issues and timing out loading monitor results.

Admin panel shows "no monitors configured"

should show VERY clear error

**Comment by amcclain** [comment]
If time allows, best to generalize into an audit of exception handling within admin tabs (e.g. log viewer, services, caches)

**Comment by lbwexler** [comment]
Dan -- might be an interesting, low hanging fruit.  Happy to take a look at this one with you -- let me know
