### ISSUE TITLE
TreeMap nodes often difficult to distinguish in dark theme

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2644]
Was difficult to repro in TB, but can be very visible in a current client project - if you have many nodes clustered together with similar heat color, the lack of contrasting borders causes them all to just blend together:

<img width="1703" alt="Screen Shot 2021-09-02 at 4 24 00 PM" src="https://user-images.githubusercontent.com/225806/131928368-1cad4f7c-7015-402d-b9b2-6deaa9742521.png">

**Comment by TomTirapani** [comment]
PR ready for review: https://github.com/xh/hoist-react/pull/2645
