### ISSUE TITLE
Disable user select on tablets

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2655]
We have had to do this on two of our flagship client apps. When a user holds down their finger to bring up the context menu the text on the page gets selected and it's not a good look. Is there any reason NOT to do this at the Hoist level?

**Comment by TomTirapani** [comment]
I think this makes sense to do at the hoist-level for tablets. Interesting to note that Onsen does this for us for mobile, so clearly a precedent of disabling user-select for touch screens

**Comment by amcclain** [comment]
Agreed - let's add the rule for the next Hoist release
