### ISSUE TITLE
Expose 'Raw' Release Notes 

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2678]
Would be nice to have an easy option to get *all* release notes/changelog entries (even if in json format).

Was troubleshooting a client app that is filtering out release notes for end-users and needed some technical items.

Not a huge priority by any means.  Could be admins only, or all users.

**Comment by amcclain** [comment]
Worth an app feature, vs. just looking in source control?

If we had a standardized config for a source control link that might be a useful thing generally to list in Admin > About, add link to source CHANGELOG.md in changelog dialog, auto-link build IDs, etc

**Comment by lbwexler** [comment]
I was thinking the same as I completed the ticket.  Totally fine with
closing.

Good to keep in mind easier links directly to source control, although that
hardly seems like a high priority.
