### ISSUE TITLE
Allow developers to enhance loadSpec with Component specific flag

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2688]
Would be very useful if I could write:

myModel.loadAsync({mySpecialProp: true}) or
myModel.refreshAsync({reconnecting:false}) and have that flag available for the model's doLoadAsync implementation

Think things used to work this way, and it was lost when we added the LoadSpec class

**Comment by amcclain** [comment]
Agreed - wanted the same recently for some use case or another.
