### ISSUE TITLE
Default Sorting should always start with sort DESC

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2699]
For finance apps, its typically desired to see the largest numbers.  This is reflected in our sorting order, and works great when `absSort: true` on a column:

`static DEFAULT_SORTING_ORDER = [
        {sort: 'desc', abs: true},
        {sort: 'asc', abs: false},
        {sort: 'desc', abs: false}
    ];
`

But for some reason (probably just related to our implementation) we don't start with desc when sorting columns with `absSort:false`.  This is a mistake and annoying for unsigned values like exposures, notional and risk.

**Comment by TomTirapani** [comment]
Don't we start with 'ascending' because of alphabetical string sorting? I think if we were more stringent about defining / determining field types we could have different default sort order for numerical / string columns?

**Comment by lbwexler** [comment]
yes, of course -- great point, and apologies for forgetting this.

We should definitely take advantage of field type info where we have it.  No need to require it, but getting better default sort order would be one of the benefits of doing so.

**Comment by amcclain** [comment]
Interesting - it's a hard call, as I 100% understand why many finance values would want to default to DESC, but for numbers generally it might be surprising in other cases such as counts, numeric IDs, prices (I think), etc.

We have `Column.sortingOrder` already - would it help if we made it easier to set this with additional preset statics, `ABS_DESC_FIRST`, `DESC_FIRST`, `ASC_FIRST` or something like that?

**Comment by amcclain** [comment]
Discussed and first step is to define additional preset constants to make it easy for app-level col defs to choose an option based on business considerations.

But also agreed that it would on balance be an improvement to default NUMBER and DATE fields to desc-first. That could be done at the same time or in a second pass if it complicates.

**Comment by lbwexler** [comment]
@febbraiod -- let's try to knock this off in the office tomorrow?  Happy to take a look with you
