### ISSUE TITLE
Harmonize mobile button props with desktop where possible

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2716]
Mobile button props are currently driven by the underlying Onsen component and are somewhat obscure. Would like to take any easy wins at supporting desktop props where we can translate into corresponding onsen button props - e.g. minimal, outlined.

**Comment by TomTirapani** [comment]
Had a couple of spare cycles so took a stab at this - it's a long-standing gap that would be great to harmonize.
https://github.com/xh/hoist-react/pull/2792
https://github.com/xh/toolbox/pull/542
