### ISSUE TITLE
FilterChooser scrollbar is not right aligned

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2728]
I believe this is a regression in filterChooser, where the scrollbar appears to the left of right elements (like the X and favorite icon buttons):
<img width="619" alt="Screen Shot 2021-10-08 at 8 55 41 AM" src="https://user-images.githubusercontent.com/49966727/136561689-2f2b82b2-d4e3-4f4e-b1fb-7be34070cbaf.png">
<img width="896" alt="Screen Shot 2021-10-08 at 9 01 55 AM" src="https://user-images.githubusercontent.com/49966727/136561690-e3286c18-1be9-48f7-97af-8e4189e2972b.png">

**Comment by TomTirapani** [comment]
I'm not sure this is a regression - I *think* the scrollable area of react-select has always been to the left of the clear affordance / dropdown indicators. Last year we added behaviour to absolutely position the indicators _**if you provide a height**_, the intention being to support 'textarea' like multi-select: https://github.com/xh/hoist-react/pull/2156/files. But this only applies for fixed height Selects, and not the more common 'inline' usage above.

We could discuss changing the behaviour to *always* abs position the indicators, but this can negatively affect how the tags wrap and you can end up with icons floating over the tag. This tradeoff makes more sense in the 'textarea' usage where the indicator takes up a relatively smaller area and thus does not warrant reserving the entire right edge.
