### ISSUE TITLE
Persist more options in activity tracking tab

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2729]
It would be nice to persist the activity tracking options that are not currently persisted:
- day range button value (I often want to just look at 1 day, for example) 
- max rows value
- chart metric
We are persisting filters and grouping, so why not take it a step further?

**Comment by amcclain** [comment]
Closing as a general cleanup - I don't think we've felt a need for these, and there are other activity tracking enhancements we could take on first.
