### ISSUE TITLE
FilterChooser autocomplete misfires when entering second query clause

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2732]
Can replicate using the FilterChooser @ https://toolbox-dev.xh.io/app/grids/columnFiltering

* Add a "City" filter - e.g. "City = Boston"
* Type "comp" to trigger the "Company" field-level suggestion and select the first option (the field itself)
* Filter control ends up with a committed tag reading "Company" and the word "Company" again after that, still editable in the control:
<img width="608" alt="Screen Shot 2021-10-10 at 6 45 19 AM" src="https://user-images.githubusercontent.com/225806/136698538-56547728-619a-47f6-a47d-4dc9f8fc94d6.png">

(Observed in a client app that's _not_ using grid column filtering - just the filter chooser.)

**Comment by TomTirapani** [comment]
Taking a look at nice now - can reproduce in Toolbox
