### ISSUE TITLE
Form field validation message should provide better default if `FieldModel.displayName` is null

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2746]
Contrived Example:
<img width="667" alt="Screen Shot 2021-10-21 at 11 50 19 AM" src="https://user-images.githubusercontent.com/49966727/138313708-f8a4f16b-8861-4e5c-a560-991023c626f5.png">

`displayName` for this field is `null` to hide its label by default. However, the required validation message that appears stringifies its null value.

**Comment by lbwexler** [comment]
Looking at the code required, more carefully I am having second thoughts about this ticket.  Given that we default the display name to a "reasonable" value, it seems like we don't really consider it to be a nullable thing.   Handling null puts a undue burden on our validators, and maybe other code as well.  

This seems like a bad pattern for clearing out labels.  We support explicitly setting the labels to null in the field itself via the `label` prop:

/**
     * Label for form field. Defaults to Field displayName. Set to null to hide.
     * Can be defaulted from contained Form (specifically, to null to hide all labels).
     */

@Petra - can you explain the use case a bit better?  Is there a reason you can't knockout the label from there?

**Comment by petradish** [comment]
Hi @lbwexler! This issue came up from setting {displayName: null} on the FieldModel config instead of clearing out the label prop on FormField, as what should have been done. @amcclain suggested that we default the displayName to something more user friendly than 'null' in the case that a developer does null out the display name. 

I agree with you though that FormField.displayName should never be null. Could we instead default the displayName to the generated display name if it is passed in as null?

**Comment by lbwexler** [comment]
It's just a fair bit of code that would need to occur in every validator
(and app defined validator) to workaround a misuse of the API.

If we think setting 'displayName' to null is going to be a common mistake,
I almost would rather warn on the console, pointing people to the "label"
prop....
