### ISSUE TITLE
Support third `onClose` action in MessageModel

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2758]
MessageModel currently supports 2 actions: confirm and cancel. 
When a user closes out of the dialog by clicking the backdrop or hitting ESC, it triggers the `onCancel` action, which could be an unexpected behavior other than simply closing the dialog and doing nothing.
Perhaps as a default, the onClose = onCancel, but there should be a way for an app dev to specify them as separate callbacks.

**Comment by lbwexler** [comment]
Think we will want to think carefully about the default of this as petra mentions.

There may be a tradeoff between simplicity of the API, and making this a non-breaking change.  I think if we want it to be a non-breaking change we will indeed need to have `onClose` defaulting to any `onCancel` provided.  Not the worst thing in the world, I suppose, but will need to be documented.
