### ISSUE TITLE
Mobile and Desktop column chooser should consistently render displayName values

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2759]
In a client app, we noticed that when specifying a displayName on a column as html (using fmtSpan) the column chooser on desktop would happily accept that, but on mobile we would see the raw html in the GUI.

**Comment by amcclain** [comment]
Where you looking to set Column.displayName to a string (containing HTML) or to a React element?

Note that the field is doducmented (currently only via the ctor param) as taking a String. We could revisit and broaden out to allow elements - we'd just need to ensure we didn't have any other assumptions there around the type.

(In contrast, `Column.headerName` *is* currently doc'd as taking an element.)

Agree though that the handling should be clear and consistent, and understand the use case for being able to use some formatting in certain contexts here (e.g. for labels)

**Comment by febbraiod** [comment]
95% sure we were just trying to use markup and no elements. I guess the ticket is less about what the displayName should accept, but rather that the mobile and desktops choosers shouldn't be different if we can help it. Would be best if they both could render markup
