### ISSUE TITLE
Rename the Record class

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2762]
A language-level `Record` class is in the pipeline for JS - see https://github.com/tc39/proposal-record-tuple - and is already part of TS - https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type

As much of a pain as it would be, I'd vote for renaming the Hoist `Record` class to something else to avoid confusion / collisions. This would also allow us to get more help from IDEs when using `{Record}` in JSDoc annotations, which I find never actually resolves to the Hoist class due to the above.

On the bright side, I doubt the class is directly used and imported very often in application code - Records are almost never constructed directly.

We could go with something like `StoreRecord` or `DataRecord` (or even `XhRecord`) for the class name, allowing us to keep getters on other core classes like `allRecords` or `selectedRecord` unchanged, as well as app code referring to `rec` or `recs` in local vars.

My hope is that this could be a quick, find-and-replace effort in Hoist w/minimal or no app changes needed. 

Finally, we should consider if there are any other public API classes with names that are very general in a way that's more of a liability than we intended.  Not to pick on the data package, but `Store`, `Cube`, `View` all come to mind. 

One way to assess this is to add a JSDoc annotation using a Hoist class name as a type (e.g. for a function param or return), where that class has _not_ been explicitly imported into the file where it is used. Cmd+clicking on the type in the JSDoc comment will show you how/where the IDE resolves it. We certainly don't need to let whatever heuristics IntelliJ happens to use drive all our decisions here, but it's a decent indicator IMO, and practically speaking has a real effect on developer productivity. Even if you aren't using JSDoc annotations in app code, docs for Hoist functions specifying a return of `Record` or `Record[]` would likely work better.

**Comment by lbwexler** [comment]
👍🏻 on changing Record to StoreRecord

Skeptical of changing Store and Cube and View.

**Comment by amcclain** [comment]
Sounds good to me - Record is the one with the concrete, upcoming conflict with a build-in name, so happy to focus on that.

**Comment by dsilberger** [comment]
Pushed up a branch `record-refactor` making the change from `Record` to `StoreRecord`. Added a breaking change notice in CHANGELOG.md. I'll open the PR and flag for review.
