### ISSUE TITLE
Improve UX/discoverability of DashContainer add menu

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2768]
User's have a hard time remembering how to add new views to a dash container, since the only method for non-empty containers is to know to right-click next to an existing view tab. Would like to bring back the add button we used to render in the empty tab header space as an optional feature, which could be toggled on or off at runtime so apps can support a locked/edit mode for dash containers.

**Comment by amcclain** [comment]
Another option could be to bring back the inline add button, but only have it be visible when user's mouse is hovered over the tab strip
