### ISSUE TITLE
Tabs/Models should have a way to prevent load on render

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2773]
We have client apps where it is desirable to only ever call loadAsync/doLoadAsync when the user requests it via button or similar. As of now the first time you visit a tab the developer has no choice in the matter. A workaround is easy enough to implement but seems this should be part of the Hoist api.

**Comment by TomTirapani** [comment]
I may be wrong, but I think you could use `RefreshMode.SKIP_HIDDEN` for this? (Not 100% sure)

**Comment by febbraiod** [comment]
I believe SKIP_HIDDEN gets us part of the way there, but the model will still attempt a load on first visit (i.e. refresh isn't the only problem here). Admitted I didn't investigate beyond reading the description. I can give it a try and update the doc string if it works.

**Comment by febbraiod** [comment]
Not sure we need this ticket after all. we can short circuit the initial load by checking loadSpec.loadNumber. Probably good enough?

**Comment by amcclain** [comment]
Workaround described above is the right approach
