### ISSUE TITLE
Copying a cell should take the same value as exportValue

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2779]
As seen in a client app, certain cells cannot be properly copied/pasted if, for example, the value is an object or includes html. Column.exportValue can take an alternate field name or call a function that processes a value before exporting, and this should be the same value that is copied.

**Comment by lbwexler** [comment]
Just found this very promising link on the ag-Grid site.   Not sure if were were aware of this.

https://www.ag-grid.com/react-data-grid/clipboard/#processing-clipboard-data
