### ISSUE TITLE
fmtNumber output not correct on decimal portion of large numbers with high precision

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2780]
This can be seen in toolbox's https://toolbox.xh.io/app/other/numberFormats page:

Format `123456000000000.1` with precision `6` and zeroPad `true`.

Expected result: `123,456,000,000,000.100000`
Actual result: `123,456,000,000,000.093750`

Petra and I think the root cause is a bug in the [numbro](https://github.com/BenjaminVanRyseghem/numbro) lib that hoist-react uses.

It looks like other users have come across this issue with [numbro](https://github.com/BenjaminVanRyseghem/numbro), and submitted PRs to fix this.
(one example: https://github.com/BenjaminVanRyseghem/numbro/pull/580)
but numbro is generally slow with PRs & releases.

Most solutions point to incorporating [bignumber.js](https://mikemcl.github.io/bignumber.js/) to fix this.  Numbro already uses bignumber, but not to fix this issue (yet).

**Comment by amcclain** [comment]
You can confirm it's numbro @ https://numbrojs.com/try-me.html?lang=en-US&value=123456000000000.1&format=%7B%22mantissa%22%3A6%2C%22optionalMantissa%22%3Afalse%7D

**Comment by cnrudd** [comment]
I fmtNumber is called without `formatConfig`, we only end up specifiying three 
numbro configs:
```
    config.thousandSeparated 
    config.mantissa 
    config.trimMantissa 
```

I think it's worth trying to do those 3 functions ourselves, or pull in bigNumber to do them.  I already have thousandSeparated done.

**Comment by lbwexler** [comment]
I am going to close this ticket, as I think formatting issue is really just a single  manifestation of the bigger issue that Hoist does not provide support for BigNumber (now a built-in JS class).  This includes the data package, as well as number formatting. 

 Its not something clients have needed or wanted yet, although cyrpto projects are very likely  to want it.
