### ISSUE TITLE
Create keyboard shortcut to refresh app

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2781]
A client has requested a keyboard shortcut to refresh the app instead of the entire browser.

**Comment by amcclain** [comment]
Hi @saba-mo - this can be done now via Panel hotkeys support - see the Toolbox example @ https://github.com/xh/toolbox/blob/cd26f8ff2f0461a72fcf4c643e351b3971903136/client-app/src/desktop/App.js#L40

I don't think this is necessarily general enough to install by default - some apps might have a different model for getting data (websocket push, static data loaded once on start, etc).  But it should be very easy to implement for any app that needs/wants the same, and I would suggest we stick with shift+r as our standard hotkey for a (r)efresh

**Comment by saba-mo** [comment]
Thank you, @amcclain, this is very easy to implement in the client app!

**Comment by amcclain** [comment]
After discussion we are thinking this would be a useful built-in - see https://github.com/xh/hoist-react/blob/fd38d189ddc79b7cfe06282918a851339001df94/desktop/appcontainer/AppContainer.js#L151
