### ISSUE TITLE
Re-examine equality check in createRecord method

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2786]
At the moment there is check (by reference) of the new raw data being passed to createRecord against the cached raw data on an existing record that has the same id. Even if the newly passed data has mutated fields, the existing record is reused. This is creating issues in a client app where, to work around this, the new raw data needs to be cloned, but the clone itself is causing issues (WRT LocalDate equality).

I have a number of ways to fix in my app, but have heard rumors of others encountering similar problems. Also in discussing with John H. he was easily able to think of other use cases where the current set up would produce problems.

We could:

1) Not do this check at all
2) Potentially do a more detailed equality check using fast deep equals?
3) Add a flag in the API to elect to always create to new record when loading data regardless of raw data equality

**Comment by amcclain** [comment]
These concerns are absolutely core to how the records and the data package work - we don't want to be in the world of workarounds or fixes.  Let's be sure to review with @lbwexler ASAP to understand the patterns at play here.

Also any issues with LocalDate equality indicate a potential different problem w.r.t. however you are doing cloning or handling of LocalDate - it's important that the static factories there be used to maintain the 1 class instance per date behavior expected by that clas..

**Comment by amcclain** [comment]
Had a bit more time and found #2702 - an issue I had put in a while ago on the same topic.  Good to discuss these use cases.

**Comment by febbraiod** [comment]
"Also any issues with LocalDate equality indicate a potential different problem w.r.t. however you are doing cloning or handling of LocalDate - it's important that the static factories there be used to maintain the 1 class instance per date behavior expected by that class"

Yup totally get this. We are cloning a large array of objects wholesale right before they are fed into a Hoist cube in order to prevent this issue with the records. Rather than loop through each object and look to not clone but rather reuse each localDate. Lee and I discuss and I went with comparing the underlying strings for now as both a cleaner way to workaround the issue (in terms of having less code) and also as faster solution in terms of app performance (although I don't rightly know that performance would be a concern or not).

I have a comment in place that clearly explains the problem with the hope to remove once the Hoist code is revisited. Let me know if somehow there is a danger here that I am not perceiving.

**Comment by amcclain** [comment]
Closing to continue tracking in #2702
