### ISSUE TITLE
Select's queryFn should have an option to fire without the user having to provide any input

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2796]
This is a nice-to-have for a large client app that is under construction. The previous iteration of said app has an inline editor that lazily loads its options when the select editor is opened (without the user have to provide any params). 

I think we could just pre-populate the options as an acceptable workaround but we would not pick up any newly added options for the external service without a refresh.

**Comment by amcclain** [comment]
Let's revisit after or as part of #3426
