### ISSUE TITLE
Column.exportFormat provided as a function breaks CSV

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2797]
exportFormat is primarily an excel concept.  CSV (and clipboard) typically ignore it 

However, if you specify it as a per-cell function, it will actually break CSV exports, and the column will get exported as all null values.

We should also clarify what exportFormat applies to in our documentation.  Might have been more straightforward if we had called it `excelFormat`!

**Comment by amcclain** [comment]
👍 on renaming to `excelFormat`

**Comment by TomTirapani** [comment]
PRs here:
https://github.com/xh/hoist-react/pull/2848
https://github.com/xh/toolbox/pull/544
