### ISSUE TITLE
FilterChooser renders inner scrollbar even when value tags do not wrap

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2798]
This appears to be a css issue in Chrome 96+.  Does not happen in Chrome 95.
This does not happen in our select component.

![image](https://user-images.githubusercontent.com/2573928/144311867-c1254c0f-0560-4562-aed9-ccc1ad0c254a.png)
![image](https://user-images.githubusercontent.com/2573928/144312087-467e59f0-1b23-46ca-a80e-18a4e9ccccc6.png)

**Comment by amcclain** [comment]
Reported by @haynesjm42 today - I've seen this also and have been meaning to file this ticket. Colin / John - if either of you have a few cycles to look this week please comment or chat so we don't dupe up the work - hopefully a quick style fix, but with React Select you never know...

**Comment by cnrudd** [comment]
This issue exists on Safari 15.1 too.  So, it is not strictly a Chrome version bug, as I previously thought.
The artifact is the vertical scrollbar.

Definitely, if these lines are tweaked:

```
hoist-react/desktop/cmp/input/Select.scss
// Ensure multi-value selects don't overflow vertically in the toolbar
.xh-toolbar {
  .xh-select {
    &__value-container--is-multi {
      height: 28px;
      overflow-y: auto !important;
    }
  }
}
```
The scrollbars go away.  But those lines are needed for their specified purpose.
It's the lineheight of the element inside that is making the element too big.
![image](https://user-images.githubusercontent.com/2573928/144464814-99c03b8e-9109-44f7-afbc-d65c33946dbf.png)
and by just a smidge over 28.

Lineheight is coming from blueprint.css:
![image](https://user-images.githubusercontent.com/2573928/144464975-de30371d-96d0-460f-a48d-14c8b561254e.png)
Will look into whether that changed recently.
