### ISSUE TITLE
Copying a row to the clipboard will always copy the column group headers as well

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2801]
This behavior is seen whether selecting 'Copy' or 'Copy with Headers' from the grid's context menu, and can be seen in the Grouped Columns example in toolbox: https://toolbox-dev.xh.io/app/grids/groupedCols. 

This is already in AG Grid's pipeline as a new feature to allow/suppress the copying of column group header values (AG-5501).

**Comment by amcclain** [comment]
We could skip this issue entirely by handling the preparation of text to copy ourselves, instead of leveraging the ag-grid provided API.

**Comment by saba-mo** [comment]
Background on where AG Grid stands with this feature request: 

AG-5501 [Clipboard] Allow copySelectedRowsToClipboard and copySelectedRangeToClipboard to allow/suppress the copying of column group header values

https://github.com/ag-grid/ag-grid/issues/4550

**Comment by saba-mo** [comment]
This is still in the AG Grid Pipeline but it also appears to have been resolved - I tested in toolbox and a client app. I don't believe we decided to stop leveraging the ag-grid provided API, but it looks like we can close this ticket.

**Comment by lbwexler** [comment]
Closing -- I can confirm Saba's finding -- working for our menu items!
