### ISSUE TITLE
Charts that re-render while in fullscreen shrink in size

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2803]
As seen in a client app, viewing a chart in fullscreen mode and then changing the date range and re-rendering the chart causes it to shrink down to the dimensions of its parent element. A contrived toolbox example can be found in the portfolio app example on this branch (use range selector buttons to see behavior): https://github.com/xh/toolbox/tree/fullscreenChart

![Screen Shot 2021-12-02 at 12 12 55 PM](https://user-images.githubusercontent.com/67703233/144495816-6faa5a94-1f01-47f7-b31b-18900d8f57f4.png)

**Comment by amcclain** [comment]
Completing #2753 would allow this menu option to be omitted for use cases that trigger this bug. We don't want to invest too much in trying to change/patch the built-in behavior here.
