### ISSUE TITLE
Gridmodel should have a more stable isEditing flag (in addition to existing flag)

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2806]
Use case is an editable grid where user edits should _eventually_ trigger a call to the server. 

Currently the "isEditing" flag flips back and forth between true and false every time a cell (or row in fullRowEditting mode) is entered or exited.

When tabbing through cells/rows, from a user perspective, editing has never stopped and the server call should not be made.

There are other apps that rely on the existing behavior (they need to do updates on each cell edit completion). Suggesting a second flag (gridIsInEditMode?) that mimics the behavior of the existing flag BUT is debounced such that the mode does not change in the milliseconds that occur between editing one cell and the next. Rather only after the mode has "settled" on one state or the other.

In the app in question we can workaround by debouncing the handler that the reaction calls. But we thought this was worth consideration for a change in Hoist.

**Comment by amcclain** [comment]
I think I understand the ask here (and it makes sense) - but how would the user signify in this app that they are "done done" with editing? Sounds like they are tabbing from cell-to-cell - is the idea that they would click somewhere else to avoid activating the next editor, or reach the end of the line, or end of the grid?

To put it another way, how can we define when "the mode has "settled" on one state or the other" in a general way?

Seems possible that this use case might call for a more explicit approach where once the user starts editing a button lights up indicating that there is dirty local state and prompting to user to press it to flush the changes when they are ready - ala some database editor tools. But I realize that might also seem somewhat clunky or old-fashioned. Happy to discuss / brainstorm - would be great to look at the particular app together.

**Comment by febbraiod** [comment]
I think the mode has settled after it lands in one place or the other for any amount of time. If it's in the cell we're editing. If it's not we're not.

The user can signify they are done done by either clicking somewhere else, or hitting return or tabbing out of the end of the grid. Point being if a cell is immediately active for editing after the previous cell is exited. We're NOT done.

Glad to look together whenever you have the time.
