### ISSUE TITLE
GridFilter enhancements (from client call)

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2816]
We discussed a few enhancements to our column filters with a client that we'd like to implement:

- [x] Make operator selector more obviously a control that the user can adjust - right now it looks a lot like a fixed label. Use text labels instead of mix of text/mathematical operators, avoid overly abbreviated text labels (e.g. begins -> begins with"
- [x] Autofocus the primary input.
- [x] Revise bottom toolbar - make toolbar full size, remove "Cancel" and "Close" options in favor of user clicking outside the control to dismiss (in line with recent `GroupingChooser` change), move "Clear" button to the right, where it will either show up on its own or next to an "Apply" button (based on `GridFilterModel.commonOnChange`). Consider labelling those buttons "Clear Filter" and "Apply Filter" for clarity, match with Excel, and to make bigger target for mouse click.
- [x] Allow dev to set the default operator in `GridFilterFieldSpec`
- [x] Don't show the And/Or buttons until there is more than one clause in the query. For the very common use case of a single clause, they are just extra noise and might be confusing (e.g. "does this mean and/or with column filters on other fields?")
- [x] Not mentioned on call, but I would like to explore moving the Add button down below the last completed query clause, where it seems like it would more naturally flow and be more readily available to click.

**Comment by lbwexler** [comment]
Bravo: 6 for 6!

**Comment by amcclain** [comment]
Filed #2841 for the additional request to autocomplete from available values within the custom tab (when available). 

This seemed like a potentially very different amount of work, and we'll need to review further to determine the complexity cost / possible implementations.
