### ISSUE TITLE
Support scaling of value in NumberInput

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2821]
I would like NumberInput to support some kind of scaling factor when converting between the internal/external value. This is specifically to provide a more intuitive input for percentage values, without requiring apps to write code to perform the scaling.

This also would address a use-case I currently have for wanting to enable column filtering on a percent column without needing special scaling in the column renderer. Currently user would need to input `0.3` instead of `30` to have the filter value be `30%` in terms of what they are seeing the grid itself using the default percent renderer.

**Comment by amcclain** [comment]
Agree - this would link up with the 100x default behavior of fmtNumber (https://github.com/xh/hoist-react/blob/f0d5fdf9fcd1799b2737d535593f63504e985fe6/format/FormatNumber.js#L183)

Mentioned a while ago in #2053 but I would vote for a dedicated prop.

**Comment by lbwexler** [comment]
@haynesjm42 -- Do you think you could take a look at this for v46?  would like to get this done

**Comment by haynesjm42** [comment]
Yes will take a look at this today
