### ISSUE TITLE
Grid ValuesTabModel extracts values from store, even when not enabled

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2843]
We've discussed this when we first implemented grid filters, I believe, but now might be a decent time to revisit.

Within `ValuesTabModel`, we are doing some non-trivial work to extract and compute a list of values from the source store/cube, reconcile those with current filter values, and load into an inner managed GridModel.

All of this happens even when `fieldSpec.enableValues == false`. From what I can see, this flag only effects the default tab shown + visibility of the tab switcher within the header dialog. 

Can we (safely) avoid doing this values extraction - or even avoid creating a `ValuesTabModel` altogether within `ColumnHeaderFilterModel` - when this feature is disabled? We don't have any expectation that it can be "switched on" post-construction, so that should ease matters a bit.

**Comment by TomTirapani** [comment]
PR here: https://github.com/xh/hoist-react/pull/2844
