### ISSUE TITLE
`LocalDate.toString()` should be yyyy-mm-dd

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#2845]
This change will bring the Hoist-React framework's LocalDate implementation in line with other implementations that follow the ISO-8601 standard:
https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html
https://nodatime.org/2.2.x/api/NodaTime.LocalDate.html
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

Default output format will change to yyyy-mm-dd
Default input formats accepted by the class' get method will be: yyyy-mm-dd && yyyymmdd

**Comment by lbwexler** [comment]
Found the java link I looked at that made me feel that the format with out the hyphens was fully standard

BASIC_ISO_DATE is first, just by alphabetization, but the name is certainly as inviting as the ISO_LOCAL_DATE (that we are proposing moving toward)

https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
