### ISSUE TITLE
Select Button should relabel (or skip) "Create XXXX"

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2869]
The "Create [my option]" dropdown item is a bit problematic: 

 + When there are no options,  is there a way we could skip the "create xxxx"  menu, and just have the enter/focus loss cause the pending value to be automatically created?

+ Should we default the "Create" prefix to something that doesn't imply saving data?  Skip the prefix?

We wanted to explore this -- probably only want to do if is low-hanging fruit, and doesn't add a lot of complexity to this already complex component.

**Comment by TomTirapani** [comment]
Took a look at this - unfortunately, it seems there's no way to the skip the `Create "xxxx"` menu option. You can prevent it from showing by setting `formatCreateLabel` to a no-op function, but without the option in the list, the user can't actually add the option. The user needs to pick the option from the list for the new item to actually be created.

If we want to change the prefix, I would vote for `Add "xxxx"` or simply `+ "xxxx"`. I'm not sure about skipping the prefix entirely - without any prefix at all, its too easy to confuse the new option you're adding with being an existing item. There are certainly use cases where such a distinction doesn't seem important, but then there are other cases (e.g. groups in the config admin) where it's important.

**Comment by lbwexler** [comment]
Got it tom -- appreciate you taking the look and happy to drop this ticket now!

Given that we actually have a well-documented `createMessageFn()` prop,  I think no need to change the defaults.
