### ISSUE TITLE
FormField does not need to setup tooltip popover if no inner input item

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2883]
Creating a formField with `minimal:true` (e.g. via `form.fieldDefaults`) but no `item` input still sets up a tooltip wrapper w/associated complex inner DOM structure.

Is there any use case for this, or should we skip this step if we know we are in readonly mode and using readonlyRenderer? Would we ever want to show validation errors on a readonly field? I don't _believe_ the tooltip has any other purpose.

**Comment by lbwexler** [comment]
Are we sure that we would never want to show a validation error for a read-only field?  What if the record was somehow invalid, but currently "locked" against editing?  What are we we trying to gain from this? 

We could potentially hedge our bets, and in the case of a read-only display, only show the tooltip if `displayNotValid` is true?  That might remove the extra cruft for the large majority of case, but keep the door open for a read-only validation display.

**Comment by lbwexler** [comment]
(I assume for the editable fields we want to always include the tooltip wrapper for stability -- but for this corner case on read-only fields, maybe the calculus is a little different?)

**Comment by amcclain** [comment]
In the particular app that prompted this - CryptIQ - we moved from having a form with a mix of RO and RW fields to a RO versions, so we could remove the `minimal:true` config and now have no extra layout.

Given that and some of the uncertainty around need to support validation on RO fields, let's shelve this for now. I will close the PR, and we can always come back to it if/when this comes up again.  Thanks for taking the time to look at it, Tom.
