### ISSUE TITLE
Update to FontAwesome v6.0

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2889]
Should be a drop in, enabling access to a bunch of new icons. Existing icons have been tweaked to varying degrees - we'll want to give the ones we use often in Hoist built-ins to ensure they are looking reasonable.

See https://fontawesome.com/docs/changelog/

Tried this locally today and ran into one strange issue with the `faThumbtack` icon, of all things. They have a mixed-case alias (`thumbTack`) and something with that def. in particular throws. Reported to FA support and will update this ticket with any response. Was not clear how to workaround at the moment...

This update also includes support for a new "thin" style - we can see how that looks and if we want to include that variation in our big set of included-by-default icons.

**Comment by amcclain** [comment]
FA support having trouble replicating. They asked for a reproducible test case, but I wasn't sure how to proceed to create one.

There is some chance it relates to https://github.com/xh/hoist-dev-utils/blob/4ec3a3c1c62ad771b702c85ded163f62d8d872a7/configureWebpack.js#L443

**Comment by TomTirapani** [comment]
Wonder if this will be improved with https://github.com/xh/hoist-dev-utils/issues/33? 🤔

**Comment by TomTirapani** [comment]
So I took a look at this... doesn't look like using the updated hoist-dev-utils or unwinding the tree-shaking helps. This is definitely a bug on the FA side... they are using inconsistent casing for the imports / filenames themselves.

It took some digging (15k+ issues!), but I found this issue:
https://github.com/FortAwesome/Font-Awesome/issues/18661

And this one, in which they say they'll fix for 6.1.0:
https://github.com/FortAwesome/Font-Awesome/issues/18800

I think we just have to wait for them to fix in a patch release. Will keep an eye on it,

**Comment by TomTirapani** [comment]
Tried again using the recently release v6.1.1, and the import issues around `faThumbtack` have been resolved.

I did a side-by-side comparison of the bundled icons against toolbox - almost all of them have changed, but the changes are subtle and shouldn't be too noticeable unless you're looking out for them. The following icons had the most pronounced changes, but even with these I think most apps should be fine to take the upgrade:

- boxFull
- eye
- fileCsv
- filePdf
- folderOpen
- gauge
- impersonate
- mobile
- news
- phone
- pointerUp
- shield
- unlink

**Comment by petradish** [comment]
magic, too!
