### ISSUE TITLE
Checkbox does not fit in filterable column header

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2900]
See screenshot from toolbox/grids/columnFiltering: https://toolbox-dev.xh.io/app/grids/columnFiltering
![Screen Shot 2022-03-03 at 2 19 01 PM](https://user-images.githubusercontent.com/67703233/156663169-08262019-4ef9-420a-8082-919a47f7d14c.png)

**Comment by lbwexler** [comment]
Looking better in latest version of Hoist.  Closing....
