### ISSUE TITLE
Option to access column filter menu via right-click, hide menu button in header

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2901]
The header button takes up a lot of space and makes for a busier look for the grid, would like to be able to hide that menu button and access the column filter popover via right-clicking on the column header

**Comment by lbwexler** [comment]
John can you help us understand the priority of this?  Client request?  Would be great to see the app

**Comment by haynesjm42** [comment]
Not urgent, was for a client app with a lot of sensitivity about column width (long headers, consistently 3-4 digit numbers as cell contents) so trying to be as optimal as possible with the width to make autosizing work well and still have readable headers. Happy to show you the use-case in question anytime.

**Comment by amcclain** [comment]
@haynesjm42 - thinking we might close out this ticket now that we have the new `GridModel.headerMenuDisplay` config added in #3320 - WDYT?

**Comment by haynesjm42** [comment]
Yep I agree, fixed by #3320
