### ISSUE TITLE
Support for View row counts

### ISSUE THREAD

**Issue by petradish** [xh/hoist-react#2906]
Applications using the Cube currently define their own custom row count labels in order to show row counts for leaf rows and aggregate rows. `Store/GridCountLabel` is able to count all rows (aggregates + leaves) when `{includeChildren: true}`, but many clients are more interested in leaf counts (filtered and unfiltered).

I think we should create readily accessible getters for aggregate and filtered leaf row counts on View and possibly enhance our current gridCountLabel to bind to a view and have options to show aggregates or leaves. In one client app, we've created a custom component that reports on all 3 row counts using a tooltip:

![Screen Shot 2022-03-09 at 4 16 16 PM](https://user-images.githubusercontent.com/49966727/157537441-90dc5945-df19-4402-9a23-51e1a837db10.png)

**Comment by lbwexler** [comment]
Maybe split the difference and provide the convenience getter on views to make this a bit easier for applications?

Seems like a flag on the control to toggle what it shows might also be useful.

Multiple row types seems like a tough one to generalize, especially w.r.t to what the app is using to refer to the different row types.
