### ISSUE TITLE
LocalStorageService will throw app startup if it reports as unavailable

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2917]
LocalStorageService throws if the `store2` library we use reports its API as "fake" - meaning that it has determined that the browser does not support LS:

https://github.com/xh/hoist-react/blob/3470904793f57fba16b048209399a7e582341ab2/svc/LocalStorageService.js#L64

Unfortunately, this code path is exercised by `PrefService` on init - and possible others - which means that an app will be unable to start in any capacity if the library reports LS as fake.

We had a client error report where this happened (for unknown reasons) for a particular user. Clearing local storage in the user's browser resolved the issue, which is itself mysterious. We are following up to see if we can get more info on what could have caused this specific case, but it seems clearly problematic to prevent _any_ app from starting in this condition - even if LS would not be used or essential for the app to function.

**Comment by lbwexler** [comment]
I agree -- we coincidentally have an issue where we can't really rely on LocalStorage in a Cordova app we are building for a client.   It's a different problem -- the LSS will init fine, but it will not retain the value across having the App shutdown.

So one question is whether we want to make the use of LocalStorage 'optional' to apps, to give us a bit more flexibility.  Right now Hoist requires LocalStorage for the BannerService, as well as the 'Loop preventer" in AjaxService where we reload the app to force reauth in non-sso situations.  For the former, we could just move the Banner handling to a server-side preference.  For the latter, am not sure we have a *great* solution, other than writing to a cookie
