### ISSUE TITLE
Upgrade to React v18

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2932]

**Comment by TomTirapani** [comment]
Opened a draft PR for this, since there are console warnings from Blueprint about it using `ReactDOM.render` for context menus and toasts.

**Comment by lbwexler** [comment]
we may want to link this to blueprint 4.x

**Comment by lbwexler** [comment]
We decided to wait for v50 for this

**Comment by TomTirapani** [comment]
Do we still want to wait for this, given that Blueprint has delayed fixing the warnings until v5:

https://github.com/palantir/blueprint/issues/5212

FWIW, the warnings go away when using the prod build of React.

**Comment by lbwexler** [comment]
I would be up for merging this now.   Not a lot of other major change right now in Hoist React, and might be a good opportunity to get this done.

**Comment by lbwexler** [comment]
@amcclain -- thoughts here?
