### ISSUE TITLE
Support list/array field type

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2935]
Am running up against this limitation often, especially for fields which represent some kind of collection of tags on the record. Would like to see support for an array of primitive values, something like this:

```
{
    name: 'tags',
    type: 'string[]'
}
```

Important to also support these fields in our filtering. FieldFilter should support `includes` and `does not include` operators. Would also be nice if we could filter on whether the array is empty or not.

**Comment by lbwexler** [comment]
Want to make sure we consider carefully before implementing the complexity of a _typed_ array.
