### ISSUE TITLE
TabContainer `emptyText` styling should be consistent with other components

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#2953]
The TabContainer `emptyText` is displayed differently from other container-like components (such as Grid), it should use consistent layout and styling to other similar components (probably use the placeholder component?)

**Comment by amcclain** [comment]
<img width="784" alt="Screen Shot 2022-04-14 at 11 27 35 AM" src="https://user-images.githubusercontent.com/225806/163453859-771d1a7c-25b1-40ea-a608-6e5d34e93a6a.png">

**Comment by jskupsik** [comment]
<img width="791" alt="Screen Shot 2022-04-22 at 6 17 35 PM" src="https://user-images.githubusercontent.com/101586582/164851874-7e33c14a-8285-4baf-a018-83f3d132ec3c.png">

https://github.com/xh/hoist-react/commit/3b222a72adf68670c80a9afab3b2ef41a8e764c0

**Comment by lbwexler** [comment]
Hi Jakub - nice!  Reopening so you can make this change for mobile as well ---

**Comment by jskupsik** [comment]
<img width="575" alt="Screen Shot 2022-04-25 at 3 26 49 PM" src="https://user-images.githubusercontent.com/101586582/165185079-f231e8ba-345b-43ed-9f95-1a310ee099db.png">

Also see https://github.com/xh/toolbox/pull/579
