### ISSUE TITLE
Unmounting Grid showing empty text yields react warning

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#2954]
When adding all available columns from the column chooser - leaving the Available Columns list at 0 - React warns of a memory leak and points to AgGridReact. This is only reproducible when running locally, and appears to be related to the Ag Grid upgrade to v27. It does not appear to cause any performance issues. 

<img width="1769" alt="Screen Shot 2022-04-14 at 2 36 25 PM" src="https://user-images.githubusercontent.com/67703233/163481364-9c0194eb-89b3-4bbc-ad9c-e2ca222594e8.png">

**Comment by lbwexler** [comment]
*Not* related to the observer --- any use of the most simple`noRowsOverlayComponent` seems to cause this problem.  
And don't think there is any easy way to get that text to be dynamic other than remounting the entire grid.  Will file a ticket with ag-Grid.

**Comment by lbwexler** [comment]
So it looks like this was fixed in version 27.2.x. !  

A bit annoying that ag-Grid did not recognize it was broken when responding to my ticket but I'll take it!
