### ISSUE TITLE
"Copy" context menu item behavior for Total rows inconsistent with other rows

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#2967]
Reported by client QA team. The copy menu item for regular rows puts the whole in your clipboard. While for total rows it only grabs the cell you are right clicking on.

**Comment by amcclain** [comment]
Almost certainly an ag-grid bug - if it comes up again in QA we can confirm look for a record of it on their side.  @saba-mo did check and this is not a new v27 bug.

**Comment by ghsolomon** [comment]
It looks like this is a limitation of pinned rows, and doesn't appear to be fixed in the current release.  Worth attempting to come up with our own workaround?  Or filing a ticket with ag-grid directly?

**Comment by lbwexler** [comment]
we should file this with ag-grid, I think
