### ISSUE TITLE
Inline Grid DateEditor no longer shows date picker popup

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#2980]
Console warning logged from: 

https://github.com/xh/hoist-react/blob/27725263583c5a01d919a22a9d169029df1c816a/desktop/cmp/grid/editors/DateEditor.js#L21

...indicating the editor is no longer finding the grid body viewport.  Visible on https://toolbox-dev.xh.io/app/grids/inlineEditing.

I am guessing that something changed here with the latest ag-grid update.

**Comment by TomTirapani** [comment]
PR here: https://github.com/xh/hoist-react/pull/2988
