### ISSUE TITLE
Grid can get in a bad state after sorting

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#2997]
Surprisingly easy to reproduce on all apps with just a bit of effort. Rows are just missing or rendered on top of each other.

- Broken in 27.1.0 and 27.2.1
- No mention in ag-Grid site, and have not reproduced yet in their examples or filed.

**Comment by lbwexler** [comment]
Fixed with a `refreshCells()` after we set grid state.

https://github.com/xh/hoist-react/commit/c203a3f845d7a6d49a10872d6d72ea29bd7f9993

**Comment by ghsolomon** [comment]
Bug example:
https://user-images.githubusercontent.com/88904581/167470466-e9a93646-d3e0-4e46-85d8-b390138e033b.mov
