### ISSUE TITLE
SwitchInput.labelSide prop ignored if input within compact toolbar

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3002]
Label always on the left for switchInputs within a desktop toolbar with `compact:true` - looks like it's due to use of flexbox for alignment:

https://github.com/xh/hoist-react/blob/b06c39a5dec04a28f8d7e4c386a797e90cc0d372/desktop/cmp/toolbar/Toolbar.scss#L158

**Comment by ghsolomon** [comment]
Having trouble reproducing this.  Do you have an example you could share?
