### ISSUE TITLE
Hoist CSS needs to be updated to account for new/removed AG27 css classes

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3004]
For example the .ag-react-container class no longer exists but Hoist still has style definitions that expect it. 

Noticed to be causing small but unexpected changes to styling in client app.

Demoed for tom via Screenshare.

**Comment by TomTirapani** [comment]
Thanks for demoing the styling issues @febbraiod - please see PR here: https://github.com/xh/hoist-react/pull/3013
