### ISSUE TITLE
Unable to lookup TaskObserver from context

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#3006]
The example use case is:

+ I have a parent component that implements loadSupport.
+ I want the child component to be able to look up it's parent's `loadModel` via context

However, attempting to look up a TaskObserver throws with `Uncaught TypeError: Class constructor TaskObserver cannot be invoked without 'new'`.

I think it's because TaskObserver is neither a HoistModel with `isHoistModel` - I would expect it to be matched here: https://github.com/xh/hoist-react/blob/develop/core/HoistModel.js#L218-L220

Not sure how best to address this... should we make TaskObserver into a HoistModel?

**Comment by lbwexler** [comment]
Let's discuss before release.   This is a tricky one.  I think there are technical reasons why TaskObserver cannot be a HoistModel -- loadModel -- despite the unfortunate name -- is not a HoistModel.

In any case, that error message is not correct!

**Comment by lbwexler** [comment]
Discussed this with Tom -- he is able to work around by looking for the first HoistModel in context that has a `loadModel`

**Comment by lbwexler** [comment]
Also, improved the error message here:

https://github.com/xh/hoist-react/commit/8da35da4
