### ISSUE TITLE
Update to Onsen 1.12

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3014]
Looks like they got around to a number of fixes, as well as react 17 support (just in time for 18...)

Note despite the minor version bump this is called out as a breaking change - https://github.com/OnsenUI/OnsenUI/blob/master/react-onsenui/CHANGELOG.md

**Comment by lbwexler** [comment]
interestingly enough, colin tried this and ran into some basic issues with onsen's attempt to serialize our element trees.

**Comment by TomTirapani** [comment]
So, good news and bad news...

Good news is that I was able to workaround the above the issue, and after actioning some small breaking changes on their side, toolbox mobile seems to working again.

Bad news is that the styling is completely messed up. They've started used CSS vars in their style sheets, which unfortunately match the names we provide for apps to override XH styles: e.g.
```
// Hoist vars.scss
--xh-text-color: var(--text-color, var(--xh-blue-gray-dark));

// Onsen
--text-color: #1f1f21;
```
I'm not sure what our options are for this, their CSS vars are coupled quite closely with their core styles
