### ISSUE TITLE
Grid editing interactions problems

### ISSUE THREAD

**Issue by pauldelano** [xh/hoist-react#3015]
Issues with grid editing
1. Tabbing from selectEditor does not open next editable field in grid
2. In Toolbox example, tabbing from textAreaEditor toggles the next row lock status instead of opening next editable field
3. Grid selectEditor menu does not follow scroll
4. Grid textAreaEditor follows scroll out of grid
5. NumberEditor can lose value when tabbing out immediately

**Comment by pauldelano** [comment]
The first selectEditor tabbing issue is the most critical.

**Comment by haynesjm42** [comment]
Inline editing is even more broken than this, if you type in a value and quickly press enter/tab then it will not take the value you typed. You need to wait a second or two after entering the value before "committing" it in order for it to be taken by the grid.

**Comment by haynesjm42** [comment]
Seems that after select editor commits it's value, the grid is losing focus - which explains the issues with tabbing

**Comment by lbwexler** [comment]
#1 is not a regression and exists in released v48.
#5 is a new regression to NumberInput

**Comment by lbwexler** [comment]
[5] is fixed here: https://github.com/xh/hoist-react/commit/c17dba55b50c3847fd2

**Comment by lbwexler** [comment]
[1] is fixed here https://github.com/xh/hoist-react/pull/3026

I think with [1] and [5] closed we can close this issue.  The scrolling issue is a known issue. Don't scroll the grid while editing!
