### ISSUE TITLE
Allow App more flexibility to hide/show its version bar.

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#3022]
Two use cases for this recently came up:

1) We have a little "mini-app" for a client that is being used for a cross-app integration in a pop-up. Its an order form for an order management app While it may be very helpful/safe to see the version bar,  it also can be a little repetitive, with the main app's version bar.  Would be nice to have the option for the mini-app to suppress it, either in code or via AppSpec.

2) We are showing our example apps in a frame.  The redundant version bar is definitely problematic *when in a frame*.

Not sure exactly how best to do this and also how it should interact with the user preference we already have governing the same behavior -- I don't think there will be a perfect solution.

**Comment by amcclain** [comment]
We could add an extra flag to `AppSpec`, for cases like the pop-up app where the user knows ahead of time that they never want to show the version bar.

Alternatively, we could have a set of template getters on `HoistAppModel` that would allow for more nuanced / conditional overrides - e.g. an app that knows it might be within a frame could check.  I.e. 

`get supportVersionBar() {return true}` 

Suggesting the use of "support" here to indicate that this does not determine, on its own, whether it is shown or not. Looking at the other stuff installed by `AppContainer`, I don't see any other obvious similar features we should made conditional at the same time, but I wouldn't be surprised if a few more come along. 

This would deepen the split between `AppSpec` and `HoistAppModel` responsibilities - we could discuss if we have any appetite to further review what is set in the spec and if it could/should be moved to the model (or vice versa).

And finally, no reason why the spec couldn't also be configured with a function - it has `checkAccess`.  But it seems weird to put more into it, when the app model could answer this question at the right time - it's available right within `AppContainer.render`

**Comment by lbwexler** [comment]
Great idea.  I do think that anything that could be dynamic is better specified in the AppModel itself.   It gives us more opportunity to write code, consider prefs, environment, etc.  Not sure why we have as much in AppSpec as we do, but my currrent thinking is that the AppModel is a better place to put this stuff.

**Comment by Ryanseanlee** [comment]
So in each "mini-app" where we don't want the version bar to show, we want the "mini-apps" `AppModel` to override the `supportVersionBar()`? If so, should I implement that into all the example apps in toolbox?
