### ISSUE TITLE
Support `autoHeight` mode for DashCanvasView

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#3042]
Would like to be able to toggle an auto-height mode for DashCanvasViews, where it would calculate the rows based on the `scrollHeight` of the child component. Would need to listen for changes to the child `scrollHeight` and adjust accordingly.

This would of course require that you setup your content component correctly for this to work, which is generally the case when dealing with any kind of auto-height.

**Comment by ghsolomon** [comment]
closed with #3060
