### ISSUE TITLE
Persisted Grid state can omit width/pinned status for hidden columns

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3058]
We persist hidden columns into grid state so we can detect when new, default-visible cols have been added (in code) to the grid and show them by default, as well as maintain ordering of hidden cols in case the user shows them again.

However in grids with a high percentage of hidden cols - especially those that have many cols - the state tracking for all hidden cols can make up a very large percentage of the overall state and result in a very large JSON blob for persistence. We have a client app that creates an extreme case in the form of dashboards with multiple instances of a grid widget containing over 200 available columns, where only a small fraction of cols are likely to be made visible. 

This JSON bloat could be trimmed down significantly with minimal risk / disruption if we persisted hidden cols with their order and `hidden:true` flag _only_, leaving out `width`, `pinned`, and `manuallySized` state here:

https://github.com/xh/hoist-react/blob/323c1f90ed55d99587a818a25abfbb5ba26c1922/cmp/grid/GridModel.js#L914

 This would have the effect of resetting the width and pinned state for a col that was hidden and shown again, but that might be considered a benefit rather than a downgrade in functionality, putting the col back to a more default state when shown again.

**Comment by lbwexler** [comment]
like this suggestion alot, and it certainly seems straightforward.  

alternative, or in addition to this:

what if we only saved the hidden state of a column if its default in code was *not* hidden?  Wouldn't that reduce the bloat  greatly, and also allow new non-hidden columns to appear?

**Comment by lbwexler** [comment]
understood -- yes, outside of risk/disruption territory for sure.   Like
that expression.

**Comment by amcclain** [comment]
@jskupsik - when you are feeling a bit better and up to it, can please take a look at this?  Would make a nice difference for one of our current client apps where we serialize a ton of grid state with many columns.  Hopefully a straightforward and safe change as described.
