### ISSUE TITLE
Empty Dashboard "Add View" menu should show view submenu only

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3069]
An empty DashCanvas/Container displays an "Add View" button, which shows the standard menu. 

Somewhat non-ideally, this means the user gets this weird experience, where they must navigate into a submenu to add items:
<img width="1204" alt="Screen Shot 2022-06-29 at 5 29 13 PM" src="https://user-images.githubusercontent.com/225806/176567867-005f8742-71d5-4089-b208-6cb054a5964b.png">

In many cases, instances might have other menu items - notably a "reset to defaults" option.  I can see how those might be nice to make available here, but the tradeoff in the default case seems unfortunate. Could we build a dedicated menu for this button that skips right to the available widgets, with perhaps an API to add any other arbitrary buttons (or other content) to the empty placeholder?  That would let an app with a reset function highlight that even more clearly.

**Comment by ghsolomon** [comment]
> perhaps an API to add any other arbitrary buttons (or other content) to the empty placeholder? 

Would love to discuss this bit - have some ideas but would be good to hear how everyone might want to customize the empty canvas / how much flexibility to allot for here
