### ISSUE TITLE
Show lastUpdated / lastUpdatedBy in admin config/pref differ

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3092]
It would be useful when looking at the detailed diff display in our cross-environment diff tool if you could see who last updated each value and when.

We deliberately exclude those two fields from the actual comparison itself - otherwise there wouldn't be any way to get them in sync - but it would be great to see it for informational purposes when evaluating if you want to take a remote value.

**Comment by lbwexler** [comment]
@PeteDarinzo  -- since you were recently working on the differ, thought this might be a good  one for you
