### ISSUE TITLE
Calling `TaskObserver.setMessage('foo')` prevents any linked subtasks from displaying a more specific message

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3122]
`TaskObserver` currently has some surprising behavior around its messages.  If the observer has had its message set directly, any subsequent messages set via `linkTo()` will not be shown.

E.g.
```
export class FooModel extends HoistModel {

    constructor() {
        super();
        // General / default message customization desired.
        this.loadModel.setMessage('Loading foo....');
    }

    // Primary model load - general message desired - works OK
    async doLoadAsync(loadSpec) {}
    
    // Secondary model load - more specific step-by-step messages desired - do not show due to setMessage call in ctor
    async loadSomethingElseComplicated() {
        await XH.fetchJson({}).linkTo({observer: this.loadModel, message: 'Loading step 1'});
        await XH.fetchJson({}).linkTo({observer: this.loadModel, message: 'Loading step 2'});
    }

}
```

This is due to https://github.com/xh/hoist-react/blob/71f2cf77d31bd005ce320572c31d2598ce651f41/core/TaskObserver.js#L158  

@pauldelano and I reviewed and think it would be more useful if the observer returned the message of any pending subtask first, if available, and then fell back to its own message as a default.

**Comment by lbwexler** [comment]
I see the logic in this case, but am a little bit nervous about over-generalizing.  

What if there is more than one pending sub-task?  Should we take the first?  That seems a little arbitrary, but perhaps defensible, as the ordering of when the tasks are added is preserved.
