### ISSUE TITLE
GridModel.selectAsync()  does not work without this.whenReadyAsync()

### ISSUE THREAD

**Issue by john-xhio** [xh/hoist-react#3123]
`GridModel.selectAsync() ` requires  `await GridModel.whenReadyAsync();` to function. (similar to `selectFirstAsync`) Can it be baked into the function?

In situations where you want to default the grid selection to a specific row immediately after a load you have to wait for the grid to be ready or the row will not be selected.

**Comment by lbwexler** [comment]
Uugh.  Thanks for reporting this.  Did not expect this.  Will look into this tomorrow.

**Comment by lbwexler** [comment]
Hi John -- sorry for the delay on this. 

Can you upgrade to v51, and set the experimental flags for grid (config key `xhGridExperimental`) to 

{
	"syncDataImmediately": true
}

this should fix your problem.   Hopefully it does not break anything else (would love your confirmation of that for your app) Its looking like this will become the standard setting in the toolkit in v52

**Comment by john-xhio** [comment]
Awesome, I will rewind my temporary fixes and try it out. Thank you!

**Comment by lbwexler** [comment]
[it worked for John]

**Comment by lbwexler** [comment]
Closing this -- we are making the flagged fix the default behavior in v 52.
