### ISSUE TITLE
LocalDate.from will tick to the next day if provided with the 31st on a month that only has 30 days.

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3141]
LocalDate.from('09/31/2022') -> 10/01/2022

This is like a moment behavior, but it was unexpected when seen in a client app when testing validation. Should we provide a flag to opt in or out of this behavior?

**Comment by lbwexler** [comment]
Well, believe it or not, this behavior seems to be standard in parsing of  moment and javascript date.  The 31st of September, April, June, and November all will be rolled.  as well as 29, 30, 31 of February!


Can't see an easy way to avoid this in our code, and am not sure we should, given this convention, and the lack of much complaint about it as far as I can see.   Strictly speaking our code refers to moment parsing, and is not incorrect.

Let's re-open this if we need to
