### ISSUE TITLE
App Version should be a column in the Admin Activity Grid

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#3143]
App Version info in the activity grid would be especially useful right after app upgrades to see who was still using the old version.

This would be a breaking change because it would require a new column "AppVersion" or "Version" be added to this Hoist-Core table:
https://github.com/xh/hoist-core/blob/develop/grails-app/domain/io/xh/hoist/track/TrackLog.groovy

**Comment by jskupsik** [comment]
The 'additional data' field occasionally contains "appVersion" and "appBuild" information, but only on 'Loaded App' entries.

**Comment by amcclain** [comment]
This was completed!
