### ISSUE TITLE
Make BLANK_STR a static property on GridFilterModel.js

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#3144]
This would make it easier to re-use and maintain in apps.  
Apps wouldn't have to make their own BLANK_STR constant and make sure it was in sync.

https://github.com/xh/hoist-react/blob/da53eb4e42d7433cc49bd2fec84c421d13cc95d7/cmp/grid/filter/GridFilterModel.js#L39

**Comment by saba-mo** [comment]
Let's call this BLANK_PLACEHOLDER.

**Comment by TomTirapani** [comment]
FYI, I pushed this follow on commit straight to develop: https://github.com/xh/hoist-react/commit/0c6fb6bd17b898edd60a629e7d113c6881613488
