### ISSUE TITLE
Review console warning output when renderIsComplex and highlightOnChange used on same column

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3147]
Currently `Column` warns if you spec both arguments as true:

https://github.com/xh/hoist-react/blob/aadb6a5d1dc2ed3196fa22fde63d493f0a0a780e/cmp/grid/columns/Column.js#L457

The new Hoist Inspector properties grid does this for its value column:

https://github.com/xh/hoist-react/blob/aadb6a5d1dc2ed3196fa22fde63d493f0a0a780e/inspector/models/ModelsModel.js#L242

But I am not observing any issues with that configuration.  I see updated values flash as intended, but _do not_ see the values column cells _always_ flash as the warning implies.

Am I missing something, or is this warning perhaps out of date given Ag-Grid changes? If the latter, does this imply there's something deeper we need to revisit?

**Comment by lbwexler** [comment]
Tested this, and I think we can safely remove the warning and close.  Am assuming this is related to the major ag-Grid changes in the last several releases.
