### ISSUE TITLE
DockContainer behavior unintentionally changed by use of ModalSupport

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3148]
Docked `DockView` elements within a `DockContainer` were intentionally configured (via CSS) to not flex/shrink if they overflow the available width of the container - instead they could overflow off the edge and clip.  

This was a tradeoff to avoid designers needing to handle arbitrary shrinking of docked view contents. See:

https://github.com/xh/hoist-react/blob/aadb6a5d1dc2ed3196fa22fde63d493f0a0a780e/desktop/cmp/dock/impl/Dock.scss#L37

Introduction of ModalSupport wrapper has broken this, causing dock views to shrink vs. clip.

<img width="1407" alt="Screen Shot 2022-09-30 at 12 13 13 PM" src="https://user-images.githubusercontent.com/225806/193342465-00a8a278-f6e0-4c2e-baa2-625aad08bb3e.png">
<img width="1954" alt="Screen Shot 2022-09-30 at 12 15 40 PM" src="https://user-images.githubusercontent.com/225806/193342479-cce3d28e-44e9-47c7-9174-a07bf6e8207c.png">

@pauldelano also reports that the `docked:false` config is no longer respected.

**Comment by pauldelano** [comment]
Also, the modal dialog mode constrains the width of the dialog to 500px instead of to the width of the contained component. Was able to work around this by defining this style.
.bp4-dialog {
  width: auto;
}
