### ISSUE TITLE
Add Store.allErrors and StoreRecord.allErrors convenience getters

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3179]
Right now there is no convenient way for an app to get a flat listing of validation errors within a store. It would be helpful to have an analog to `FormModel.allErrors` for this purpose.

Currently:
* `Store.validator.errors` returns an object mapping `{recordId -> {fieldName: errors[]}`
* `StoreRecord.errors -> StoreRecord.validator.errors` returns `{fieldName: errors[]}`
* `Store.errors` does *not* exist

I'd propose:
* Add `Store.errors -> Store.validator.errors` for consistency with `StoreRecord.errors` (still returns the mapping object as described above)
* Add `StoreRecord.allErrors` returning a flattened list of errors across all fields (as `string[]`).
* Add `Store.allErrors` returning a flattened list of errors across all records (as `string[]`).

**Comment by amcclain** [comment]
@Ryanseanlee and I came across a need for this in a client app.  Let's close this gap _after_ the TS work has been merged in.

**Comment by lbwexler** [comment]
@amcclain -- one issue with flattening out the messages at the *store* level is that the individual messages do not have any context about the particular record where there error is. So if there are errors on more than one record, its pretty confusing, with dupes.   We could leave off `Store.allErrors`, or have it return an array of {record, errors[]} objects.

I have also added an `Store.errorCount` getter for symmetry.
