### ISSUE TITLE
GridModel.ensureRecordsVisibleAsync fails to find collapsed row nodes in tree grid

### ISSUE THREAD

**Issue by ghsolomon** [xh/hoist-react#3211]
`GridModel.ensureRecordsVisibleAsync` can fail to find collapsed row nodes in a tree grid.

This can be fixed by changing the `await wait()` between steps `1) Expand any nodes that are collapsed` and `2) Scroll to all nodes` to `await wait(100)`, but this is of course not an elegant solution.

**Comment by amcclain** [comment]
To confirm - was this resolved by #3212 ?

**Comment by ghsolomon** [comment]
> To confirm - was this resolved by #3212 ?

That's correct
