### ISSUE TITLE
Spinner should support layout props

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#3216]
It's props current just extend HoistProps, so if you want to set something like width or height, you'll get linter errors since TS doesn't know that we pass the props through to the `img` element. Supporting layout props on Spinner is probably the best way to go, we don't think it is necessary to support other `img` element props

**Comment by lbwexler** [comment]
Woops -- just merged Colin's change to actually support *all* image props.
Do we want to roll that back -- @cnrudd, @haynesjm42?

**Comment by lbwexler** [comment]
https://github.com/xh/hoist-react/commit/dafef9cc8ff10a2
