### ISSUE TITLE
MenuItem's appMenuButtonProps should use onClick not actionFn

### ISSUE THREAD

**Issue by jskupsik** [xh/hoist-react#3222]
The MenuItem interface does not contain for a 'onClick' field, despite that being the correct/working field for clicking on the MenuItem. The provided 'actionFn' does not work.

**Comment by amcclain** [comment]
@TomTirapani should your PR fully close out this issue?  Reviewing tickets quickly here and not looking in too much depth - if you can help confirm the scope of your fix that would be much appreciated.

**Comment by TomTirapani** [comment]
Yeah, my PR should fully close out this issue, but approaches it from the other direction - changing the implementation to use `actionFn` rather than `onClick`, for consistency with our other menus
