### ISSUE TITLE
Banner feature should allow for pre-canned messages to be saved and published via admin

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3230]
Idea is that there might be messages that occur with some frequency e.g. "Realtime prices delayed. IT is investigating". Having this feature would both be convenient for business admins and help avoid silly typos.

**Comment by amcclain** [comment]
We discussed this when we first implemented the feature and I think it would be a nice enhancement to add. I know from practice that you often don't want to force a Help Desk person (or us!) to come up with some new message from scratch under pressure when there is a production issue that warrants an alert.

* We could consider storing some amount of history, allowing the admin to review and select from (then go on to edit) any past messages. 
  * That might be useful both as a quick-selection tool and also have the benefit of giving the feature a bit of a memory, in case you were interested in how / when it had been used before.
  * Also has the advantage of not relying on a diligent admin to think up scenarios ahead of time.
* Or we could support defining a library of canned configurations to pick from, either directly in the tool (ideal) or via a config.
* Or we could split the difference by not automatically remembering all prior messages, but allowing an admin to save a given config that's currently loaded into the tool, on demand. I am imagining an alert that gets setup, and then when it is time to take it down there's a visible option to "save for future use" that a smart admin could click to snapshot an alert they think might recur, and give it a name or whatever to identify.
* Any which way, we should aim to capture all the little settings together - message, intent, icon, etc.
