### ISSUE TITLE
Grid Cell Date Picker is not positioned correctly when grid has pinned columns

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#3241]
Reported by a client where it's affecting their app. Can reproduce on toolbox:

<img width="1570" alt="Screenshot 2023-01-23 at 2 10 45 PM" src="https://user-images.githubusercontent.com/225806/214161529-66c0d4fa-9f97-41f3-801d-dc6719a1c979.png">

**Comment by meghma** [comment]
Hopefully it is an easy fix.

**Comment by meghma** [comment]
Also it appears, that if the cell is clicked, the date value disappears.

**Comment by amcclain** [comment]
@cnrudd would you be able to take a look at this when you are back in the office?

I see we already have some custom handling here, including code that's aware of the dedicated column pinning containers:

https://github.com/xh/hoist-react/blob/7ea2e92effc7c741afd876a47fca4f53ac919628/desktop/cmp/grid/editors/DateEditor.ts#L78

Hopefully this is a missed case that can be filled in, or some change to the AG-Grid DOM layout we can again properly account for.

**Comment by cnrudd** [comment]
Starting work on this now.

**Comment by cnrudd** [comment]
@meghma There is a PR in your app's repo to resolve this issue: "Also after the row is saved with the date and grid is refreshed and the date cell is clicked the cell is blanked. The date re-appears after reloading."

**Comment by amcclain** [comment]
Thanks for resolving this @cnrudd / thanks for merging @lbwexler
