### ISSUE TITLE
Misleading exception from FetchService.xxxJson() when server returns 200 w/empty response

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3256]
We have special handling within FetchService to correctly return `null` from an API call that returns `204 NO_CONTENT` and an empty response body.

However if an API returns `200 OK` instead with an empty body, we throw on attemping to call `r.json()` and the exception handling wrapped around the call within FetchService ends up returning a misleading `Exception. serverUnavailable()` with the message `Unable to contact the server at ${origin}`.  

This just confused @Ryanseanlee and I as we were seeing the network request to the API go through OK and respond with a 200 (before we noticed the empty body), so it very obviously _did_ contact the server OK, but then was tripped up by its unexpected empty response.

For the particular case here we are contacting the API developers to have them return a non-empty body or a 204, but the misleading exception made it more difficult to debug.

**Comment by lbwexler** [comment]
Interesting comment here about browser support for empty responses:  
https://developer.mozilla.org/en-US/docs/Web/API/Response/body

Would be good (and trivial) to at least code to this standard by checking `body` before calling `.json()`  Would be even better if chrome respected that!

**Comment by amcclain** [comment]
Ran into another version of this just now with an API that returns `202 Accepted` in response to a successful PATCH request - looks like we are throwing in the same way.  

@jskupsik I'm referring to the new approvals endpoint on our client project - might be reason enough to take a look at this Hoist ticket and resolve it to better support this class of "empty but successful" responses.

**Comment by jskupsik** [comment]
I was thinking about a FetchOptions argument:
```ts
    /**
     * If set, response body will be always ignored or never ignored, regardless of status code.
     * Default behavior: null response bodies generally throw an error, except for status codes in
     * {@link NO_JSON_RESPONSES} in which cases the body is ignored.
     */
    ignoreBody?: boolean;
```
    
Is there any value in an (unexpected) body-less response throwing and being treated by hoist as a failed response, unless the developer explicitly opts into accepting it? I would improve the error message in this case.

If we don't do the strategy above and check for the existence of a body on the response, do we still want to _always_ ignore the body for 204s and 205s as we currently do, or should we return the body if we ever do happen to get a 204 with a body?

**Comment by lbwexler** [comment]
Why wouldn't you just use `fetchService.fetch()` if you did not actually want the body?

**Comment by lbwexler** [comment]
In the end we determined that just improving the exception so that it was less confusing was the safest choice.

We considered  replacing the native `.json()` with a custom version, but decided we risk missing out on any browser optimizations there.

We also considered adding a flag of the form `alwaysAllowEmptyResponse` to the fetch ops but are holding off on that.   The new exception warns to go use `fetch()` directly...
