### ISSUE TITLE
use "noImplicitOverride": true in tsconfig.json

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#3271]
See: https://www.typescriptlang.org/tsconfig#noImplicitOverride

I think this would add another level of safety to the project: mainly, not allow subclasses to override super class methods and properties without the `override` prefix.  This would bring a lot of clarity to what was being overriden or not.

Steps:
1: add `"noImplicitOverride": true` to tsconfig.json
2: add `override` prefix to all red-marked methods and properties (search and replace should take care of most offenders)

**Comment by amcclain** [comment]
I would be in favor of this - seems like a nice bit of extra safety TS can provide that we could take without much effort.

**Comment by lbwexler** [comment]
let's go for it!

**Comment by lbwexler** [comment]
how badly do we want this in hoist -- its required for all properties -- e.g.

`override xhImpl: true`

**Comment by cnrudd** [comment]
Yes, not just methods.  I thought that was a fine aspect of the feature.  I did say, "methods and properties" in the description.  :)

**Comment by lbwexler** [comment]
hah -- yah, just hadn't realized we had so many properties like `xhImpl =
true`.

Not a showstopper, I suppose.....

**Comment by cnrudd** [comment]
A strong case for adding this to Hoist-React is that if a developer wanted to add this to their Hoist-React app to help debug or keep their app ship shape, the typescript compiler would error out on all of the Hoist-React Framework `override` omissions.   Because the TS compiler also compiles HR files when run on app files.  
I don't think we want to get in the way of app developers taking full advantage of this feature.
