### ISSUE TITLE
Use of commitOnChange + buttonGroupInput throws console warning

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3277]
We have a form component in an app with `fieldDefaults: {commitOnChange: true}` and an included `formField` with a `buttonGroupInput` as its item.

This throws "Warning: React does not recognize the `commitOnChange` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute...." - indicating that the defaulted prop is making its way through to the underlying component, which does not support (or need) it.

**Comment by lbwexler** [comment]
Yes, this is a known issue, and I am not quite sure what the best way to solve it is.  As I discussed with John Haynes, we no longer have a convenient way at Runtime to analyze what props are supported on an object.  (that was one advantage of proptypes).

We could add an explicit flag of the form `supportsCommitOnChange` on the component, but that seemed to me a little bit clunky.

Thanks for filing -- should have done so after my analysis/work with John.  Will circle back on this
