### ISSUE TITLE
OptionsDialogModel contains references to loadModel, but property has been removed.

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3278]
Can be fixed in the client app I found this problem in because we are extending this class and can hang a loadModel on the descendant. But this appears to be broken to me in Hoist and is not documented in the breaking changes in the 54 CL.

**Comment by lbwexler** [comment]
am curious why you are extending this class.  Its marked as `@internal`.

But agree that is a problem -- good catch, fixing now.

**Comment by lbwexler** [comment]
Fixed here.  Great catch

https://github.com/xh/hoist-react/commit/839208c0e37d20dd3b7a061387147a6c4819c7c8

**Comment by febbraiod** [comment]
Not to pass the buck, but this choice was made by our friend in London I believe.

**Comment by lbwexler** [comment]
yeah, I recall now, all good

**Comment by TomTirapani** [comment]
If we are talking about what I think we're talking about, it was to support a custom layout in the dialog :)
