### ISSUE TITLE
PersistWith getter on HoistModel returns null

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3280]
This appears to be a regression that occurred between Hoist 51 and Hoist 54. Easy to fix in app but would be good to understand.

**Comment by lbwexler** [comment]
Hi -- I don't think there is any way around this -- this looks like it relates to core changes we made in how properties are defined on classes in order to support typescript and specifically our new bindable concept.

**Comment by lbwexler** [comment]
Essentially you can no longer override a property with a getter (or vice-versa).  Not sure we ever intended this in the first place -- and it might have just been luck that it worked before.  Typescript now gives you very informative errors when you try that.

If we had to do it again, we probably would defined the property on the base class as a getter, to allow overrides to be getters and therefore have the maximum flexibility.  I don't think we want to make such a breaking change.

**Comment by lbwexler** [comment]
Discussed with Don -- we have a workaround.
