### ISSUE TITLE
Upgrade Ag-Grid to 29

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#3285]
https://www.ag-grid.com/changelog/?fixVersion=29.0.0

**Comment by haynesjm42** [comment]
Found 1 regression so far - looks like setting the header height to `0` is now interpreted as a falsey value and resulting in the header height using the default height from the theme - added handling to set this via css instead but we might consider reporting this and getting it fixed in 29.1.0 - does not seem like correct behavior

**Comment by lbwexler** [comment]
Giving to Pete to check out with agGrid 29.0.1
