### ISSUE TITLE
FilterChooser does not properly parse inputs on LocalDate fields

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3312]
...despite looking like it should / does.

Reproducible on Toolbox - behavior is quite tricky, as FC displays suggestions and will even convert typed-in yyyyMMdd text to what looks like a nicely parsed value date.  The store will even correctly filter (for reasons I don't quite understand) and the matching grid column header will indicate active filtering on the field.

But if you open the grid col header, it throws, and if you inspect the filter that FC has installed, it has a string value.  If you start by choosing a date from the grid filter instead, you will see it correctly sets a LocalDate value within the filter it produces.

<img width="2057" alt="Screenshot 2023-03-17 at 5 26 58 PM" src="https://user-images.githubusercontent.com/225806/226073657-93fc706e-d435-46c1-bbbb-c59b783a2bac.png">

**Comment by jskupsik** [comment]
Fixed with PR https://github.com/xh/hoist-react/pull/3313
