### ISSUE TITLE
ButtonGroupInput attempts to spread FormField props onto underlying DOM element.

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#3323]
A ButtonGroupInput inside a FormField will attempt to pass along certain FormField to its underlying DOM element, causing a nasty react bug:

<img width="746" alt="Screenshot 2023-03-27 at 11 44 10" src="https://user-images.githubusercontent.com/3017757/227930362-e7bc2302-ab38-4220-a4a7-87fdadd62135.png">

Observed with setting `commitOnChange` on the FormField, but I suspect it may occur with other FormField props.

(Edit: You may think "Just don't set `commitOnChange: true` on a ButtonGroupInput FormField, it doesn't make sense" and you would be right - in this case, it was being set via `formFieldDefaults`. But regardless of how it gets set, we are advertising `commitOnChange` as a FormField prop through TypeScript. Even if it has no effect for this particular HoistInput, devs should be able to set it on any FormField without throwing)

**Comment by amcclain** [comment]
@TomTirapani can this be closed or are there remaining issues?  Please go ahead and close out if we're all good, thanks.

**Comment by TomTirapani** [comment]
This is resolved - closing
