### ISSUE TITLE
Column uniqueness validation error could be more helpful

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3334]
It could point you to exactly which colId is causing the error. If you have a larger number of columns that have similar looking field names (sd5, msd5, sd10, msd10, sd1060, msd1060 ect ect) it can feel a little like a wild goose chase to pin the offender down manually. My understanding is other have recently felt this pain as well.

**Comment by amcclain** [comment]
💯 - agree, great suggestion. Any time I encounter one of our own exceptions that seems to actively _not_ give you the one bit of info you need (and which you know it has!) it drives me crazy.  This is definitely one - I searched to ensure I hadn't already put in a ticket for this (I did not).

Note that `Store` does what you're looking for re. unique record IDs:
https://github.com/xh/hoist-react/blob/b8c1b5a6f9ab523ada55379cdcddfdd688088daa/data/Store.ts#L969
