### ISSUE TITLE
Admin Memory Monitor chart axes misaligned

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3335]
It would be nice to get these axes aligned on top of one another - unclear why there is a gap between the bottom one and the primary chart area.

<img width="1762" alt="Screenshot 2023-04-18 at 11 11 35 AM" src="https://user-images.githubusercontent.com/225806/232866734-4cc9a6e1-8a0a-405e-aa07-3cfc762996a2.png">

**Comment by lbwexler** [comment]
Yes, actually was aware of that, but let it go, as I couldn't find a clean way of addressing it, and it didn't seem terrible relative to how little code was required to get this stacked chart.

Note that this chart is a done as a *single* chart, using relative axes -- not sure its a technique we have ever used in client applications.

**Comment by cnrudd** [comment]
I think we have used this single chart object to display 2 (or more) charts in an app.  I think it was in the first app that @febbraiod  converted to Hoist for a client.  I might be wrong, but it's worth checking that app.
