### ISSUE TITLE
TreeMap should allow for resizing the grid to chart ratio

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3371]
As it stands there is a grid Width property that can be set but never changed. This is a client request for their flagship Hoist app.

**Comment by amcclain** [comment]
@febbraiod I'm not sure that the relevant change would be within a Hoist component - we don't have a pre-integrated grid + chart combination - e.g. see the [Toolbox example for this pattern](https://github.com/xh/toolbox/blob/develop/client-app/src/desktop/tabs/charts/GridTreeMapPanel.ts) where they are two comps.

Could you be looking at a custom client component that binds the two together and has the `gridWidth` property?

**Comment by febbraiod** [comment]
You are absolutely right. I had convinced myself that was a hoist component and I didn't bother to look, how embarrassing. Thanks Anselm!
