### ISSUE TITLE
Add observable property to Idleservice: idleFor

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#3385]
The  observable `idleFor` property would be an int, and have the time in minutes since activity was last detected on the app.

This property could be used by apps who wanted to implement their own "lighter touch" "sleep" profile.

For instance, rather than shutdown all services, and force users to re-awaken the app by reloading it (thereby losing any current unsaved state), 
and app could, when idleFor > 30mn were detected, stop making the several recurring data calls that may fetch a lot of data.

When activity was detected again (idleFor would == 0) those recurring data calls would be resumed, without reloading the app.

**Comment by lbwexler** [comment]
Closing this.

For now its easy enough to do this in app land -- just use a timer and check `XH.lastActivityMs`
