### ISSUE TITLE
Particular layout can cause ResizeObserver loop limit exceeded error

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3390]
This occurs when you have a chart nested in a non-resizable panel, which is nested inside a resizable parent panel. (And possibly only when the window changes in such a way to make the panel smaller??)

Reproduced here in portfolio example app:

https://github.com/xh/toolbox/tree/panelResizeBug

<img width="930" alt="Screenshot 2023-06-08 at 2 08 36 PM" src="https://github.com/xh/hoist-react/assets/15745614/21bab333-dd86-45bc-ae8a-510ee05a6c45">

**Comment by lbwexler** [comment]
Cannot reproduce
