### ISSUE TITLE
Poor defaults with `errorMessage({error: lastLoadException})`

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3441]
Model throws in `doLoadAsync()` with e.g. HTTP500, resulting error comes back from fetchService with empty string message, mildly-useful name.  Our `errorMessage` component displays small empty red box - looks silly.

Should be able to better source meaningful content from exception + fallback to generic error message string if none found.

**Comment by lbwexler** [comment]
Closing this, and linking to related ticcjet https://github.com/xh/hoist-react/issues/3555
