### ISSUE TITLE
Update `router5 7.0 → 8.0`

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3453]
https://router5.js.org/migration/migrating-from-6.x-to-7.x

**Comment by amcclain** [comment]
(Yes that link actually points to the 7 -> 8 docs - not exactly confidence inspiring...)

**Comment by lbwexler** [comment]
ah -- well at least if those are the docs for 7-8 that's something.  I had assumed they were the 6-7 docs

**Comment by lbwexler** [comment]
I discussed this with Leo -- let's continue to hold off here.

**Comment by amcclain** [comment]
Unfortunately does not look like anything has improved here - project still appears to be effectively abandoned, docs still in misleading state described above.  I'm going to close the ticket as we don't have any pressing need to take an update and it's not clear that the 8.x release is fully baked - and if there are any problems, does not look like they are likely to be fixed.
