### ISSUE TITLE
Improve RelativeTimestamp's handling of durations expressed in days

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#3507]
RelativeTimestamp uses momentjs to "humanize" durations.

This works well in most cases, but fails quite noticeably for durations that it determines should be expressed in "days":

For durations described in "days", users are expecting a plain calendar subtraction (today's date minus yesterday's date equals one day), but momentjs instead returns "2 days", since it rounds up fractional days.

For longer durations like months or years, humans don't object to or notice rounding, but for durations expressed in days, rounding is not accepted.

Perhaps RelativeTimestamp can be given special handling: when the interval will be in days (as determined by momentjs) , it forgoes momentjs' math and returns the result of a plain calendar day (no time component) subtraction.

**Comment by cnrudd** [comment]
Found some time to work on this today.  First step was to improve the components testability with more options:

<img width="910" alt="image" src="https://github.com/xh/hoist-react/assets/2573928/9c08f36b-c308-4147-9f41-44e8a60aeb0b">


I will work on adding in "LocalMode" next.

**Comment by cnrudd** [comment]
UI that landed in PR:
<img width="916" alt="image" src="https://github.com/xh/hoist-react/assets/2573928/1b5a4108-7f5e-468b-83a4-3df25074789a">

**Comment by lbwexler** [comment]
We fixed this!
