### ISSUE TITLE
`GridFilterFieldSpec.inputProps` typed too generically as `HoistInputProps`

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3510]
We store and will then spread on any `inputProps` provided to the type-specific input component that ends up being rendered within the grid filter header's "custom" tab:

https://github.com/xh/hoist-react/blob/c7283cbba9ac52ca86c2cd64a0e228f72d15128a/desktop/cmp/grid/impl/filter/custom/CustomRow.ts#L79

This means we support all props for e.g. `dateInput` or `numberInput`, but the typing displays as an error.  We should likely amend to a union type of the PropTypes for all supported inputs - I expect that's the best we can do.

**Comment by lbwexler** [comment]
Would be nice to take this typescript off the board, if simple @ghsolomon -- thanks

**Comment by ghsolomon** [comment]
One complication here - we have different input props for our desktop vs. mobile components, but `GridFilterFieldSpec` is shared between both.  We could make`inputProps` an exclusive union of both mobile and desktop prop types, but then I believe we would also need to break those type definitions out into their own modules so we aren't importing anything but the types into the shared module.

**Comment by ghsolomon** [comment]
We ultimately decided against changing the `GridFilterFieldSpec.inputProps` type in order to avoid importing platform-specific code into this cross-platform module.  Applications wishing to ensure type-safety and avoid TS errors can define their input props separately and pass them as illustrated below:

```
private createGridModel() {
        const inputProps: DateInputProps = {
            maxDate: LocalDate.today()
        }

        return new GridModel({
            filterModel: {
                fieldSpecs: [
                    {
                        field: 'trade_date',
                        fieldType: 'localDate',
                        inputProps
                    }
                ]
            },
            ...
        })
}
```
