### ISSUE TITLE
`GridModel.cellBorders` is not applying top and bottom borders

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#3525]
Setting GridModel.cellBorders to true is only applying left and right borders. This is presumably related to the recent cell border styling changes in hoist react 59.2.0. The .ag-cell class was added to the styles applied to --no-row-borders class in AgGrid.scss.
![Screenshot 2023-11-14 at 1 20 36 PM](https://github.com/xh/hoist-react/assets/67703233/33156a98-7b5f-4f68-9b21-82070964f875)

**Comment by amcclain** [comment]
Just to ensure it's 100% clear - in screenshot above, with "cell borders" enabled, we would expect the grid to render looking like an Excel spreadsheet, with (shared) borders around each cell.
