### ISSUE TITLE
Rendering + expand/collapse bugs with tree Grids in AirWatch Browser

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-react#3559]
Reproducible in Toolbox-dev on MDM browser.

**Comment by cnrudd** [comment]
@lbwexler the AirWatch browser.

**Comment by amcclain** [comment]
Testing in Airwatch Web browser v24.02 b1489 on iPhone 15 w/iOS 17.5.1.  Using Toolbox-dev with Hoist v65 snap and AG 31.2.1.

I believe treegrid expand/collapse behavior is the following:

* Tap on a cell in a parent-level tree grid row - row will NOT expand/collapse.
* Any subsequent tap on SAME cell - row expands/collapses OK
* Tapping on another cell - even in the same row - does not exp/coll until next tap (on same cell)

Crazy making!  I am seeing that the first, non-working tap seems to trigger a brief flash where it looks like the row might be expanding and then contracting again very quickly.

**Comment by amcclain** [comment]
Also seeing issues with the expand/collapse carets not rendering reliably.

When first loading a page with tree grid - no carets visible:
![IMG_7997](https://github.com/xh/hoist-react/assets/225806/cb98778b-abf8-4e10-b6e1-d20ae82e3939)

Interact with page, tapping a row (which fails to expand as per above) - carets become visible:
![IMG_7998](https://github.com/xh/hoist-react/assets/225806/988f11cb-d02a-4b33-aa98-e37b7e0d8162)

Expanding one of these rows triggers scrolling - note scrollbar artifact along part of right edge of grid body, which should not be there:

![IMG_7999](https://github.com/xh/hoist-react/assets/225806/9c758b09-789a-4440-9873-f500d58868d8)

**Comment by amcclain** [comment]
Also note how build number in footer has been helpfully turned into a tel: link, to add further insult to injury.  

No, Airwatch, I do not want to "Call (807) 180-80" - which is what it suggests if you tap on that link....   🙄

**Comment by amcclain** [comment]
Closing as we don't think there is much we can do about this very broken browser - following up with client re. replacements
