### ISSUE TITLE
Alert banners should support option to limit to one or more specific client apps

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3587]
Currently the Admin Console allows you to display a configurable alert banner, but it will be shown across all client apps. We have some applications that use a single project / server to host distinct client apps with different purposes / user bases. For those projects, we might wish to display an alert banner to one client app but not another.

We should add a multi-select option to the alert banner configs to spec one or more client app codes.  If blank (default) would show to all client apps.  

A nice bonus would be to populate the select options with the list of all client app codes so admins don't need to know them.  I don't believe we have that now. Could use an optional config, but could also consider having our dev-utils [define a const](https://github.com/xh/hoist-dev-utils/blob/e83a9812a84e0d863519655bb96e7efd469e8efc/configureWebpack.js#L614) that apps could read - it knows the codes.

Do _not_ need the (much more complex) ability to show different banners at the same time to different apps.

**Comment by minusleaf** [comment]
Additional requirements:

- Client apps should also be a differentiator as to whether a new preset can be added
- Update the UI on the dropdown presets what apps are targeted to help better differentiate between different presets. If client apps field is empty, then indicate "all apps".
