### ISSUE TITLE
Include `defaultHeaders` in exception logs

### ISSUE THREAD

**Issue by ghsolomon** [xh/hoist-react#3590]
`FetchService.managedFetchAsync` can throw 3 Hoist-generated exceptions:

- `Exception.fetchTimeout`
- `Exception.fetchAborted`
- `Exception.serverUnavailable`

To each, it passes `opts: FetchOptions`, which includes a `headers` property.  However, `opts.headers` is not the fully resolved collection of headers (i.e. it does not include `FetchService.defaultHeaders`).  We should include `defaultHeaders` here so that we log the entire collection of headers sent with the request, and not only those which are specified via `opts`.

(See https://github.com/xh/hoist-react/blob/f475e80dc70603c3b78d36f19a93807fc8e6c217/svc/FetchService.ts#L171)

**Comment by lbwexler** [comment]
I'll take a look -- good train ticket
