### ISSUE TITLE
SplitTreeMap does not surface errors as intended

### ISSUE THREAD

**Issue by ghsolomon** [xh/hoist-react#3610]
`SplitTreeMap` should renderer errors inside an `errorMessage` per the following code in `SplitTreeMap.ts`:
```
const errorPanel = hoistCmp.factory(({errors}) =>
    errorMessage({message: fragment(errors.map(e => p(e)))})
);
```
However, without an `error` prop, the `errorMessage` component returns `null` per this code:

```
export const [ErrorMessage, errorMessage] = hoistCmp.withFactory<ErrorMessageProps>({
    className: 'xh-error-message',
    render(props, ref) {
        let {
            className,
            model,
            error = model?.['error'],
            message,
            title,
            actionFn,
            actionButtonProps,
            detailsFn,
            detailsButtonProps,
            ...rest
        } = props;

        if (isNil(error)) return null;
```

In addition to not being displayed in the UI, these errors aren't logged to the console.

Consider fixing by passing an `error` prop, modifying `errorMessage` to accept a `message` with no `error`, and/or add logging to better surface errors to the developer.

**Comment by lbwexler** [comment]
think that  this is just a misuse of ErrorMessage -- its doc clearly states that when error is not set it will not be shown.

Error could be set to a new compound/synthetic error that includes them all.  Or just first error.  Don't think we have any requirements on the form of it.

**Comment by ghsolomon** [comment]
Ah got it, makes sense. Updating the PR
