### ISSUE TITLE
`ToastModel` instances are not destroyed

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3668]
With Inspector open to observe overall model count, show a few toasts.  You will see model count increases, with a new `ToastModel` created for each toast that is not destroyed.

**Comment by oodarluz** [comment]
https://github.com/xh/hoist-react/blob/70a4ed84e1404ea5a02c5d319d9a459f8fe8f927/appcontainer/ToastSourceModel.ts#L35C1-L46C6

The add model function will lazily cull none visible toasts when a new toast is added. 

Steps to recreate: 
1. add a few new toasts
2. wait for them to disappear 
3. add another toast

The total model count will reduce

**Comment by lbwexler** [comment]
@amcclain -- Otito and I went over this -- hopefully it makes sense to you?   Let me know and I will close

**Comment by amcclain** [comment]
Great thanks, sorry for any false alarm appreciate your reviewing.
