### ISSUE TITLE
FormModel is missing a `setValue(fieldName: string, value: any)` method

### ISSUE THREAD

**Issue by jskupsik** [xh/hoist-react#3688]
Common sense dictates that there would be a `FormModel.setValue(fieldName: string, value: any)` method on our FormModel class.

We have `FormModel.setValues(values: PlainObject)` as well as `BaseFieldModel.setValue(v: any)`, both of which imply the existence of this missing method.

It isn't particularly difficult to set a field value without this method, but it does feel like a gap in our API.

**Comment by amcclain** [comment]
Seems like this is pretty well covered by `formModel.setValue({myField: 42})` - any downsides to that?  

I'm not opposed to adding a new, explicitly singular API for convenience or clarity, just checking that I'm not missing something re. ability of the existing multi-val method to set a single val.

**Comment by amcclain** [comment]
@jskupsik any thoughts?   On another review, I would rather _not_ have to support multiple signatures on the existing `setValue` function, just to keep the type signatures clean.  I don't see any advantage to the two-arg form of the method vs the one-arg object form.  (Happy to have any other considerations change my mind, of course)
