### ISSUE TITLE
`ErrorMessage` component should be cross-platform

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3693]
We have two versions of the `ErrorMessage` component - one for desktop, one for mobile.  This is problematic for use cases where we have an app-level comp that's cross-platform.

We should migrate to a single cross-platform component or use our "dynamics" concept to support an import that swaps between the two.

**Comment by lbwexler** [comment]
This is a nice idea -- the code is truly identical. One issue is that the APIs are actually different due to the fact that one gets Mobile ButtonProps and the other gets  Desktop ButtonProps.  Sigh.

**Comment by amcclain** [comment]
Yes, exactly - honestly it's frustrating that we have different button components - if I could go back in time doesn't seem like *that* itself should be necessary (different buttons) but all stemming AFAIK from core use of Blueprint and that library declaring itself desktop-only in general.

Assuming that we don't want to block on an entire rethink of buttons - surely we don't - where does that leave us?

Rethinking this component to avoid buttons entirely seems a bit drastic - we could do something with links instead but that seems like it would just be...weird.

Could we create a new props interface for a very restricted set of cross-platform button props (I really don't think we need to support many - we could keep it limited to e.g. text/icon/onClick + layout/styleProps) and then use the dynamics mechanism to instantiate the right platform-specific errorMsg component?

**Comment by amcclain** [comment]
Could we consider accomplishing this (or at least a cheap / initial version of this) by establishing a new set of exports at the top level of our `@xh/hoist/dynamics` package that did the platform-specific switching internally?  Apps do this now in some cases where they have a cross-platform component that needs to render an `errorMessage`, but it seems unfortunate to have to put that into the app code.

```
import {errorMessage as errorMessageDesktop} from '@xh/hoist/dynamics/desktop';
import {errorMessage as errorMessageMobile} from '@xh/hoist/dynamics/mobile';
import {hoistCmp, XH} from '@xh/hoist/core';

export const errorMessage = hoistCmp.factory(props => {
    return XH.isDesktop ? errorMessageDesktop(props) : errorMessageMobile(props);
});
```

**Comment by TomTirapani** [comment]
Closing as this has been achieved as part of https://github.com/xh/hoist-react/pull/3866
