### ISSUE TITLE
Add `omit` to `FormFieldProps`

### ISSUE THREAD

**Issue by minusleaf** [xh/hoist-react#3699]
@lbwexler and I talked about how it was strange for the `omit` field to not be included with `FormFieldProps`, so when extending it to make a custom field and needing that functionality to help show correct/concise form data, it seemed I had to add it in manually.

Example usage:
```
rateField({field: 'someField', omit: someBoolean});
```

`rateField` implementation:
```
export const rateField: RateField = ({inputProps, ...props}) => {
    return formField({
        item: rateInput(inputProps),
        readonlyRenderer: rateElemRenderer(inputProps),
        flex: 1,
        ...props
    });
};

interface RateFieldProps extends FormFieldProps {
    omit?: boolean;
    inputProps?: SomeInputProps;
}

type RateField = (props: RateFieldProps) => ReactElement;
```

**Comment by ghsolomon** [comment]
Closing since `omit` is not part of `FormFieldProps` but rather `ElementSpec<FormFieldProps>`
