### ISSUE TITLE
Blueprint Vertical Tab Switchers look terrible

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#3713]
[From Don]

Also found an issue with the very latest Blueprint release (5.10.4).  Makes vertical tab switchers look terrible. BP switched around some css and we'll need to dance with that in Hoist.

**Comment by febbraiod** [comment]
They added a `gap: 20px` property to the `bp5-tab-list` class. But they also took a 20px right margin away from `.bp4-tab-list > *:not(:last-child)`. So simply removing the "gap: 20px" results in the vertical tab switcher looking better, but bangs up the horizontal tab switcher.

**Comment by febbraiod** [comment]
Blueprint decided they had a bug on their side and fixed. We should just take the fix version (5.3.5) as the minimum version in hoist.
