### ISSUE TITLE
Inline Grid Edit of NumberInput can be lost after quick navigation

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#3717]
[From Jakub, reported at Client]

Has anyone encountered a changes-are-not-immediately-saving bug with numberEditor on the latest hoist/blueprint/ag-grid?
If a user changes a value in a grid column using numberEditor and then, very quickly afterwards, hits ENTER or clicks off the field, the value they just changed to is not saved. It appears to take a couple 100ms to save the value.

It occurs in https://toolbox-dev.xh.io/app/grids/inlineEditing

It does not happen in the last release of the client app, which uses:
Hoist React	62.0.1
React	18.2.0
ag-Grid	30.2.1
Blueprint Core	4.20.2

It does happen in the current dev of the client app, which uses:
Hoist React	65.0.0
React	18.2.0
ag-Grid	31.2.1
Blueprint Core	5.10.4

**Comment by minusleaf** [comment]
The issue in question from Toolbox:
https://github.com/xh/hoist-react/assets/70573025/9539a623-d513-4639-a797-0a48e167c8e9
