### ISSUE TITLE
Content of App disappearing in BlackBerry Access on Chrome

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#3718]
![pic](https://github.com/xh/hoist-react/assets/2307561/201ca16f-a794-46d8-b8b3-db79c07a5a53)

Seems to have broken after https://github.com/xh/hoist-react/pull/3649/files

Working fine in HR 63.x, broken in HR 64

**Comment by TomTirapani** [comment]
Hi guys,

I think this is almost definitely related to the use of these dynamic viewport units, which were first introduced in Hoist 64:
https://github.com/xh/hoist-react/blob/develop/cmp/layout/Viewport.scss#L5-L6

If you disable them in dev tools (i.e. simulate the browser not ignoring them) you get something that looks very similar to the photo above:
![Screenshot 2024-07-09 at 15 25 11](https://github.com/xh/hoist-react/assets/3017757/1085c5c1-9f51-4f40-b5d7-1ed68c1261ab)
