### ISSUE TITLE
`ChartModel.updateHighchartsConfig()` incorrectly updates array-based values

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3725]
Use of lodash `merge` within `updateHighchartsConfig()` does not seem appropriate for array-based values - e.g. `xAxis.categories`.  

The merge function will splice old and new arrays together, so an attempt to update `categories: ['New York', 'London', 'Hong Kong']` to `categories: ['Approved', 'Restricted']` will result in `categories: ['Approved', 'Restricted', 'Hong Kong']` 😦 

Do we ever want this function to merge arrays like this, or did we intend this only for deep-merging of objects? Wondering if we should use `mergeWith` and customize to accept new array values in their entirety.

**Comment by lbwexler** [comment]
yikes!   good catch -- that does seem *really* wrong for what we generally intend when merging configurations ---- surprised we never encountered before

**Comment by lbwexler** [comment]
OK -- started to fix this, but am finding that lodash merge does *not* claim to behave in this way.  in fact, the example they give in mergeWith is where they actually claim to introduce the array merging with the customizer....

**Comment by lbwexler** [comment]
Ah -- I see now -- its actually merging the individual items, to get an
array the size of the longest item.  That's just so deeply weird, I don't
know when you would ever want that for an an array

I had been testing merge({foo: [1, 2]}, foo: [2,3]) which looks like an
assignment -- first array has to be longer to see the behavior!

**Comment by lbwexler** [comment]
Will fix -- have it coded up
