### ISSUE TITLE
Use `Highcharts.Options` type for `ChartModel.highchartsConfig`

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3726]
Would want to look carefully around any complexities with extra modules or things like that, but this would be a *big* upgrade over our current bail-out to `PlainObject` when it comes to getting help writing and updating chart configs.

**Comment by amcclain** [comment]
Ah - the curse of "quick wins" strikes again...

So we deliberately don't import HC at all as a Hoist dep, to make it clear that any project / developers wishing to use it must review and properly license the library according to their terms.

**Comment by lbwexler** [comment]
Looking at highcharts available downloads, I don't see an easy path forward here -- we have gone through much trouble to have the toolkit work without highcharts, and don't think we want to give up on that.
