### ISSUE TITLE
Component prop marked as observable.ref can cause performance issues

### ISSUE THREAD

**Issue by saba-mo** [xh/hoist-react#3769]
Passing an object marked as @observable.ref as a component prop and then accessing it in the top-level component via a getter on the model causes the component's render method to get called in an infinite loop. This was noticed in a client app that was experiencing performance issues. 

The toolbox branch [cmpProps](https://github.com/xh/toolbox/tree/cmpProps) reproduces the issue - just uncomment line 9 destructuring the getter from the model in DetailsPanel.ts in the Recalls example directory. 

Steps to reproduce the issue:
- Object marked as @observable.ref that gets set in its loadAsync method is passed as a component prop.
- The receiving component creates its model, and accesses the component prop via a getter on the model.
- The receiving component accesses the object from its model in the component's top level render method. 

Note that in the client app, the presence of auto refresh seemed to be required to create this loop; however, I'm not sure that's the case in the toolbox example as it seems to happen immediately.

**Comment by amcclain** [comment]
How interesting! Staying tuned - thanks for the comprehensive write up.

**Comment by amcclain** [comment]
@saba-mo just checking to see if you got any more details here - is it still an actionable Hoist ticket? I didn't want to let it fall through the cracks.

**Comment by saba-mo** [comment]
No additional details yet. @lbwexler, do you want to look together?

**Comment by lbwexler** [comment]
its on my shortlist!
