### ISSUE TITLE
Admin log levels configuration grid does not refresh after update

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#3800]
When adding or updating a log level, the entire grid should refresh after any individual update, to reflect potential changes to effective logging levels on other rows.  

Eg I have log level rows for `com.myapp` and `com.myapp.pkg`.  Both start with no override showing default INFO level.  I update parent `com.myapp` to debug.  After update `com.myapp.pkg` should also show effective level of debug.

If after making that update I close the log levels dialog and re-open, I see the correct effective levels across all rows.

**Comment by lbwexler** [comment]
Yes, of course, agree that really is important and would really aid in understanding how this works.

Looked at it, and weirdly we don't have any great hooks for this in RestGridModel.

**Comment by lbwexler** [comment]
actual found a little workaround  see PR -- think making RestGridModel more flexible to handle this is a bigger project, but felt it was worth it to get this fix in ASAP
