### ISSUE TITLE
`TabModel.title` will omit special characters like '&' because we run it through lodash's `startCase`

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#3804]
This appears to happen by default when sourcing the title from the "id" provided in a config object through the TabContainerModel

**Comment by amcclain** [comment]
Sounds like we would benefit from an updated version of `genDisplayName()` 

https://github.com/xh/hoist-react/blob/c6f7eb7440f220e576a5c200228e94ba23b675a1/data/Field.ts#L175

Could relocate out of this file and avoid the use of `startCase` there as well.  

Although it looks to me like this only applies if you are _not_ spec'ing a title and instead having the tab `id` be auto-processed into a display title.  Do you have chars like `&` in your tab IDs also?  That seems a bit weird to me, and potentially a source of bugs if you had routing enabled.  Pls review and confirm when you have a chance?

**Comment by lbwexler** [comment]
Were y'all thinking we would just not call startCase() if certain characters like `&` are included or write a custom startCase()?

I guess the former is at least a better, less surprising heuristic  heuristic for generating a default display name -- although in either case the answer is really for the app to be explicit about what it wants.

**Comment by lbwexler** [comment]
Don and I discussed, and agreed that it was both strange for him to provide an id with special charachters, and easy for him to specify the title directly.  Closing.
