### ISSUE TITLE
Allow Cube Views to opt-out of flattening redundant children

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-react#3843]
Our cube currently has hard-coded logic to flatten "redundant children"; i.e., groups with a single child with the same dimension values: https://github.com/xh/hoist-react/blob/develop/data/cube/row/BaseRow.ts#L66-L75

We should offer a flag to allow cube view queries to opt-out of this behaviour.

**Comment by amcclain** [comment]
"Redundant child" - ouch!

But seriously, I have no doubt there is a specific use case behind this request, and it seems like it should be pretty straightforward to implement, assuming we don't have any strong expectations anywhere else that this processing has been applied (I don't know why there would be).
