### ISSUE TITLE
Admin - activity grid date range filters use local date as latest

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#400]
Admin activity grids (client activity tracking + errors) have a date range filter in the toolbar to limit the activity returned. The end date for the filter is set by default to today as per the client browser.

The issue is that the server might be in a different timezone ahead of the client. (Note this isn't just us Californian's whining about NY 😉 - we have production servers in UTC.)

This means that an admin hitting the activity grids can miss the latest activity unless they push forwards to "tomorrow" at certain times in the day. The UI does allow them to do that, which is good, but there is a very real risk that admins will be confused or, more importantly miss the latest error or activity reports. 

Raises a few questions:
* In what timezone should the date filters be interpreted? Server time? Local time? Some zone that's set via config as the "official" zone for the app?
* Should the server in general provide the client with its timezone and/or current date so the client could be smarter?
* Would not posting an end-date or otherwise handling "latest" be cleaner in any way?

**Comment by amcclain** [comment]
Ah - @lbwexler if you recall when we discussed this last week, I was confused as the app servers I was checking appeared to be in eastern time. But those were the host servers - the docker Tomcats are in UTC, hence the timezone mismatch.

The appropriate timezone for our Docker configs for various clients is another topic, but UTC is hardly unreasonable and the above points still hold.  Would be happy to discuss again anytime as this is a relatively general topic, not limited to any particular admin grid.

**Comment by amcclain** [comment]
@johnbc this is not a critical bug but would be nice to resolve and thought you could help - happy to touch base next week to review as your time allows

**Comment by lbwexler** [comment]
If we make the day filtering just based on *LocalDay* of the visit/error as returned and assigned by the server, this problem just goes away, and that is mostly what we want.

It means that we wouldn't be able to allow the client to show a time-component and do sub-day filtering, but we have never really needed that all these years and  with the ability to sort based on dateCreated and filter on other stuff, I really think this would get us 95% of what we want.
