### ISSUE TITLE
Add "lossless" smart number formatter

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#438]
We often want to shorten the display of very large numbers by using units such as millions (or sometimes billions/thousands). At the same time, it can be problematic to show "rounded" or otherwise inexact values in certain circumstances.

Proposing a "lossless" number formatter that would evaluate an input and output a (potentially) shortened form based on the scale of the number but avoid losing any actual precision.  E.g.
```
12,000,000 -> 12m
12,320,000 -> 12.32m
12,320,500 -> 12,320,500 or 12.3205m
12,320,418 -> 12,320,418
```
For the second-to-last one, we could consider a max/min precision (or "decimal places") config that could provide some control over that choice.

Needless to say, smaller numbers should also work:
```
8 -> 8 (or 8.00 depending on how we handled zero pad)
1.234252 -> 1.234252
```
Finally, should think about how we could best handle thousands as a unit and how to decide when we would go to thousands if enabled.
```
19,000 -> 19k
19,410 -> 19.41k
```

**Comment by amcclain** [comment]
Note this would very likely be a good (and complete) replacement for our quantity formatter - indeed, that's the use-case that is driving this ticket.

**Comment by peterjcoffman** [comment]
@amcclain Would you take a look at the PR for this? I'm not sure precisely what behavior you're looking for.

**Comment by amcclain** [comment]
I like the idea of a `fmtNumberCompact` function that exposes controls over the desired shorthand units, the desired precision, and whether or not any rounding should be allowed. 

I am finding it surprisingly difficult to hold that in my head, however.  

Here is what I am thinking if we do *not* allow rounding - i.e. if we stick to this ticket's core idea of creating a "lossless" formatter:
* Take a new `allowedUnits` parameter - can be a string with any combination of the letters `kmb` for thousands/millions/billions.
  * I think using a simple string will be more convenient than an array. If the letter is included in the string, that unit is enabled. 
  * Would default to `mb` to enable millions and billions only. (Displaying numbers in thousands is a requirement we've had, but is generally a bit weird IMO.)
* Keying off of the existing `precision` parameter, formatter should choose the largest allowed unit it can use to render the number within the given precision (i.e using up to "{precision} decimal places") without any rounding (i.e. while still exactly representing the number). 
  * Precision could default to 2 here.
* It will always fallback to rendering the number in whole units (i.e. no shorthand) if required to avoid rounding.

Where it starts to get more difficult is if we do want to allow for some rounding (i.e. another new param `allowRounding`). Maybe I am somehow over-complicating things or am stuck in my head about it. I keep going in circles somehow so TBH I am just going to throw this comment over the wall for review and then we can come back to it.  (I've spent too long this AM trying to work out a clearer spec and need to move on, but I also don't want to just abandon the thought above.)

**Comment by peterjcoffman** [comment]
>     * Keying off of the existing `precision` parameter, formatter should choose the largest allowed unit it can use to render the number within the given precision (i.e using up to "{precision} decimal places") without any rounding (i.e. while still exactly representing the number).

I have implemented this.

**Comment by amcclain** [comment]
Closing as not immediately actionable.
