### ISSUE TITLE
Tree Component

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#572]
Have an upcoming need for a powerful Tree component for a client app. 

Needs to support the following:

- Item selection handling
- Context menus
- Configurable component to use for tree items
- Drag and Drop re-ordering of nodes

Given the required features, I think it makes sense for this to be an extension of DataView, and is very much in the same vein as #449, with the only addition being the drag and drop support.

ag-grid supports row dragging with tree data: https://www.ag-grid.com/javascript-grid-row-dragging/#row-dragging-tree-data

**Comment by haynesjm42** [comment]
@cnrudd this essentially needs to be at feature parity with what you built recently for a similar client app (though in angularjs)

**Comment by cnrudd** [comment]
Hmm.  @haynesjm42 this does look pretty cool:
https://www.ag-grid.com/javascript-grid-row-dragging/#row-dragging-tree-data
and looks to be at feature parity with the Kendo tree view I implemented.  
It seems to be one better in that it says that multiple nodes can be selected and dragged.

If the client doesn't mind a bit of a 'grid' feel, or if you can hide grid headers/row lines if needed, the AG grid tree view might do the trick.

**Comment by haynesjm42** [comment]
Was thinking that our DataView could serve as a tree component. If provided a TreeStore and once Grid and GridModel support tree data (via #449) it *should* just work for DataView with a bit of wiring.

**Comment by amcclain** [comment]
Closing as not immediately actionable.  If we come across a new demand for this we can find / reopen or start fresh.
