### ISSUE TITLE
Support sizing modes at theme level

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#605]
Provide three (?) standard levels of sizing at the theme level, with a JS API and standard preference to swap between them. Would better accommodate users who prefer very small, data-dense displays as well as those who prefer/require larger font sizes and padding for legibility. 

This could be considered a sibling of the light/dark theme support.

Would require review and (ongoing) testing across the set of components, including the grid and forms, and for desktop and mobile. That makes it a big ticket, undeniably, but perhaps we could implement some basic support that would get us 80% of the way there and provide a pattern we could continue to refine and implement going forwards...

Should also consider how this might interact with the grid's "compact mode" switch....

**Comment by amcclain** [comment]
Updated to reflect simplification of supporting a flag (two modes) for parity with the existing grid feature and because that seems like a more reasonable place to start while still offering a lot of value.

**Comment by lbwexler** [comment]
Updated to reflect that grid now has 4 modes.

**Comment by amcclain** [comment]
Closing as not immediately actionable.
