### ISSUE TITLE
Add affordance for toggling collapse state of  Panel via button.

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#611]
This would probably most naturally be a button in or adjacent to 'headerItems'.  The trickiest thing is the cleanest API to specify it, versus the behavior we have now..

We would need to somehow allow the panel to be collapsible, *without* automatically installing the resize bar the way we currently do.  This could just be a flag or 2 (e.g. 'showResizeSplitter', 'showResizeButton') or a mode "resizeDisplay = "splitter|button". 

Also would be nice to find a decent spot for it when the panel collapses vertically. 

Critical for client apps that are collapsing panels that are not necessarily "docked" within a flexing container.

**Comment by amcclain** [comment]
Quick note to say I don't think we would want the splitter and header-based button to be mutually exclusive.
