### ISSUE TITLE
Configurable Grid Group Row Rendering

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#647]
Would be nice to be able to customize the group row rendering a bit without having to use agOptions. 

Some ideas on what we could/should be able to configure:
* Display value
* Turn off child count
* Expand/Collapse icon?

**Comment by amcclain** [comment]
Agree on all these points.  Perhaps `rowGroupOptions` as a sub-config object to GridModel?

**Comment by amcclain** [comment]
Note that using the new `GridModel.groupRowRenderer` isn't entirely as friendly as it could be. Returning a custom value here will only fill in the "inner" part of the group cell - the expand collapse arrows will still show (which is probably good) but so will the counts (which are more likely to be something developers want to turn off).

You can take over the entire row by supplying a `groupRowElementRenderer` and returning a React element, but then you need to do more work on the styling, and expand/collapse arrows go away again.

We could push farther if desired - maybe using CSS classes to hide child counts, etc. - but will let #1685 close out this ticket for today!
