### ISSUE TITLE
Updated Select input TODOs/issues

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#733]
Umbrella ticket for issues we discover with the new select field:

🐞 Bugs
- [x] Multiselect mode shifts height when at least one value is added.
- [x] Console warning thrown re. react-selects not generating unique DOM IDs (Could this point to some larger issue with rendering?  Some comp instances seem to get a unique ID while others do not...)
- [ ] Does not support HoistInput's 'style' prop
- [x] Validation errors do not highlight - validation styles in general within FormField.scss appear *very* specific to Blueprint - if we can generalize any better we should. 
- [x] Event on esc keypress to close the menu is allowed to propagate, potentially e.g. closing a modal dialog in a sudden and unexpected way.

🎁 Feature TODOs
- [x] Support for custom item renderer.
- [ ] Support for custom options filtering
- [x] Support for truncating very long option lists to avoid perf. issues.

**Comment by amcclain** [comment]
The HoistInput style prop might be tricky - see how react-select uses styled components.
In general I think we need to do a pass at sizing / styling across inputs to get better consistency.

**Comment by cnrudd** [comment]
I am using the new select control in a modal, which is closable by hitting the Escape key.
I had to add some logic to the component that wraps the select control that checks to see if the select is open: 

if it is open, the Escape key event propagation is stopped.  The select control closes, but the modal does not.

If the select is closed the Escape key event propagates, and the modal closes.

Seems like a select in a modal that can be closed by Escape is a pretty common use case.  Maybe we can add a  prop to our select control that prevents 'Escape' propagation if control is open.

**Comment by amcclain** [comment]
Hi - thanks for reporting!

* Is there any reason not to always stop propagation in the case where the select is focused, showing its menu, and esc is pressed? Do we need a prop to opt in/out of that behavior, or should it always do that?
* We should check if we have the same situation with e.g. the date picker.
* That said, in this case is it important that the modal be closable with the esc key?  Not trying to get out of a fix here, but it seems potentially problematic to have a modal that's complex enough to have inputs of any kind (i.e. not a trivial/read-only alert) that will also close itself so readily. I see we do not close the rest editor form pop-up on esc, which I think is good.  We do close the config differ on esc, and it's a good way to see the bug you're reporting and why it's bad. But in that case too I think I might favor not closing the differ on esc. It's complex enough and has enough internal stuff going on that it seems reasonable to press the close button.  (But again, still agree we should stop the event if we can.)

**Comment by cnrudd** [comment]
The modal I am working on is part of a data entry interface.  To maintain feature parity with the interface it is meant to replace, the modal would have to close on Escape.  The end-users are quite insistent on not being forced to reach for the mouse.

To code my escape key event handler, I had to use react-select's onKeyDown prop.  
Whether we make it a permanent or opt in/out feature, we should code it so that onKeyDown can still be used for other customizations.

From the developer's perspective:
If the feeling is that most modals that contain forms will not be closable on escape, then it is probably not worth implementing as a feature (permanent or optional), just to keep our fingerprint on react-select as small as possible.

From the end-user's perspective:
I can't see a reason why Escape key propagation would not always be stopped if the control were open.

It seems like other's agreed with the end-user's perspective, and the lib maintainer even coded this in two years ago:
https://github.com/JedWatson/react-select/pull/1066
then someone else complained about it:
https://github.com/JedWatson/react-select/issues/1335
but got no response.

In the latest version 2 of the code stopPropagation has been removed: https://github.com/JedWatson/react-select/blame/master/src/Select.js#L1145

Maybe in version 2 the solution is to use: menuPortalTarget to put the drop down menu outside of the modal, and then no Escape key handling is needed.  I will test that.  If that does not work, I will ask the lib what happened to their original solution.

**Comment by shravnk** [comment]
Apologies if I am misunderstanding, but do we not already use menuPortalTarget to attach the drop down menu to document body? I have been dealing with a similar issue related to select menus within a popover. I piggybacked off of one of Colin's solutions yesterday to use the onInteraction prop to handle clicks outside the popover (this prop is also available to Dialogs).

I just tried this and was able to prevent Escape press from closing the popover, but only when a select menu is open:

`    @action
    onInteraction = (nextOpenState, e) => {
       const escapePressOnSelectMenu = withDefault(e, false) &&
            withDefault(e.target, false) &&
            withDefault(e.key, false) &&
            e.key === 'Escape' &&
            e.target.id.includes('react-select');
        if (escapePressOnSelect) {
            this.setPopoverDisplay(true);
        }
    };`

**Comment by cnrudd** [comment]
@shravnk Yes, we already do use menuPortalTarget.  I edited my comment probably at the same time as you were writing yours.  Sorry about that.

Your solution is on the popover that contains the select.  My solution is more on the select itself (which is in a dialog, not a popover)

**Comment by shravnk** [comment]
See [this PR](https://github.com/exhi/hoist-react/pull/769) for the minimal validation issue. Did not need to use Blueprint classes in several other instances so made those changes as well.

The lighter onFocus box-shadow we use for the new Select compared to Blueprint is harder to identify when a validation error border is also applied. May be nitpicking though...

**Comment by cnrudd** [comment]
@amcclain In my client work in which I have a select inside a dialog, I found that this commit
221ca61 #diff-7c57d69a6dcea1ae69f31992eab0ca6bR176
does fix the issue of not closing the dialog when when the escape key is hit when the select menu is open.

However, it now prevents the escape key from closing the dialog when the user is focused on a select field that does not have a menu open.

This latter issue is not that big of a deal.  Probably not worth worrying about until someone complains about it.   But if we were to address it, I guess we would need to find some way to examine if the select menu is open to determine whether or not to stop propagation.  Or WAS open if the menu closes before the event propagates to box wrapper.

I had a solution which handled this in the client's code.  It didn't involve a wrapper box, but used a reference and the select components onkeydown handler.    Can discuss if you like.

**Comment by cnrudd** [comment]
I notice while trying to set a select value programmatically that the react-select will only accept values that are strings.

I had a list of options like:  [{id: 100, name: 'test'}, ...]   The 'value' field  was 'id'   .    If tried to set the 
 component value to 100,   it failed.    
I needed to map id.toString() on all option items first.

react-select uses flow (https://flow.org/en/docs/types/objects/) 
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L589
https://github.com/JedWatson/react-select/blob/master/src/types.js#L4
https://github.com/JedWatson/react-select/blob/master/src/types.js#L15
and does most of its equality comparison with ===  not == so we are stuck with this.

Wondering if it is worth, in our wrapper, to convert the value fields we get to strings.
Could be done in this toOption function https://github.com/exhi/hoist-react/blob/develop/desktop/cmp/form/inputs/Select.js#L238
line 250: value: src[valueField].toString()

It might mean restricting our acceptable value types to string, number, or boolean.  That would still satisfy most usecases, I think.

**Comment by amcclain** [comment]
Closing as we have addressed most of these items.  Will let any others loop back around to us in new tickets.
