### ISSUE TITLE
RecordActionBar gridModel vs selModel

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-react#770]
RecordActionBar currently takes both a `gridModel` and a `selModel` prop. It is a very common use-case where the `selModel` is coming from the `gridModel` so it would be nice if RecordActionBar was intelligent enough to get it from the `gridModel` if it was not explicitly provided to the component.

The complication here is that there are cases where we want to pass a `gridModel` but not a `selModel`, such as the usage in RestForm, where there is only 1 Record that the action should know about and should not care at all about the selected records in the grid (and in fact wants `selectedRecords` to only contain the specific Record for the form), but it does need the `gridModel` in order to carry out the action. Seems over-complicated and confusing all-around so a cleanup here would be nice.

**Comment by amcclain** [comment]
Closed due to inactivity - can reopen if this comes up again.
