### ISSUE TITLE
Panel resize should have a mode to delay resize until dragger is dropped

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-react#847]
In Sencha world the resizables do this (see PIQ admin Client Activity tab). Client is requesting the same for HR.

**Comment by lbwexler** [comment]
Anselm and I discussed, and this looks like a pretty big lift. Let's review the specifics tommorrow and understand the issues the client is facing here?

**Comment by amcclain** [comment]
As per my comment just now on another unrelated ticket #845 I'd like to suggest we close tickets tagged as future if we really don't think we have the bandwidth / incentive to work on them in the near-to-medium term (and they aren't bugs).

@febbraiod and @lbwexler - let's quickly touch base (if you haven't already) to ensure this request doesn't have more weight behind it than we realize, and to ensure we understand the particular pain point / motivation (beyond it generally being a sane / nice idea).

**Comment by febbraiod** [comment]
As to the weight of this request, the client has brought it up at two separate meetings and referred to it as 'mega-lag'. Then a third time over chat. We have informed him that the ticket has been filed with Hoist and, at least for the moment, that seems to have satisfied him.

However, my personal opinion is that the priority should be rather low. The client already sort of hinted that he imagines the user would set the width once and probably leave it there rather than frequently and quickly dragging between widths. So, from a practical perspective I think we could close this ticket, but I wouldn't be surprised at all if it keeps coming up in the future.

**Comment by lbwexler** [comment]
Closing this, for potential work in the future, as discussed above.

**Comment by amcclain** [comment]
Re-opening at client request for review

**Comment by lbwexler** [comment]
Colin brought this ticket came back from the dead and the fix looks great!  Thanks for your persistence Colin
