### ISSUE TITLE
Add Hoist enumeration and implementation of "intents"

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-react#855]
Intents appear in our API, and we rely on the blueprint implementation on the desktop.

It might be nice to remove our direct usage of the bp intent and just have our own enumeration and associated css classes which we can use on desktop and mobile.

RecordAction supports an intent, for example, and should be a cross-platform object.

**Comment by amcclain** [comment]
@TomTirapani and I were recently looking at a project where we wanted to setup some standardized row-level shading in a grid that would have mapped nicely onto intents. 

I thought it would be a useful Hoist feature to supply readymade CSS classes that keyed off of our CSS variables to provide background shading for grid rows (and cells?), tuned to work with other standard grid styling as well as light/dark themes.

We could tackle these separately if that works out better, but I this was another nice example of a way intent could be brought in and applied more generally, outside of the BP-sourced components.

**Comment by amcclain** [comment]
We added some relevant CSS classes as part of button refactoring that was done this summer.

Closing as not otherwise actionable at this time.
