### ISSUE TITLE
Grid support for column filters

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#858]
The Excel-style column filters supported by ag-Grid are a common and popular feature for business users, despite having some usability drawbacks.

They are currently enabled for several key applications via agOptions escape hatches. We would like to minimize the use of those, but even more so the fact that these filtering options are internal to the grid creates recurring issues such as:
* Column filters don't interact with StoreFilterField
* Grid exports can't respect column filters
* StoreCountLabel and other store-based utils don't return accurate counts, etc.
* Reading/writing filter state across re-renders and data loads can be problematic or require ad hoc workarounds.

This ticket is a subset of #243 and all those larger discussions will still require working out, but these filters are important enough IMO to warrant this dedicated issue.

**Comment by lbwexler** [comment]
Client asked me about this again today.  (His users very much want the export to respect the column filters.)

**Comment by amcclain** [comment]
Closing as dupe of more descriptive issue #2360
