### ISSUE TITLE
Core layout components review

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#859]
I have a set of layout-related changes I would like to propose:

1 - Remove `display:flex` from `Box`. Right now `Box` is functionally the equivalent of `HBox` (as default flex-direction is `row`). I propose Box instead be a thin enhancement over `div` with the key addition of `layoutSupport` for declarative specification of inline styles. 

2 - Use the layout CSS classes (`xh-vbox` etc) to implement the specific flexing and other behaviors, vs specifying these styles inline. I think it's more natural to have the CSS classes be driving their corresponding behaviors.

3 - Get `HBox` and `VBox` to process child sizing (flex/width/height/min-max) in a way that more closely matches how things worked in Ext, favoring what I see as a more understandable and predictable handling of child dimensions vs. a direct flexbox implementation.  I.e. 
* If a child is given an exact pixel dimension, it should stay that size. 
* Flex children should be space filling, and flex proportions should remain constant. 
* If fixed/min dimensions overflow the container's available space, it should scroll. 

I know we've discussed how sticking with the default flexbox behavior is easy to justify, but in the end I maintain that this is sub-optimal for the rich component apps we're looking to build, where predictable control over sizing is paramount.

**Comment by lbwexler** [comment]
1 & 2 sound good to me.

3 seems like an insanely ambitious project.  Ext had an entire layout lifecycle built to support their layouts.  We have flexbox.    

Would love to talk about this more -- if you have a vision of how this would be implemented I would be psyched to hear it!

**Comment by TomTirapani** [comment]
Implemented 1 & 2 in branches here:
https://github.com/exhi/hoist-react/pull/1084
https://github.com/exhi/toolbox/pull/175
We should be careful to check client apps / components for cases where they are using box / frame and relying on them being functionally equivalent to hbox / hframe.

**Comment by TomTirapani** [comment]
Discussed with Lee - closing this for now, as the pull request is significantly behind.
