### ISSUE TITLE
PropType definitions for layoutSupport components

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#900]
We should be able to define a set of PropType definitions that can be mixed into the propTypes for all Hoist components implementing our `@layoutSupport` decorator.

I think this would be worth the effort to more comprehensively document all props supported via the decorator, and in general make the layout props more discoverable for any given component that has them.

**Comment by amcclain** [comment]
Started on this (will open WIP P/R).  Still think it's worth doing - propTypes are respected properly by React and will warn if provided with invalid value types.

Annoyingly, my main impetus here was to get hinting in the IDE, but IJ has a longstanding bug out that prevents that from working for this (or any other case where we are spreading propTypes for composed components): https://youtrack.jetbrains.com/issue/WEB-22063

Have not checked other tools such as VSCode, which might be more commonly used by Hoist React developers who are also writing JSX.

**Comment by lbwexler** [comment]
Colin -- can you see if the bug that Anselm mentions in comment above is also an issue in vscode?

**Comment by cnrudd** [comment]
I just checked in VSCode.  I checked out the layoutSupportPropTypes branch of hoist-react and the columnPackageLocation branch of toolbox.  I tried completion on a box element (both elementFactory and JSX.  No luck.  I did not get suggestions for any of the proptypes in layoutSupportProps.

**Comment by amcclain** [comment]
Just chatting with Colin - note that he was not seeing Intellisense auto-completion for any proptypes - not just the new ones added via the spread operator from the LayoutSupport static.

So we should investigate that first as I am sure VSCode should be able to do that, then see if they more advanced case works or not.

**Comment by amcclain** [comment]
Note that IntelliJ should soon get proper support for propTypes mixed in via object spreads - https://youtrack.jetbrains.com/issue/WEB-22063 - so I would still like to complete this work once verified we have it right.

**Comment by cnrudd** [comment]
I looked into this today with the latest version of IntelliJ: 19.1 and the latest updates in the layoutSupportPropTypes branch.

I tested writing a new button component into a toolbox component. 
  
When using JSX, I got propType suggestions only for the props defined directly on the Button component.   But I think this needs to be tested with the layouSupportPropTypes branch cut as a release and toolbox used in non-wrapper dev mode.  Even though I am running with startWithHoist, INtellij is using the npm lib version of hoist react to read the button component.

**Comment by amcclain** [comment]
Thanks for looking again here.  I gave this a shot and was able to get IJ hinting at spread props, although annoyingly the type information seemed to be lost. You can see here that both direct button props and layoutSupport props are in the list, but only the former have the type info:

<img width="795" alt="Screen Shot 2019-04-15 at 4 18 24 PM" src="https://user-images.githubusercontent.com/225806/56362186-22516f00-619e-11e9-9885-35a195c98d40.png">

I had my IJ using the special [webpack config file](https://github.com/exhi/hoist-react/blob/develop/webpack.config.intellij.js) we have in hoist-react, and was also testing within HR code.  Even still I found the hinting a bit flaky - once or twice it seemed stuck and didn't show up.

Anyway, I still think this is worth doing for completeness and, even if IJ doesn't work beautifully now hopefully it will improve and other tools might do better. Spreading prop-types seems like it's a valid and well-supported pattern.  

@YanaNirvana would appreciate if you could help us with this one - not urgent but will route to you and we can discuss any time.  Will be another opportunity to take a tour of the existing componentry. I will also send you another prop-type related ticket could do at the same time.

**Comment by cnrudd** [comment]
@amcclain Thanks for the tip about [webpack config file](https://github.com/exhi/hoist-react/blob/develop/webpack.config.intellij.js)

**Comment by amcclain** [comment]
@cnrudd going through older tickets and this one seemed worth revisiting - ping me anytime, not urgent

**Comment by amcclain** [comment]
Closed due to inactivity. At this point, another approach such as TS def. files seems more likely to me.
